. \" @(#)calc.1	1.1 01/04/20 Copyright 1985-2001 J. Schilling
. \" Manual page for calc
. \"
.if t .ds a \v'-0.55m'\h'0.00n'\z.\h'0.40n'\z.\v'0.55m'\h'-0.40n'a
.if t .ds o \v'-0.55m'\h'0.00n'\z.\h'0.45n'\z.\v'0.55m'\h'-0.45n'o
.if t .ds u \v'-0.55m'\h'0.00n'\z.\h'0.40n'\z.\v'0.55m'\h'-0.40n'u
.if t .ds A \v'-0.77m'\h'0.25n'\z.\h'0.45n'\z.\v'0.77m'\h'-0.70n'A
.if t .ds O \v'-0.77m'\h'0.25n'\z.\h'0.45n'\z.\v'0.77m'\h'-0.70n'O
.if t .ds U \v'-0.77m'\h'0.30n'\z.\h'0.45n'\z.\v'0.77m'\h'-.75n'U
.if t .ds s \(*b
.if t .ds S SS
.if n .ds a ae
.if n .ds o oe
.if n .ds u ue
.if n .ds s sz
.TH CALC 1 "2022/09/08" "J\*org Schilling" "Schily\'s USER COMMANDS"
.SH NAME
calc \- simple integer calculator that accepts decimal/hex/octal and outputs decimal/hex/octal/binary
.SH SYNOPSIS
.B
calc
[
.I options
]
.SH DESCRIPTION
The 
.B calc
command may be used to do simple integer calculations or to convert
numbers from one radix to another.
.PP
.B Calc
reads commands from stdin and prints the result to stdout.
The input radix for numbers may be decimal (default),
octal (if starting with a '0') or hexadecimal (if starting with "0x").
The output is always printed in four radixes: 
.BR decimal , 
.BR octal , 
.B hexadecimal
and
.BR binary .
The decimal variant is printed as signed and as unsigned representation.
.PP
The result is printed in two variants using 32 bit and 64 bit representations
for the numbers.
.SH "INPUT FORMAT"
.PP
.B Calc
accepts three types of input lines:
.TP 16
.B "one number"
The input line is one number only.
.sp
In this case the number is converted only to the different output formats.
.TP
.B "unary operator"
The input line is a unary operator followed by a number
.sp
In this case the unary operator is applied to the number and the result
is printed in all output formats.
.TP
.B "binary operator"
The input line is a number followed by a binary operator followed by a second number.
.sp
In this case the binary operator is applied to the numbers and the result
is printed in all output formats.

.SH OPERATORS
.TP 16
.B +
Binary arithmetic addition.
.TP
.B \-
Binary arithmetic subtraction.
.TP
.B *
Binary arithmetic multiplication.
.TP
.B <<
Binary logical left shift.
.TP
.B >>
Binary logical right shift.
.TP
.B ^
Binary logical exclusive or as in C language.
.TP
.B &
Binary logical and masking as in C language.
.TP
.B |
Binary logical or as in C language.
.TP
.B !
Unary logical not as in C language.
.TP
.B ~
Unary logical one's complement as in C language.
.TP
.B %
Binary arithmetic remainder from division.
.TP
.B /
Binary arithmetic division.
.SH OPTIONS
.TP
.B \-help
Prints a short summary of the 
.B calc
options and exists.
.TP
.B \-version
Prints the 
.B calc
version number string and exists.

.\" .SH EXAMPLES
.\" .SH ENVIRONMENT
.\" .SH FILES
.SH "SEE ALSO"
.BR  dc (1),
.BR  bc (1).
.\" .SH NOTES
.SH BUGS
.PP
None currently known.
.PP
Mail bugs and suggestions to
.B schilytools@mlists.in-berlin.de
or open a ticket at
.B https://codeberg.org/schilytools/schilytools/issues
.PP
The mailing list archive may be found at:
.PP
.nf
.B
https://mlists.in-berlin.de/mailman/listinfo/schilytools-mlists.in-berlin.de
.fi
.SH AUTHORS
.nf
J\*org Schilling and the schilytools project authors.
.fi
.SH "SOURCE DOWNLOAD"
The source code for
.B calc
is included in the
.B schilytools
project and may be retrieved from the
.B schilytools
project at Codeberg at:
.LP
.B
https://codeberg.org/schilytools/schilytools/
.LP
The download directory is:
.LP
.B
https://codeberg.org/schilytools/schilytools/releases
