#ident @(#)Makefile	1.3 16/06/16 
###########################################################################
# Sample makefile for sub directory makes
###########################################################################
SRCROOT=	..
RULESDIR=	RULES
include		$(SRCROOT)/$(RULESDIR)/rules.top
###########################################################################

ALLTARGETS=	$(ALLTARGETS_NT)
DIRS=		sccs man

###########################################################################
include		$(SRCROOT)/$(RULESDIR)/rules.tst
include		$(SRCROOT)/$(RULESDIR)/rules.dir
###########################################################################
