'\" te
.\"  @(#)printf.1	1.3 17/11/21 Copyright 2017 J. Schilling */
.\"
.\" The contents of this file are subject to the terms of the
.\" Common Development and Distribution License, Version 1.0 only
.\" (the "License").  You may not use this file except in compliance
.\" with the License.
.\"
.\" See the file CDDL.Schily.txt in this distribution for details.
.\" A copy of the CDDL is also available via the Internet at
.\" http://www.opensource.org/licenses/cddl1.txt
.\"
.\" When distributing Covered Code, include this CDDL HEADER in each
.\" file and include the License file CDDL.Schily.txt from this distribution.
.\"
.if t .ds a \v'-0.55m'\h'0.00n'\z.\h'0.40n'\z.\v'0.55m'\h'-0.40n'a
.if t .ds o \v'-0.55m'\h'0.00n'\z.\h'0.45n'\z.\v'0.55m'\h'-0.45n'o
.if t .ds u \v'-0.55m'\h'0.00n'\z.\h'0.40n'\z.\v'0.55m'\h'-0.40n'u
.if t .ds A \v'-0.77m'\h'0.25n'\z.\h'0.45n'\z.\v'0.77m'\h'-0.70n'A
.if t .ds O \v'-0.77m'\h'0.25n'\z.\h'0.45n'\z.\v'0.77m'\h'-0.70n'O
.if t .ds U \v'-0.77m'\h'0.30n'\z.\h'0.45n'\z.\v'0.77m'\h'-0.75n'U
.if t .ds s \\(*b
.if t .ds S SS
.if n .ds a ae
.if n .ds o oe
.if n .ds u ue
.if n .ds s sz
.TH printf 1 "2022/08/20" "J\*org Schilling" "User Commands"
.SH NAME
printf \- write formatted output
.SH SYNOPSIS
.LP 
.nf 
\fBprintf\fR \fIformat\fR [\fIargument\fR].\|.\|. 
.fi 
.SH DESCRIPTION
.LP
The
.B printf
command writes formatted operands to the standard output.
The
.I argument
operands are formatted under control of the
.I format
operand.
The
.I format
operand is treated like a
.BR printf (3)
format string and the escape sequences
.BR '\ea' ,
.BR '\eb' ,
.BR '\ef' ,
.BR '\en' ,
.BR '\er' ,
.BR '\et' ,
.BR '\ev' ,
.B '\e\e'
and
.BR '\eddd' ,
where
.I ddd
is one to three octal digits, are expanded as if they were in a C string.
.sp
In addition to the format specifiers
.BR %c ,
.BR %s ,
.BR %d ,
.BR %i ,
.BR %o ,
.BR %u ,
.BR %x ,
.BR %X ,
.BR %e ,
.BR %E ,
.BR %f ,
.BR %F ,
.BR %g ,
.BR %G ,
the format
.BR %b 
is supported.
The integers are handled internally as
.B intmax_t
to avoid range problems
even though only the standard int type specifiers are supported in the
.I format
operand.
The format
.BR %b 
is treated like
.BR %s 
except that escape sequences in the argument string are expanded as with the
.B echo
command.
.sp
Field width and precision may be specified either numerically in the
.I format
operand
or via the
.B '*'
format specifier and related arguments.
.sp
The
.BR printf (3)
flag characters
.BR '+' ,
.BR '\ ' ,
.B '#'
and
.BR '0'
are supported.
.sp
The format strings
.BI % n $
and
.BI * m $\c
, where
.I n
or
.I m
are decimal integers in the range 1 ..
.IR maxargs ,
allow one to specify the
position in the parameter list.
See
.BR printf (3)
for more information.
.sp
The
.I format
operand is reused as often as necessary to satisfy the
.I argument
operands.
If the
.I format
operand contains more format specifiers than
.I argument
operands have been specified, string formats are treated as if an empty string
has been supplied and integer arguments are treated as if a 0 has been supplied.

.SH OPTIONS
.TP
none
.\" .SH EXAMPLES
.\" .SH ENVIRONMENT
.SH "EXIT STATUS"
.LP
The following exit values are returned:
.TP
.B 0
Successful completion.
.TP
.B >0
An error occurred.
.\" .SH FILES
.\" .TP
.\" none
.SH "SEE ALSO"
.BR bosh (1),
.BR printf (3).
.\" .SH DIAGNOSTICS
.\" .SH NOTES

.SH BUGS
.PP
None currently known.
.PP
Mail bugs and suggestions to
.B schilytools@mlists.in-berlin.de
or open a ticket at
.BR https://codeberg.org/schilytools/schilytools/issues .
.PP
The mailing list archive may be found at:
.PP
.nf
.BR https://mlists.in-berlin.de/mailman/listinfo/schilytools-mlists.in-berlin.de .
.fi

.SH AUTHORS
J\*org Schilling wrote
.B printf
in 2015 - 2017. It is now maintained by the schilytools project
authors.

.SH "SOURCE DOWNLOAD"
The source code for
.B printf
is included in the
.B schilytools
project and may be retrieved from the
.B schilytools
project at Codeberg at
.LP
.BR https://codeberg.org/schilytools/schilytools .
.LP
The download directory is
.LP
.BR https://codeberg.org/schilytools/schilytools/releases .
