. \" @(#)termcap.1	1.5 09/07/12 Copyright 2008 J. Schilling
. \"  Manual page for termcap
. \"
.if t .ds a \v'-0.55m'\h'0.00n'\z.\h'0.40n'\z.\v'0.55m'\h'-0.40n'a
.if t .ds o \v'-0.55m'\h'0.00n'\z.\h'0.45n'\z.\v'0.55m'\h'-0.45n'o
.if t .ds u \v'-0.55m'\h'0.00n'\z.\h'0.40n'\z.\v'0.55m'\h'-0.40n'u
.if t .ds A \v'-0.77m'\h'0.25n'\z.\h'0.45n'\z.\v'0.77m'\h'-0.70n'A
.if t .ds O \v'-0.77m'\h'0.25n'\z.\h'0.45n'\z.\v'0.77m'\h'-0.70n'O
.if t .ds U \v'-0.77m'\h'0.30n'\z.\h'0.45n'\z.\v'0.77m'\h'-.75n'U
.if t .ds s \(*b
.if t .ds S SS
.if n .ds a ae
.if n .ds o oe
.if n .ds u ue
.if n .ds s sz
.TH TERMCAP 1L "09/07/12" "J\*org Schilling" "Schily\'s USER COMMANDS"
.SH NAME
termcap \- a termcap compiler
.SH SYNOPSIS
.B
termcap
[
.I options
]
.SH DESCRIPTION
.B termcap
reads termcap entries and outputs them in standard order and
with standard escape sequences. This allows to convert termcap
files into a comparable format.
.PP
The termcap database is an ASCII representation of the data
so people may believe that there is no need for a compiler.
Syntax checks and unification however are a property of compilers.
The
.B termcap
progam checks for correct data types, outputs all entries in a unique
order and recodes all strings with the same escape notation.
This is needed in to compare two entries and it makes life easier.
.PP
When
.B termcap
compiles entries, it checks the entries for noncompliances. If any problems
were found, it inserts comments in the form:
.sp
.BI "# NOTICE(" name ")" " some reason
.sp
or
.sp
.BI "# BAD(" name ")" " some reason
.sp
before the related termcap entry.
These comments should be carefully checked.
Frequent problems are illegally escaped colons \e: instead of \e072 that in 
most cases have been created by defective
.B terminfo
software.

.SH OPTIONS
.TP
.B \-help
Prints a short summary of the
.BR termcap (1)
options and exists.
.TP
.B \-version
Prints the
.BR termcap (1)
version number string and exists.
.TP
.B \-dooctal
When printing terminal capabilities, prefer octal output like
.B \e003
before escape sequences like
.BR ^C .
.TP
.B \-dumplist
Dump the complete internal list of terminal capabilities.
.TP
.BI if= filename
Read the file 
.I filename
with many termcap entries and produce compiled output in standard order
on 
.BR stdout .
This option is used in order to recompile a whole set of termcap entries.
.TP
.B \-inorder
Output all capabilities in the standard order. First the boolean
capabilities, then the numeric capabilities and at last the string
capabilities. Without
.BR \-inorder ,
the obsolete capabilities are printed last.
.TP
.B \-gnugoto
Allow the GNU tgoto() format extexsions %C and %m.
.TP
.B \-nowarn
Do not warn about incorrect entries that could be fixed by asuming that the
problem is a result from not correctly converting escape sequences in terminfo 
syntax to termcap syntax. For this purpose, currently null characters
.RB ( \e0 )
are converted to 
.BR \e200 .
In addition, the escape sequences
.BR \ee ,
.BR \e: ,
.BR \e, ,
.B \es
and
.B \el
are mapped to ESCAPE, ':', ',', ' ' and LINEFEED.
.TP
.B \-tc
Follow
.B tc=
entries and generate cumulative output.
Amongst others, this allows to retrieve the cumulative size of the related
termcap entry.
.B Termcap
normally does not interpret
.B tc=
entries in order to allow the entries to be reused the same way they are
in the termcap file.
.TP
.B \-v
Increment verbose level.
By default, 
.B termcap
only prints a recoded termcap entry. With increasing verbose level, more 
information on the termcap entry is printed.
With a higher verbose level,
.B termcap
prints the size of the termcap entry.

.SH ENVIRONMENT
.TP
.B HOME
To find the private files like
.B ~/.termcap
.TP
.B TERM
The type of terminal for which the output should be formatted.
.TP
.B TERMCAP
This environment variable holds either a precompiled termcap entry
or the pathname to be used to find a termcap database file.
If it holds a precompiled entry that does not match the
.B TERM
environment, the termcap database is parsed as if the
.B TERMCAP 
environment is not set.
.TP
.B TERMPATH
If 
.B TERMCAP
is empty, then the
.B TERMPATH
environment is scanned for pathnames of files that contain a
.B termcap
database.
It holds a list of filenames separated by colons or spaces (i.e.,  ":" or " ").
If the TERMPATH symbol is not set, the files
.I $HOME/.termcap
and
.I /etc/termcap
are scanned in that order.
If a pathname in 
.B TERMPATH
does not start with a slash ("/"), then the 
.B HOME
environment is prepended to the name.

.SH FILES
.TP
.B /etc/termcap
The system's terminal capabilities database.
.TP
.B ~/.termcap
The private terminal capabilities database.

.SH NOTES

.SH BUGS
