#ident @(#)Makefile	1.11 15/04/22 
###########################################################################
# Sample makefile for installing manual pages
###########################################################################
SRCROOT=	../..
RULESDIR=	RULES
include		$(SRCROOT)/$(RULESDIR)/rules.top
###########################################################################

TARGET=.	# Avoid an empty target

XMK_FILE=	adminman.mk bdiffman.mk cdcman.mk changesetman.mk \
		combman.mk deltaman.mk \
		diffman.mk \
		getman.mk helpman.mk prsman.mk prtman.mk rmdelman.mk \
		sactman.mk \
		sccs-adminman.mk sccs-cdcman.mk sccs-combman.mk \
		sccs-cvtman.mk \
		sccs-deltaman.mk sccs-getman.mk sccs-helpman.mk \
		sccs-logman.mk \
		sccs-prsman.mk sccs-prtman.mk sccs-rmdelman.mk \
		sccs-sactman.mk sccs-sccsdiffman.mk sccs-ungetman.mk \
		sccs-valman.mk \
		sccschangesetman.mk sccscvtman.mk \
		sccsdiffman.mk sccsfileman.mk sccsman.mk ungetman.mk \
		sccslogman.mk valman.mk whatman.mk \
		sccs-rcs2sccsman.mk rcs2sccsman.mk \
		vcman.mk

###########################################################################
include		$(SRCROOT)/$(RULESDIR)/sub.htm
include		$(SRCROOT)/$(RULESDIR)/rules.ins
include		$(SRCROOT)/$(RULESDIR)/rules.hlp
###########################################################################
