#ident @(#)Makefile	1.20 20/06/29 
###########################################################################
SRCROOT=	../..
RULESDIR=	RULES
include		$(SRCROOT)/$(RULESDIR)/rules.top
###########################################################################

MK_FILES=	adminman.mk bdiffman.mk cdcman.mk changesetman.mk \
		combman.mk deltaman.mk \
		diffman.mk \
		getman.mk helpman.mk prsman.mk prtman.mk rmdelman.mk \
		sactman.mk \
		sccs-adminman.mk sccs-cdcman.mk sccs-checkman.mk \
		sccs-combman.mk \
		sccs-cvtman.mk \
		sccs-delgetman.mk sccs-deltaman.mk sccs-deleditman.mk \
		sccs-editman.mk sccs-editorman.mk \
		sccs-getman.mk sccs-helpman.mk sccs-histfileman.mk \
		sccs-infoman.mk sccs-initman.mk sccs-istextman.mk \
		sccs-logman.mk \
		sccs-prsman.mk sccs-prtman.mk sccs-rmdelman.mk \
		sccs-rootman.mk \
		sccs-sactman.mk sccs-sccsdiffman.mk sccs-tellman.mk \
		sccs-ungetman.mk \
		sccs-valman.mk \
		sccschangesetman.mk sccscvtman.mk \
		sccsdiffman.mk sccsfileman.mk sccsman.mk ungetman.mk \
		sccslogman.mk valman.mk whatman.mk \
		sccs-rcs2sccsman.mk rcs2sccsman.mk \
		vcman.mk

###########################################################################
include		$(SRCROOT)/$(RULESDIR)/rules.mks
###########################################################################
