#ident @(#)Makefile	1.2 07/02/11 
###########################################################################
# Sample makefile for installing manual pages
###########################################################################
SRCROOT=	../..
RULESDIR=	RULES
include		$(SRCROOT)/$(RULESDIR)/rules.top
###########################################################################

XMK_FILE=	adminman.mk bdiffman.mk cdcman.mk combman.mk deltaman.mk \
		getman.mk helpman.mk prsman.mk prtman.mk rmdelman.mk \
		sactman.mk \
		sccs-adminman.mk sccs-cdcman.mk sccs-combman.mk \
		sccs-deltaman.mk sccs-getman.mk sccs-helpman.mk \
		sccs-prsman.mk sccs-prtman.mk sccs-rmdelman.mk \
		sccs-sactman.mk sccs-sccsdiffman.mk sccs-ungetman.mk \
		sccs-valman.mk \
		sccsdiffman.mk sccsfileman.mk sccsman.mk ungetman.mk \
		sccslogman.mk valman.mk whatman.mk

###########################################################################
include		$(SRCROOT)/$(RULESDIR)/sub.htm
include		$(SRCROOT)/$(RULESDIR)/rules.ins
###########################################################################
