'\" te
.\" @(#)sccs-admin.1	1.27 13/06/16 Copyright 2007-2013 J. Schilling
.\" CDDL HEADER START
.\"
.\" The contents of this file are subject to the terms of the
.\" Common Development and Distribution License ("CDDL"), version 1.0.
.\" You may only use this file in accordance with the terms of version
.\" 1.0 of the CDDL.
.\"
.\" A full copy of the text of the CDDL should have accompanied this
.\" source.  A copy of the CDDL is also available via the Internet at
.\" http://www.opensource.org/licenses/cddl1.txt
.\"
.\" When distributing Covered Code, include this CDDL HEADER in each
.\" file and include the License file at usr/src/OPENSOLARIS.LICENSE.
.\" If applicable, add the following below this CDDL HEADER, with the
.\" fields enclosed by brackets "[]" replaced with your own identifying
.\" information: Portions Copyright [yyyy] [name of copyright owner]
.\"
.\" CDDL HEADER END
.\"  Copyright (c) 2002, Sun Microsystems, Inc. All Rights Reserved.
.TH sccs-admin 1 "2013/06/16" "SunOS 5.11" "User Commands"
.SH NAME
sccs-admin, admin \- create and administer SCCS history files
.SH SYNOPSIS
.LP
.nf
\fB/usr/ccs/bin/admin\fR [\fB-bhnoz\fR] [\fB-a\fR \fIusername\fR | \fIgroupid\fR]... 
    [\fB-d\fR \fIflag\fR] ... [\fB-e\fR \fIusername\fR | \fIgroupid\fR]... 
    [\fB-f\fR \fIflag\fR [\fIvalue\fR]] ... [\fB-i\fR [\fIfilename \fR]] [\fB-m\fR \fImr-list\fR] 
    [\fB-r\fR\fIrelease\fR] [\fB-t\fR [\fIdescription-file\fR]] [\fB-y\fR [\fIcomment\fR]] \fIs.filename\fR...
.fi

.SH DESCRIPTION
.sp
.LP
The \fBadmin\fR command creates or modifies the flags and other parameters of SCCS history files. Filenames of SCCS history files begin with the `\fBs.\fR' prefix, and are referred to as \fBs.\fRfiles, or ``history'' files.
.sp
.LP
The named \fBs.\fRfile is created if it does not exist already. Its parameters are initialized or modified according to the options you specify.  Parameters not specified are given default values when the file is initialized, otherwise they remain unchanged.
.sp
.LP
If a directory name is used in place of the \fIs.filename\fR argument, the \fBadmin\fR command applies to all \fBs.\fRfiles in that directory.  Unreadable \fBs.\fRfiles produce an error.  The use of `\fB\(mi\fR\&' as the \fIs.filename\fR argument indicates that the names of files are to be read from the standard input, one \fBs.\fRfile per line.
.SH OPTIONS
.sp
.LP
The following options are supported:
.sp
.ne 3
.TP
\fB\fB-a\fR \fIusername\fR | \fIgroupid\fR\fR
Adds a user name, or a numerical group \fBID\fR, to the list of users who may check deltas in or out. If the list is empty, any user is allowed to do so.
.sp
.ne 3
.TP
\fB\fB-b\fR\fR
Forces encoding of binary data. Files that contain ASCII NUL or other control characters, or that do not end with a \fBNEWLINE\fR, are recognized as binary data files. The contents of such files are stored in the history file in encoded form. See \fBuuencode\fR(1C) for details about
the encoding. This option is normally used in conjunction with \fB-i\fR to force \fBadmin\fR to encode initial versions not recognized as containing binary data.
.sp
.ne 3
.TP
\fB\fB-d\fR \fIflag\fR\fR
Deletes the indicated \fIflag\fR from the SCCS file. The \fB-d\fR option may be specified only for existing \fBs.\fRfiles. See \fB-f\fR for the list of recognized flags.
.sp
.ne 3
.TP
\fB\fB-e\fR \fIusername\fR | \fIgroupid\fR\fR
Erases a user name or group \fBID\fR from the list of users allowed to make deltas.
.sp
.ne 3
.TP
\fB\fB-f\fR \fIflag\fR [\fIvalue\fR]\fR
Sets the indicated \fIflag\fR to the (optional) \fIvalue\fR specified. The following flags are recognized: 
.RS
.ne 3
.TP 7
\fB\fBb\fR\fR
Enables branch deltas. When \fBb\fR is set, branches can be created using the \fB-b\fR option of the SCCS \fBget\fR command (see \fBsccs-get\fR(1)).
.sp
.ne 3
.TP
\fB\fBc\fR\fIceil\fR\fR
Sets a ceiling on the releases that can be checked out. \fIceil\fR is a number less than or equal to 9999. If \fBc\fR is not set, the ceiling is 9999.
.sp
.ne 3
.TP
\fB\fBd\fR\fIsid\fR\fR
Specifies the default delta number, or  \fBSID\fR, to be used by an SCCS \fBget\fR command.
.sp
.ne 3
.TP
\fB\fBf\fR\fIfloor\fR\fR
Sets a floor on the releases that can be checked out. The floor is a number greater than 0 but less than 9999. If \fBf\fR is not set, the floor is 1.
.sp
.ne 3
.TP
.BI i\fR[ value\fR]
Treats the `\fBNo id keywords (cm7)\fR' message issued by an SCCS \fBget\fR or \fBdelta\fR command as an error rather than a warning.
.sp
If the parameter
.I value
to the
.RB ` i '
flag is not empty, then it holds a line fragment with keywords
starting with a
.RB ` "%" ',
e.g.
.br
.RB "        `" "%\&Z%%\&M%	%\&I% %\&E%" '
.br
This line fragment needs to exactly match a part of a line in the file
and to result in expanded keywords.
The string must begin with a keyword, and may not have embedded
.B newline
characters.
If no match was found, an attempt to check in a new delta will fail.
The parameter to the
.RB ` i '
flag is a
.B \s-1SUN\s+1
extension that was adopted by the
.B POSIX
standard.
.sp
.ne 3
.TP
.B j
Allow concurrent
.B get \-e
calls for editing on the same base
.B SID
of an SCCS file.
This allows multiple concurrent updates to take place on the same version of the SCCS file.
.sp
.ne 3
.TP
.B la
.TP
\fB\fBl\fR \fIrelease\fR[\fB,\fR \fIrelease\fR...]\fR
Locks the indicated list of releases against deltas.
An SCCS `\fBget\fR \fB-e\fR' command fails when applied against a locked release.
The following syntax is accepted to specify a list:
.sp
.nf
<list> ::= \fBa\fR | <range-list>
<range-list> ::= <range> | <range-list>, <range>
<range> ::= <SID>
.fi
.sp
The character
.B a
in the
.I list
is the equivalent to specifying all releases for the named SCCS file.
The non-terminal
.I <SID>
in
.I range
is the delta number of an existing delta associated with the SCCS file.
.ne 3
.TP
\fB\fBm\fR\fImodule\fR\fR
Supplies a value for the module name to which the \fBsccs-admin.1\fR keyword is to expand. If the \fBm\fR flag is not specified, the value assigned is the name of the SCCS file with the leading \fBs.\fR removed.
.sp
.ne 3
.TP
\fB\fBn\fR\fR
Creates empty releases when releases are skipped. These null (empty) deltas serve as anchor points for branch deltas.
.sp
.ne 3
.TP
\fB\fBq\fR\fIvalue\fR\fR
Supplies a  \fIvalue\fR to which the \fB\fR keyword is to expand when a read-only version is retrieved with the SCCS \fBget\fR command.
.sp
.ne 3
.TP
\fB\fBs\fR\fInumber\fR\fR
Specifies how many lines of code are scanned for the SCCS keyword.
.sp
This flag is a
.B \s-1SUN\s+1
extension that does not exist in historic
.B sccs
implementations.
.sp
.ne 3
.TP
\fB\fBt\fR\fItype\fR\fR
Supplies a value for the module type to which the \fB\fR keyword is to expand.
.sp
.ne 3
.TP
\fB\fBv\fR[\fIprogram\fR]\fR
Specifies a validation \fIprogram\fR for the \fBMR\fR numbers associated with a new delta. The optional \fIprogram\fR specifies the name of an \fBMR\fR number validity checking \fIprogram\fR. If this flag is set when creating an SCCS file, the \fB-m\fR option must also be used,
in which case the list of \fBMR\fRs may be empty.
.sp
.ne 3
.TP
.B x
Enable 
.B sccs
extensions that are not implemented in classical 
.B sccs
variants. If the
.RB ` x '
flag is enabled, the keywords
.BR %\&d\&% ", " %\&e\&% ", " %\&g\&% 
and
.B %\&h\&%
are expanded even though the
.RB ` y '
flag was not set.
.sp
This flag is a
.B \s-1SCHILY\s+1
extension that does not exist in historic
.B sccs 
implementations. 
.sp
This version of SCCS implements compatibility support for a SCO SCCS
extension that sets the executable bit in the file permissions of a
gotten file if the
.BR x -flag
was set in the history file with no parameter. This version of SCCS
does not allow to set this variant of the
.BR x -flag
in the history file.
If you like to get executable files from SCCS, set the executable
bit in the file permissions of the history file.

.br
.ne 4
.TP
\fB\fBy\fR[\fIvalue\fR\fB,\fR[\fIvalue\fR]]\fR
Specifies the SCCS keywords to be expanded. If no
.I value
is specified, no keywords will be expanded.
The value `\fB*\fP'
controls the expansion of the \fB%\&sccs.include.\fIfilename\fB\&%\fR keyword.
If the letters
.BR d ", " e ", " g
or
.B h
are present, the related keywords are expanded even though the
.RB ` x '
flag was not set.
.sp
If
.I value
is set to an empty string, the
.RB ` "No id keywords (cm7)" '
message will not be created even though no keyword was expanded.
.sp
This flag is a
.BR \s-1SUN\s+1 / SCHILY
extension that does not exist in historic
.B sccs 
implementations. 
.RE
.sp
.ne 3
.TP
\fB\fB-h\fR\fR
Checks the structure of an existing \fBs.\fRfile (see \fBsccsfile\fR(4)), and compares a newly computed check-sum with one stored in the first line of that file. \fB-h\fR inhibits writing on the file and so nullifies the effect of any other options.
.sp
.ne 3
.TP
\fB\fB-i\fR[\fIfilename\fR]\fR
Initializes the history file with text from the indicated file.
This text constitutes the initial delta, or set of checked-in changes.
If
.I filename
is omitted, the initial text is obtained from the standard input.
Omitting the
.B \-i
option altogether creates an empty
.BR s. file.
You can only initialize one
.BR s. file
with text using
.BR \-i .
This option implies the
.B \-n
option.
.sp
If you like to initialize more than one
.BR s. file
in one call, use the
.B \-N
option.
.sp
.ne 3
.TP
\fB\fB-m\fR \fImr-list\fR\fR
Inserts the indicated Modification Request (MR) numbers into the commentary for the initial version. When specifying more than one MR number on the command line, \fImr-list\fR takes the form of a quoted, space-separated list. A warning results if the \fBv\fR flag is not set or the \fBMR\fR validation fails.
.sp
.ne 3
.TP
.BI -N bulk-spec
Creates a bulk of new SCCS history files.
This option allows to do an efficient mass creation of SCCS history files
and to initialize the SCCS history files from named files that
are the respective counterpart to the actual SCCS history file.
.sp
The following option types are supported:
.RS
.TP 10
.B \-N
The file name parameters to the
.B admin
command are not
.I s.filename
files but the names of the g-files.
The
.I s.filename
names are automatically derived from the g-file names by prepending
.B s.
to the last path name component.
.TP
.B \-Ns.
The file name parameters to the
.B admin
command are
.I s.filename
files.
The the g-files names are automatically derived by removing
.B s.
from the beginning of last path name component of the
.IR s.filename.
.TP
.BI \-N dir
The file name parameters to the
.B admin
command are not
.I s.filename
files but the names of the g-files.
The
.I s.filename
names are put into directory
.IR dir ,
the names are automatically derived from the g-file names by prepending
.IB dir /s.
to the last path name component.
.TP
.BI \-N dir /s.
The file name parameters to the
.B admin
command are
.I s.filename
files in directory
.IR dir .
The the g-files names are automatically derived by removing
.IB dir /s.
from the beginning of last path name component of the
.IR s.filename.
.PP
A typical value for
.I dir
is
.BR SCCS .
.PP
If
.I bulk-spec
starts with a
.BR `,' ,
.BR admin (1)
renames the g-file from where the SCCS history file was initialized from
to
.B ,name
similar to what happens with
.BR sccs create .
It is recommended to let
.BR admin (1)
rename the original file as tis file usually contains unexpanded keywords and as
this file usually is writable.
.PP
In order to overcome the limited number of
.BR exec (2)
arguments, it is recommended to use `\fB\(mi\fR\&'
as the file name parameter for
.B admin
and to send a list of path names to
.BR stdin .
.PP
This option is a
.B SCHILY
extension that does not exist in historic
.B sccs
implementations.
.RE
.sp
.ne 3
.TP
\fB\fB-n\fR\fR
Creates a new SCCS history file.
.sp
.ne 3
.TP
.B \-o
Use the original time of the existing file for the delta time
when creating a new
.BR s. file.
.sp
This option is a
.B SCHILY
extension that does not exist in historic
.B sccs
implementations.
.sp
.ne 3
.TP
\fB\fB-r\fR\fIrelease\fR\fR
Specifies the release for the initial delta. \fB-r\fR may be used only in conjunction with \fB-i\fR. The initial delta is inserted into release 1 if this option is omitted. The level of the initial delta is always \fB1\fR. Initial deltas are named \fB1.1\fR by default.
.sp
.ne 3
.TP
\fB\fB-t\fR\fB[\fR\fIdescription-file\fR\fB]\fR\fR
Inserts descriptive text from the file \fIdescription-file\fR. When  \fB-t\fR is used in conjunction with \fB-n\fR, or \fB-i\fR to initialize a new s.file, the \fIdescription-file\fR must be supplied. When modifying the description for an existing file: a \fB-t\fR option without
a \fIdescription-file\fR removes the descriptive text, if any; a \fB-t\fR option with a \fIdescription-file\fR replaces the existing text.
.sp
.ne 3
.TP
.B \-V
Prints the
.B admin
version number string and exists.
.sp
.ne 3
.TP
.B \-V6
When used together with
.B \-i
of
.BR \-n ,
.BR admin (1)
will create a 
.B "SCCS v6
history file instead of a
.B "SCCS v4
history file.
.B "SCCS v6
history files are not understood by historic SCCS implementations.
See
.BR sccsfile (4)
for more information on the new features.
.sp
.ne 3
.TP
\fB\fB-y\fR\fB[\fR\fIcomment\fR\fB]\fR\fR
Inserts the indicated \fIcomment\fR in the ``\fBComments:\fR'' field for the initial delta. Valid only in conjunction with \fB-i\fR or \fB-n\fR. If \fB-y\fR option is omitted, a default comment line is inserted that notes the date and time the history file was created.
.sp
.ne 3
.TP
\fB\fB-z\fR\fR
Recomputes the file check-sum and stores it in the first line of the \fBs.\fRfile. \fBCaution:\fR It is important to verify the contents of the history file (see \fBsccs-val\fR(1), and the \fBprint\fR subcommand in \fBsccs\fR(1)), since using \fB-z\fR on a truly corrupted file may prevent detection of the error.

.SH EXAMPLES
.LP
\fBExample 1 \fRPreventing SCCS keyword expansion
.sp
.LP
In the following example, \fB10\fR lines of \fBfile\fR will be scanned and only the \fBW,Y,X\fR keywords will be interpreted:

.sp
.in +2
.nf
example% \fBsccs admin \-fs10 file\fR
example% \fBsccs admin \-fyW,Y,X file\fR
example% \fBget file\fR
.fi
.in -2
.sp

.LP
\fBExample 2 \fRPreventing SCCS keyword expansion and suppressing the
.RB ` "No id keywords (cm7)" '
warning
.sp
.LP
In the following example, no keywords will be interpreted and no warning will be generated:

.sp
.in +2
.nf
example% \fBsccs admin \-fy file\fR
example% \fBget file\fR
.fi
.in -2
.sp

.LP
\fBExample 3 \fRMass entering files with auto-initialization
.sp
.LP
In the following example, all files in the usr/src tree will be put under SCCS
and the SCCS history files will be put into SCCS sub directories:

.sp
.in +2
.nf
example% \fBfind usr/src -type f | sccs admin -NSCCS -\fR
.fi
.in -2
.sp

.LP
\fBExample 4 \fRMass entering files with auto-initialization
.sp
.LP
In the following example, all files in the usr/src tree will be put under SCCS
and the SCCS history files will be put into SCCS sub directories. Each original
.I file
will be renamed to
.I ,file
after the
.I file
has been successfully put under SCCS control:

.sp
.in +2
.nf
example% \fBfind usr/src -type f | sccs admin -N,SCCS -\fR
.fi
.in -2
.sp

.LP
\fBExample 5 \fREntering all files in a directory with auto-initialization
.sp
.LP
In the following example, all files in the current directory will be put under SCCS
and the SCCS history files will be put into the SCCS sub directory:

.sp
.in +2
.nf
example% \fBsccs admin -NSCCS .\fR
.fi
.in -2
.sp

.SH ENVIRONMENT VARIABLES
.sp
.LP
See \fBenviron\fR(5) for descriptions of the following environment variables that affect the execution of \fBalias\fR and \fBunalias\fR: \fBLANG\fR, \fBLC_ALL\fR, \fBLC_CTYPE\fR, \fBLC_MESSAGES\fR, and \fBNLSPATH\fR.
.SH EXIT STATUS
.sp
.LP
The following exit values are returned:
.sp
.ne 2
.mk
.na
\fB\fB0\fR\fR
.ad
.RS 5n
.rt  
Successful completion.
.RE

.sp
.ne 2
.mk
.na
\fB\fB1\fR\fR
.ad
.RS 5n
.rt  
An error occurred.
.RE

.SH FILES
.sp
.ne 2
.TP 15
.BI e. file
temporary file to hold an uuencoded version of the
.B g-file
in case of an encoded history file

.sp
.ne 2
.TP
.BI s. file
history file

.sp
.ne 2
.TP
.BI SCCS/s. file
history file in SCCS subdirectory

.sp
.ne 2
.TP
.BI x. file
temporary copy of the
.BR s. file;
renamed to the
.BR s. file
after completion.

.sp
.ne 2
.TP
.BI z. file
temporary lock file contains the binary process id in host byte order
followed by the host name

.SH ATTRIBUTES
.sp
.LP
See \fBattributes\fR(5) for descriptions of the following attributes:
.sp

.sp
.TS
tab() box;
cw(2.75i) |cw(2.75i) 
lw(2.75i) |lw(2.75i) 
.
ATTRIBUTE TYPEATTRIBUTE VALUE
_
AvailabilitySUNWsprot
_
Interface StabilityStandard
.TE

.SH SEE ALSO
.LP
.BR sccs (1),
.BR sccs-cdc (1),
.BR sccs-comb (1),
.BR sccs-delta (1),
.BR sccs-get (1),
.BR sccs-help (1),
.BR sccs-prs (1),
.BR sccs-prt (1),
.BR sccs-rmdel (1),
.BR sccs-sact (1),
.BR sccs-sccsdiff (1),
.BR sccs-unget (1),
.BR sccs-val (1),
.BR sccscvt (1),
.BR sccslog (1),
.BR bdiff (1), 
.BR diff (1), 
.BR what (1),
.BR changeset (4),
.BR sccsfile (4),
.BR attributes (5),
.BR environ (5),
.BR standards (5).

.SH DIAGNOSTICS
.sp
.LP
Use the SCCS \fBhelp\fR command for explanations (see \fBsccs-help\fR(1)).
.SH WARNINGS
.sp
.LP
The last component of all SCCS filenames must have the `\fBs.\fR' prefix. New SCCS files are given mode \fB444\fR (see \fBchmod\fR(1)). All writing done by \fBadmin\fR is to a temporary file with an \fBx.\fR prefix, created with mode \fB444\fR for a new SCCS file, or with the same mode as an existing SCCS file. After successful
execution of \fBadmin\fR, the existing \fBs.\fRfile is removed and replaced with the \fBx.\fRfile. This ensures that changes are made to the SCCS file only when no errors have occurred.
.sp
.LP
It is recommended that directories containing SCCS files have permission mode \fB755\fR, and that the \fBs.\fRfiles themselves have mode \fB444\fR. The  mode for directories allows only the owner to modify the SCCS files contained in the directories, while the mode of the \fBs.\fRfiles prevents all modifications except those performed using SCCS commands.
.sp
.LP
If it should be necessary to patch an SCCS file for any reason, the mode may be changed to \fB644\fR by the owner to allow use of a text editor. However, extreme care must be taken when doing this. The edited file should \fIalways\fR be processed by an `\fBadmin\fR \fB-h\fR' command to check for corruption, followed by an `\fBadmin\fR \fB-z\fR' command to generate a proper check-sum. Another `\fBadmin\fR \fB-h\fR' command is recommended to ensure that the resulting \fBs.\fRfile is valid.
.sp
.LP
\fBadmin\fR uses a temporary lock file, starting with the `\fBz.\fR' prefix, to prevent simultaneous updates to the \fBs.\fRfile. See \fBsccs-get\fR(1) for further information about the `\fBz.\fRfile'.
