. \" %Z%%M%	%I% %E% Copyright 2007 J. Schilling
. \"  Manual Seite fuer sccs-admin
. \"
.if t .ds a \v'-0.55m'\h'0.00n'\z.\h'0.40n'\z.\v'0.55m'\h'-0.40n'a
.if t .ds o \v'-0.55m'\h'0.00n'\z.\h'0.45n'\z.\v'0.55m'\h'-0.45n'o
.if t .ds u \v'-0.55m'\h'0.00n'\z.\h'0.40n'\z.\v'0.55m'\h'-0.40n'u
.if t .ds A \v'-0.77m'\h'0.25n'\z.\h'0.45n'\z.\v'0.77m'\h'-0.70n'A
.if t .ds O \v'-0.77m'\h'0.25n'\z.\h'0.45n'\z.\v'0.77m'\h'-0.70n'O
.if t .ds U \v'-0.77m'\h'0.30n'\z.\h'0.45n'\z.\v'0.77m'\h'-0.75n'U
.if t .ds s \\(*b
.if t .ds S SS
.if n .ds a ae
.if n .ds o oe
.if n .ds u ue
.if n .ds s sz
.TH SCCS-ADMIN 1 "07/01/27" "J\*org Schilling" "Schily\'s USER COMMANDS"
.SH NAME
sccs-admin, admin \- create and administer SCCS history files
.SH SYNOPSIS

.B /usr/ccs/bin/admin
.RB [ \-bhnz ]
.RB [ \-a
.IR username " | " groupid
.RB "] \&... [" \-d
.IR flag
.RB "] \&... [" \-e
.IR username " | " groupid
.RB "] \&... ["
.BI \-f flag
.RI [ value ]] 
\&... [
.B \-i
.RI [ filename ]]
.RB [ \-m
.IR mr-list ]
.RB [ \-r
.IR release ]
.RB [ \-t
.RI [ description-file ]]
.RB [ -y
.RI [ comment ]]
.IR s\&.filename \&...

.SH DESCRIPTION
.PP
This is a placeholder as Sun did forget to OpenSource sccs-admin.1

.SH OPTIONS
...TP
...B \-help

.SH FILES

.SH "SEE ALSO"

.BR sccs (1), 
.BR sccs-cdc (1),
.BR sccs-comb (1),
.BR sccs-delta (1),
.BR sccs-get (1),
.BR sccs-help (1), 
.BR sccs-prs (1), 
.BR sccs-prt (1), 
.BR sccs-rmdel (1),
.BR sccs-sact (1),
.BR sccs-sccsdiff (1),
.BR sccs-unget (1);
.BR sccs-val (1),
.BR what (1),
.BR sccsfile (4).
.SH NOTES


.SH BUGS
