'\" te
.\" @(#)sccs-get.1	1.28 14/09/15 Copyright 2007-2014 J. Schilling
.\" CDDL HEADER START
.\"
.\" The contents of this file are subject to the terms of the
.\" Common Development and Distribution License ("CDDL"), version 1.0.
.\" You may only use this file in accordance with the terms of version
.\" 1.0 of the CDDL.
.\"
.\" A full copy of the text of the CDDL should have accompanied this
.\" source.  A copy of the CDDL is also available via the Internet at
.\" http://www.opensource.org/licenses/cddl1.txt
.\"
.\" When distributing Covered Code, include this CDDL HEADER in each
.\" file and include the License file at usr/src/OPENSOLARIS.LICENSE.
.\" If applicable, add the following below this CDDL HEADER, with the
.\" fields enclosed by brackets "[]" replaced with your own identifying
.\" information: Portions Copyright [yyyy] [name of copyright owner]
.\"
.\" CDDL HEADER END
.\" Copyright (c) 1999, Sun Microsystems, Inc. All Rights Reserved
.if t .ds a \v'-0.55m'\h'0.00n'\z.\h'0.40n'\z.\v'0.55m'\h'-0.40n'a
.if t .ds o \v'-0.55m'\h'0.00n'\z.\h'0.45n'\z.\v'0.55m'\h'-0.45n'o
.if t .ds u \v'-0.55m'\h'0.00n'\z.\h'0.40n'\z.\v'0.55m'\h'-0.40n'u
.if t .ds A \v'-0.77m'\h'0.25n'\z.\h'0.45n'\z.\v'0.77m'\h'-0.70n'A
.if t .ds O \v'-0.77m'\h'0.25n'\z.\h'0.45n'\z.\v'0.77m'\h'-0.70n'O
.if t .ds U \v'-0.77m'\h'0.30n'\z.\h'0.45n'\z.\v'0.77m'\h'-0.75n'U
.if t .ds s \\(*b
.if t .ds S SS
.if n .ds a ae
.if n .ds o oe
.if n .ds u ue
.if n .ds s sz
.TH sccs-get 1 "2014/09/15" "SunOS 5.11" "User Commands"
.SH NAME
sccs-get, get \- retrieve a version of an SCCS file
.SH SYNOPSIS
.LP
.B /usr/ccs/bin/get\fR
.RB [ -beFgkmnopst ]
.RB [ -l
[p]]
.RB [ -a\c
.IR sequence ]
.br
.RB "    [" -c
.I date-time
|
.BI -c date-time\c
]
.RB [ -G\c
.IR g-file ]
.RB [ -w\c
.IR %\&W%-string ]
.br
.RB "    [" -i
.I sid-list
|
.BI -i sid-list\c
]
.RB [ -q\c
.RI [ nsedelim "]] \c
.RB [ -r
.RI [ sid ]]
.br
.RB "    [" -x
.I sid-list
|
.BI -x sid-list\c
]
.RB [ -z\c
.RI [ cmr "]] \c
.IR s.filename ...

.LP
.nf
.B "/usr/xpg4/bin/get \c
.RB [ -beFgkmnopst "] \c
.RB [ "-l \c
[p]] \c
.RB [ -a\c
.IR sequence ]
.br
.RB "    [" "-c \c
.I date-time \c
| \c
.BI -c date-time\c
] \c
.RB [ -G\c
.IR g-file "] \c
.RB [ -w\c
.IR %\&W%-string ]
.br
.RB "    [" "-i \c
.I sid-list \c
| \c
.BI -i sid-list\c
] \c
.RB [ -q\c
.RI [ nsedelim "]] \c
.RB [ "-r \c
.I sid \c
| \c
.BI -r sid\c
]
.br
.RB "    [" "-x \c
.I sid-list \c
| \c
.BI -x sid-list\c
] \c
.RB [ -z\c
.RI [ cmr "]] \c
.IR s.filename ...
.fi

.SH DESCRIPTION

.LP
The \fBget\fR utility retrieves a working copy from the SCCS history file, according to the specified options.
.sp

.LP
For each \fIs.filename\fR argument, \fBget\fR displays the  SCCS delta \fBID\fR (SID) and number of lines retrieved.
.sp

.LP
If a directory name is used in place of the \fIs.filename\fR argument, the \fBget\fR command applies to all \fBs.\fRfiles in that directory. Unreadable \fBs.\fRfiles produce an error; processing continues with the next file (if any). The use of `\fB\(mi\fR' as the \fIs.filename\fR argument indicates that the names of files are to be read from the standard input, one \fBs.\fRfile per
line.
.sp

.LP
The retrieved file normally has the same filename base as the \fBs.\fRfile, less the prefix, and is  referred to as the \fBg-\fRfile.
.sp

.LP
For each file processed, \fBget\fR responds (on the standard output) with the \fBSID\fR being accessed, and with the number of lines retrieved from the \fBs.\fRfile.
.sp

.SH OPTIONS

.LP
The following options are supported:
.sp

.sp
.ne 2
.TP 13
\fB\fB-a\fR\fIsequence\fR\fR
Retrieves the version corresponding to the indicated delta sequence number. This option is used primarily by the SCCS \fBcomb\fR command (see 
\fBsccs-comb\fR(1)). For users, \fB-r\fR is an easier way to specify a version. The \fB-a\fR option supersedes the \fB-r\fR option when both are used.
.sp
.ne 2
.TP
\fB\fB-b\fR\fR
Creates a new branch. Used with the \fB-e\fR option to indicate that the new delta should have a \fBSID\fR in a new branch. Instead of incrementing the level for version to be checked in, \fBget\fR indicates in the \fBp.\fRfile that the delta to be checked in should either initialize a new branch and sequence (if there is no existing branch at the current level), or
increment the branch component of the \fBSID\fR. If the \fBb\fR flag is not set in the \fBs.\fRfile, this option is ignored.
.sp
.ne 2
.TP
\fB\fB-c\fR \fIdate-time\fR
.TP
\fB-c\fR\fIdate-time\fR\fR
Retrieves the latest version checked in prior to the date and time indicated by
the
.I date-time
argument.
.I date-time
takes the form:
.sp

.sp
 \fIyy\fR[\fImm\fR[\fIdd\fR[ \fIhh\fR[\fImm\fR[\fIss\fR]\|]\|]\|]\|]
.sp

.sp
Units omitted from the indicated date and time default to their maximum possible
values; that is
.B \-c7502
is equivalent to
.BR \-c750228235959 .
Values of
.I yy
in the range
.BR 69 \(mi 99
refer to the twentieth century. Values in the range
.BR 00 \(mi 68
refer to the twenty-first century.
Any number of non-numeric characters may separate
the various 2 digit components. If white-space characters occur, the
.I date-time
specification must be quoted.
.sp
A
.I date-time
specification in the form:
.sp
 \fIyyyy/\fR[\fImm\fR[\fIdd\fR[\fIhh\fR[\fImm\fR[\fIss\fR]\|]\|]\|]\|]
.sp
refers to a 4-digit year and allows to specify a year outside the
range
.BR 1969 \(mi 2068 .
.sp
.ne 2
.TP
\fB\fB-e\fR\fR
Retrieves a version for editing. With this option, \fBget\fR places a lock on the \fBs.\fRfile, so that no one else can check in changes to the version  you have checked out. If the \fBj\fR flag is set in the \fBs.\fRfile, the lock is advisory: \fBget\fR issues a warning message. Concurrent use of `\fBget\fR  \fB-e\fR' for different \fBSID\fRs is allowed. However, \fBget\fR will not check out a version of the file if a writable version is present in the directory. All SCCS file protections stored in the \fBs.\fRfile, including the release ceiling, floor, and authorized user list, are honored by `\fBget\fR \fB-e\fR'.
.sp
.ne 2
.TP
.B \-F
Enforce to retrieve the
.BR g. file
even if a SID specific checksum missmatch has been detected.
.sp
.ne 2
.TP
\fB\fB-g\fR\fR
Gets the SCCS version \fBID\fR, without retrieving the version itself. Used to verify the existence of a particular \fBSID\fR.
.sp
.ne 2
.TP
\fB\fB-G\fR\fInewname\fR\fR
Uses \fInewname\fR as the name of the retrieved version.
.sp
.ne 2
.TP
\fB\fB-i\fR \fIsid-list\fR
.TP
\fB-i\fR\fIsid-list\fR\fR
Specifies a list of deltas to include in the retrieved version. The included deltas are noted in the standard output message. \fIsid-list\fR is a comma-separated list of \fBSID\fRs. To specify a range of deltas, use a  `\fB\(mi\fR' separator instead of a comma, between two \fBSID\fRs in the list.
.sp
.ne 2
.TP
\fB\fB-k\fR\fR
Suppresses expansion of \fBID\fR keywords. \fB-k\fR is implied by the \fB-e\fR.
.sp
.ne 2
.TP
.BR \-l \|[\| p \|] 
Retrieves a summary of the delta table (version log) and write it to a
listing file, with the
.RB ` l. '
prefix (called
.RB ` l. file').
When 
.B \-lp
is used, write the summary onto the standard output.
.sp
.ne 2
.TP
.B \-L
Treated as if
.B \-lp
was given.
.sp
.ne 2
.TP
\fB\fB-m\fR\fR
Precedes each retrieved line with the \fBSID\fR of the delta in which it was added to the file. The \fBSID\fR is separated from the line with a TAB.
.sp
.ne 2
.TP
\fB\fB-n\fR\fR
Precedes each line with the \fB%\&M%\fR \fBID\fR keyword and a TAB. When both the \fB-m\fR and \fB-n\fR options are used, the \fBID\fR keyword precedes the \fBSID\fR, and the line of text.
.sp
.ne 3
.TP
.B \-o
Retrieves the file under the original time of the requested version.
.sp
Use this option with care, as it may be in conflict with
.BR make (1)
rules. Using
.RB ` "get -o" '
thus may cause
.B make 
to perform an automatic retrival of the latest version as the
.BR s. file
is newer than the gotten file, or cause
.B make
to skip the compilation
as the compilation result is already newer than the gotten file.
.sp
This option is a
.B SCHILY
extension that does not exist in historic
.B sccs
implementations.
.sp
.ne 2
.TP
\fB\fB-p\fR\fR
Writes the text of the retrieved version to the standard output. All messages that normally go to the standard output are written to the standard error instead.
.sp
.ne 3
.TP
.BI -q\fR[ nsedelim\fR]
Enable
.B NSE
mode.
If
.B NSE
mode is enabled, several
.B NSE
related extensions may be used.
In this release, the value of
.I nsedelim
is ignored.
.sp
In NSE mode,
.B get
never issues a warning about missing
.BR "id keyword" s.
.sp
This option is an undocumented
.B \s-1SUN\s+1
extension that does not exist in historic
.B sccs 
implementations.
.sp
.ne 2
.TP
\fB\fB-s\fR\fR
Suppresses all output normally written on the standard output. However, fatal error messages (which always go to the standard error) remain unaffected.
.sp
.ne 2
.TP
\fB\fB-t\fR\fR
Retrieves the most recently created (top) delta in a given release (for example: \fB-r1\fR).
.sp
.ne 2
.TP
.BI -w %\&W%-string
The
.I %\&W%-string
is used as a replacement for the
.B %\&W%
keyword.
If
.B \-w
was not specified, 
.B %\&W%
is expanded to
.BR "%\&Z%%\&M%  %\&I%" ,
otherwise the argument from
.B \-w
is used.
.sp
This option is an undocumented
.B SUN
extension that does not exist in historic
.B sccs
implementations.
.sp
.ne 2
.TP
.BI -z\fR[ cmr\fR] 
Append MR number to CMR list for CMF extensions.
.sp
This option is an undocumented
.B SUN
extension that does not exist in historic
.B sccs
implementations.
.ne 3
.TP
.BI \-C dir
Specify the base directory for the
.B g-file
relative to the current working directory.
By default, the
.B g-file
is created in the current directory (independent from
the location of the 
.BI s. file\fR.
.ne 3
.TP
.B \-V
Prints the
.B get
version number string and exists.

.SS /usr/ccs/bin/get

.sp
.ne 2
.TP 13
.B \-d
Do not print the number of gotten lines.
.sp
This option is an undocumented
.B SUN
extension that does not exist in historic
.B sccs
implementations.
.sp
.ne 2
.TP
\fB\fB-r\fR[\fIsid\fR]\fR
Retrieves the version corresponding to the indicated \fBSID\fR (delta).
.sp

.sp
The \fBSID\fR for a given delta is a number, in Dewey decimal format, composed of two or four fields: the \fIrelease\fR and \fIlevel\fR fields, and for branch deltas, the \fIbranch\fR and \fIsequence\fR fields.  For instance, if \fB1.2\fR is the \fBSID\fR, \fB1\fR is the release, and \fB2\fR is the level number.  If \fB1.2.3.4\fR is the \fBSID,\fR \fB3\fR is the branch and \fB4\fR is the sequence number.
.sp

.sp
You need not specify the entire \fBSID\fR to retrieve a version with \fBget\fR. When you omit \fB-r\fR altogether, or when you omit both release and level, \fBget\fR normally retrieves the highest release and level.  If the \fBd\fR flag is set to an \fBSID\fR in the \fBs.\fRfile and you omit the \fBSID\fR, \fBget\fR retrieves the default
version indicated by that flag.
.sp

.sp
When you specify a release but omit the level, \fBget\fR retrieves the highest level in that release. If that release does not exist, \fBget\fR retrieves highest level from the next-highest existing release.
.sp

.sp
Similarly with branches, if you specify a release, level and branch, \fBget\fR retrieves the highest sequence in that branch.
.sp

.sp
.ne 2
.TP
\fB\fB-x\fR \fIsid-list\fR
.TP
\fB-x\fR[\fIsid-list\fR]\fR
Excludes the indicated deltas from the retrieved version. The excluded deltas are noted in the standard output message. \fIsid-list\fR is a comma-separated list of \fBSID\fRs. To specify a range of deltas, use a  `\fB\(mi\fR' separator instead of a comma, between two  \fBSID\fRs in the list.

.RE

.SS /usr/xpg4/bin/get

.ne 2
.TP 13
\fB\fB-r\fR \fIsid\fR
.TP
\fB-r\fR\fIsid\fR\fR
Same as for \fB/usr/ccs/bin/get\fR except that \fBSID\fR is mandatory.
.sp
.ne 2
.TP
\fB\fB-x\fR \fIsid-list\fR
.TP
\fB-x\fR\fIsid-list\fR\fR
Same as for \fB/usr/ccs/bin/get\fR except that
.B sid-list
is mandatory.

.SH OUTPUT

.SS /usr/ccs/bin/get

.LP
The output format for \fB/usr/ccs/bin/get\fR is as follows:
.sp

.LP
.in +2
.nf
\fB"%s\en%d lines\en"\fR, <\fISID\fR>, <\fInumber of lines\fR>
.fi
.in -2
.sp

.SS /usr/xpg4/bin/get

.LP
The output format for \fB/usr/xpg4/bin/get\fR is as follows:
.sp

.LP
.in +2
.nf
\fB"%s\en%d\en"\fR, <\fISID\fR>, <\fInumber of lines\fR>
.fi
.in -2
.sp

.SH USAGE

.LP
Usage guidelines are as follows:
.sp

.SS ID Keywords

.LP
In the absence of \fB-e\fR or \fB-k\fR, \fBget\fR expands the following  \fBID\fR keywords by replacing them with the indicated values in the text of the retrieved source.
.sp

.LP

.sp
.TS
tab() box;
cw(.79i) |cw(4.71i) 
lw(.79i) |lw(4.71i) 
.
\fIKeyword\fR\fIValue\fR
_
\fB%\&A%\fRT{
Shorthand notation for an ID line with 
data for 
\fBwhat\fR(1)\fB: %\&Z%%\&Y%  %\&M%  %\&I%%\&Z%\fR
T}
_
\fB%\&B%\fRSID branch component
_
\fB%\&C%\fRT{
Current line number. Intended for identifying messages output by the program such as ``\fIthis shouldn't have happened\fR'' type errors.  It is \fInot\fR intended to be used on every line to provide sequence numbers.
T}
_
\fB%\&D%\fRCurrent date: \fIyy\fR/\fImm\fR/\fIdd\fR
_
\fB%\&d%\fRCurrent date: \fIyyyy\fR/\fImm\fR/\fIdd\fR
_
\fB%\&E%\fRT{
Date newest applied delta was created: \fIyy\fR/\fImm\fR/\fIdd\fR
T}
_
\fB%\&e%\fRT{
Date newest applied delta was created: \fIyyyy\fR/\fImm\fR/\fIdd\fR
T}
_
\fB%\&F%\fR\fBSCCS\fR \fBs.\fRfile name
_
\fB%\&G%\fRT{
Date newest applied delta was created: \fImm\fR/\fIdd\fR/\fIyy\fR
T}
_
\fB%\&g%\fRT{
Date newest applied delta was created: \fImm\fR/\fIdd\fR/\fIyyyy\fR
T}
_
\fB%\&H%\fRCurrent date: \fImm\fR\fB/\fR\fIdd\fR\fB/\fR\fIyy\fR
_
\fB%\&h%\fRCurrent date: \fImm\fR\fB/\fR\fIdd\fR\fB/\fR\fIyyyy\fR
_
\fB%\&I%\fR\fBSID\fR of the retrieved version: \fB%\&R%.%\&L%.%\&B%.%\&S%\fR
_
\fB%\&L%\fR\fBSID\fR level component
_
\fB%\&M%\fRT{
Module name: either the value of the \fBm\fR flag in the \fBs.\fRfile (see 
\fBsccs-admin\fR(1)), or the name of the \fBs.\fRfile less the prefix
T}
_
T{
\fB%\&P%\fR
T}Fully qualified \fBs.\fRfile name
_
\fB%\&Q%\fRValue of the \fBq\fR flag in the \fBs.\fRfile
_
\fB%\&R%\fR\fBSID\fR Release component
_
\fB%\&S%\fR\fBSID\fR Sequence component
_
\fB%\&T%\fRCurrent time: \fIhh\fR\fB:\fR\fImm\fR\fB:\fR\fIss\fR
_
\fB%\&U%\fRT{
Time the newest applied delta was created: \fIhh\fR\fB:\fR\fImm\fR\fB:\fR\fIss\fR
T}
_
\fB%\&W%\fRT{
Shorthand notation for an \fBID\fR line with data for \fBwhat\fR: \fB%\&Z%%\&M%  %\&I%\fR or get -w argument
T}
_
\fB%\&Y%\fRT{
Module type: value of the \fBt\fR flag in the \fBs.\fRfile
T}
_
\fB%\&Z%\fRT{
4-character string: `\fB@(#)\fR', recognized by \fBwhat\fR
T}
.TE
.LP
A line with a string in the form \fB%\&sccs.include.\fIfilename\fB\&%\fR is replaced by
the content of the file
.IR filename .
The file is searched for in the path list found in the environment variable
.BR SCCS_INCLUDEPATH .
.LP
The keywords
.BR %\&d\&% ", " %\&e\&% ", " %\&g\&%
and
.B %\&h\&%
are only expanded if either the 
.B `x'
flag has been set by the 
.BR admin (1)
command or if the expansion for a specific keyword has been enabled
via the
.B `y'
flag.

.SS ID String

.LP
The table below explains how the  SCCS identification string is  determined for retrieving and creating deltas.
.sp

.LP

.sp
.TS
tab() box;
cbw(.92i) sw(.92i) sw(1.38i) sw(.92i) sw(1.38i)
cw(.92i) |cw(.92i) |cw(1.38i) |cw(.92i) |cw(1.38i)
cw(.92i) |cw(.92i) |cw(1.38i) |cw(.92i) |cw(1.38i)
lw(.92i) |lw(.92i) |lw(1.38i) |lw(.92i) |lw(1.38i)
.
Determination of SCCS Identification String
_
SID \fB(1)\fP\fB-b\fR OptionOtherSIDSID of Delta
SpecifiedUsed \fB(2)\fPConditionsRetrievedto be Created
_
none \fB(3)\fPnoR defaults to mRmR.mLmR.(mL+1)
none \fB(3)\fPyesR defaults to mRmR.mLmR.mL.(mB+1).1
RnoR > mRmR.mLR.1 \fB(4)\fP
RnoR = mRmR.mLmR.(mL+1)
RyesR > mRmR.mLmR.mL.(mB+1).1
RyesR = mRmR.mLmR.mL.(mB+1).1
R\(miT{
R < mR and R does \fInot\fR exist
T}hR.mL \fB(5)\fPhR.mL.(mB+1).1
R\(miT{
Trunk succ. \fB(6)\fP in release > R and R exists
T}R.mLR.mL.(mB+1).1
R.LnoNo trunk succ.R.LR.(L+1)
R.LyesNo trunk succ.R.LR.L.(mB+1).1
R.L\(miT{
Trunk succ. in release \(>= R
T}R.LR.L.(mB+1).1
R.L.BnoNo branch succ.R.L.B.mSR.L.B.(mS+1)
R.L.ByesNo branch succ.R.L.B.mSR.L.(mB+1).1
R.L.B.SnoNo branch succ.R.L.B.SR.L.B.(S+1)
R.L.B.SyesNo branch succ. R.L.B.SR.L.(mB+1).1
R.L.B.S\(miBranch succ.R.L.B.SR.L.(mB+1).1
.TE

.sp
.ne 2
.mk
.na
\fB(1)\fR
.ad
.RS 5n
.rt  
`R', `L', `B', and `S' are the `release', `level', `branch', and `sequence' components of the \fBSID\fR, respectively; `m' means `maximum'. Thus, for example, `R.mL' means `the maximum level number within release R'; `R.L.(mB+1).1' means `the first sequence number on the \fInew\fR branch (that is, maximum branch number plus one) of level L within release R'. \fINote:\fR If the \fBSID\fR specified is of the form `R.L', `R.L.B', or `R.L.B.S', each of the specified components \fImust\fR exist.
.sp

.RE

.sp
.ne 2
.mk
.na
\fB(2)\fR
.ad
.RS 5n
.rt  
The \fB-b\fR option is effective only if the \fBb\fR flag is present in the file. An entry of `\fB\(mi\fR' means `irrelevant'.
.sp

.RE

.sp
.ne 2
.mk
.na
\fB(3)\fR
.ad
.RS 5n
.rt  
This case applies if the \fBd\fR (default \fBSID\fR) flag is \fInot\fR present in the file.  If the \fBd\fR flag \fIis\fR present in the file, the \fBSID\fR obtained from the \fBd\fR flag is interpreted as if it had been specified on the command line. Thus, one of the other cases in this table applies.
.sp

.RE

.sp
.ne 2
.mk
.na
\fB(4)\fR
.ad
.RS 5n
.rt  
Forces creation of the \fIfirst\fR delta in a \fInew\fR release.
.sp

.RE

.sp
.ne 2
.mk
.na
\fB(5)\fR
.ad
.RS 5n
.rt  
`hR' is the highest \fIexisting\fR release that is lower than the specified, \fInonexistent\fR, release R.
.sp

.RE

.sp
.ne 2
.mk
.na
\fB(6)\fR
.ad
.RS 5n
.rt  
Successor.
.sp

.RE

.SH ENVIRONMENT VARIABLES
.sp
.LP
See
.BR environ (5)
for descriptions of the following environment variables that affect the
execution of
.BR get (1):
.BR LANG ,
.BR LC_ALL ,
.BR LC_COLLATE ,
.BR LC_CTYPE ,
.BR LC_MESSAGES ,
and
.BR NLSPATH .
.br
.ne 4
.TP
.B SCCS_INCLUDEPATH
A colon separated list of directories where to look for include
files for a \fB%\&sccs.include.\fIfilename\fB\&%\fR replacement.
.br
.ne 4
.TP
.B SCCS_NO_HELP
If set,
.BR get (1)
will not automatically call
.BR help (1)
with the SCCS error code in order to print a more helpful
error message. Scripts that depend on the exact error messages
of SCCS commands should set the environment variable
.B SCCS_NO_HELP
and set
.BR LC_ALL=C .

.SH EXIT STATUS
.sp
.LP
The following exit values are returned:
.sp
.ne 2
.TP 5
.B 0
Successful completion.
.sp
.ne 2
.TP
.B 1
An error occurred.

.SH FILES

.sp
.ne 2
.TP 12
.B ``g-file''
version retrieved by \fBget\fR

.sp
.ne 2
.TP
.BI l. file
file containing extracted delta table info

.sp
.ne 2
.TP
.BI p. file
permissions (lock) file for checked-out versions.
The
.BR p. file
has an arbitrary number of lines, each is related to a
.B get \-e
call. Each line has the following structure:
.sp
.RS +15
.I old-sid
.I new-sid
.I username
.I date
.IR time " \e
.br
[
.BI -i i-arg
][
.BI -x x-arg
][
.BI -z z-arg
]
.RE
.RS +12
.LP
The
.I old-sid
is the SID that was checked out with
.BR "get \-e" ,
the
.I new-sid
is the SID that will be used for the new version when
.B delta
is called. The
.I username
is the user-name corresponding to the real user ID at the time
.B get \-e
was called. The
.I date
and
.I time
fields are in the same format as used in the delta table of the
.BI s. file
as described in
.BR sccsfile (4)
for
.B SCCS
v4.
In order to grant POSIX compatibility, a two digit year is used
between 1969 and 2068. For years outside that range, a four digit
year is used.
The following fields are only present when one or more of the
.B \-i
.B \-x
or
.B \-z
options have been specified on the command line, they refer to the
list of included and excluded deltas or to the CMR list from the
NSE enhancements.
.RE

.sp
.ne 3
.TP
.BI q. file
temporary copy of the 
.BR p. file; 
renamed to the 
.BR p. file 
after completion 

.sp
.ne 2
.TP
.BI s. file
.B SCCS
history file, see
.BR sccsfile (4).

.sp
.ne 3
.TP
.BI z. file
temporary lock file contains the binary process id in host byte order 
followed by the host name

.SH ATTRIBUTES

.LP
See 
\fBattributes\fR(5) for descriptions of the following attributes:
.sp

.SS /usr/ccs/bin/get

.LP

.sp
.TS
tab() box;
cw(2.75i) |cw(2.75i) 
lw(2.75i) |lw(2.75i) 
.
ATTRIBUTE TYPEATTRIBUTE VALUE
_
AvailabilitySUNWsprot
.TE

.SS /usr/xpg4/bin/get

.LP

.sp
.TS
tab() box;
cw(2.75i) |cw(2.75i) 
lw(2.75i) |lw(2.75i) 
.
ATTRIBUTE TYPEATTRIBUTE VALUE
_
AvailabilitySUNWxcu4t
_
Interface StabilityStandard
.TE

.SH SEE ALSO
.LP
.BR sccs (1),
.BR sccs-admin (1),
.BR sccs-cdc (1),
.BR sccs-comb (1),
.BR sccs-delta (1),
.BR sccs-help (1),
.BR sccs-prs (1),
.BR sccs-prt (1),
.BR sccs-rmdel (1),
.BR sccs-sact (1),
.BR sccs-sccsdiff (1),
.BR sccs-unget (1),
.BR sccs-val (1),
.BR sccscvt (1),
.BR sccslog (1),
.BR bdiff (1), 
.BR diff (1), 
.BR what (1),
.BR changeset (4),
.BR sccsfile (4),
.BR attributes (5),
.BR environ (5),
.BR standards (5).

.SH DIAGNOSTICS

.LP
Use the SCCS \fBhelp\fR command for explanations (see 
\fBsccs-help\fR(1)).
.sp

.SH BUGS

.LP
If the effective user has write permission (either explicitly or implicitly) in the directory containing the SCCS files, but the real user does not, only one file may be named when using \fB-e\fR.

.SH AUTHORS
The
.B SCCS
suite was origininally written by Marc J. Rochkind at Bell Labs in 1972.
Release 4.0 of
.BR SCCS ,
introducing new versions of the programs
.BR admin (1),
.BR get (1),
.BR prt (1),
and
.BR delta (1)
was published on February 18, 1977; it introduced the new text based
.B SCCS\ v4
history file format (previous
.B SCCS
releases used a binary history file format).
The
.B SCCS
suite
was later maintained by various people at AT&T and Sun Microsystems.
Since 2006, the
.B SCCS
suite is maintained by J\*org Schilling.
