'\" te
.\" @(#)sccs-sact.1	1.27 20/08/05 Copyright 2007-2020 J. Schilling
.\" Copyright (c) 1999, Sun Microsystems, Inc.
.\" CDDL HEADER START
.\"
.\" The contents of this file are subject to the terms of the
.\" Common Development and Distribution License ("CDDL"), version 1.0.
.\" You may use this file only in accordance with the terms of version
.\" 1.0 of the CDDL.
.\"
.\" A full copy of the text of the CDDL should have accompanied this
.\" source.  A copy of the CDDL is also available via the Internet at
.\" http://www.opensource.org/licenses/cddl1.txt
.\"
.\" When distributing Covered Code, include this CDDL HEADER in each
.\" file and include the License file at usr/src/OPENSOLARIS.LICENSE.
.\" If applicable, add the following below this CDDL HEADER, with the
.\" fields enclosed by brackets "[]" replaced with your own identifying
.\" information: Portions Copyright [yyyy] [name of copyright owner]
.\"
.\" CDDL HEADER END
.if t .ds a \v'-0.55m'\h'0.00n'\z.\h'0.40n'\z.\v'0.55m'\h'-0.40n'a
.if t .ds o \v'-0.55m'\h'0.00n'\z.\h'0.45n'\z.\v'0.55m'\h'-0.45n'o
.if t .ds u \v'-0.55m'\h'0.00n'\z.\h'0.40n'\z.\v'0.55m'\h'-0.40n'u
.if t .ds A \v'-0.77m'\h'0.25n'\z.\h'0.45n'\z.\v'0.77m'\h'-0.70n'A
.if t .ds O \v'-0.77m'\h'0.25n'\z.\h'0.45n'\z.\v'0.77m'\h'-0.70n'O
.if t .ds U \v'-0.77m'\h'0.30n'\z.\h'0.45n'\z.\v'0.77m'\h'-0.75n'U
.if t .ds s \\(*b
.if t .ds S SS
.if n .ds a ae
.if n .ds o oe
.if n .ds u ue
.if n .ds s sz
.TH sccs-sact 1 "2020/08/05" "SunOS 5.11" "User Commands"
.SH NAME
sccs-sact, sact \- show editing activity status of an SCCS file
.SH SYNOPSIS
.LP
.nf
.B "/usr/ccs/bin/sact \c
.RB [ \-s "] \c
.br
.RB "    [" \-X\c
.IR extended-options "] \c
.RB "[" -N\c
.IR bulk-spec "] \c
.IR s.filename...
.fi

.SH DESCRIPTION
.LP
The
.B sact
utility informs the user of any
.B SCCS
files that are checked out for editing.
.LP
The output for each named file consists of five fields separated by
.B SPACE
characters.
.RS +4
.TP
.ie t \(bu
.el o
.B SID
of a delta that currently exists in the
.B SCCS
file, to which changes will be made to make the new delta
.RE
.RS +4
.TP
.ie t \(bu
.el o
.B SID
for the new delta to be created
.RE
.RS +4
.TP
.ie t \(bu
.el o
Username of the person who has the file checked out for editing.
.RE
.RS +4
.TP
.ie t \(bu
.el o
Date that the version was checked out.
.RE
.RS +4
.TP
.ie t \(bu
.el o
Time that the version was checked out.
.RE
.LP
If a directory name is used in place of the
.I s.filename
argument, the
.B sact
command applies to all
.BR s. files
in that directory. Unreadable
.BR s. files
produce an error; processing continues with the next file (if any). The use of
.RB ` \(mi '
as the
.I s.filename
argument indicates that the names of files are to be read from the
standard input, one
.BR s. file
per line.
.SH OPTIONS

.br
.ne 2
.TP
.B \-s
Suppresses the error message when a file is not currently edited.

.sp
.ne 3
.TP
.BI -N bulk-spec
Processes a bulk of SCCS history files.
This option allows one to do an efficient mass processing of SCCS history files.
.sp
The
.I bulk-spec
parameter is composed from an optional list of
.B flag
parameters followed by an optional
.B path
specifier.
.sp
.ne 4
The following flag types are supported:
.RS
.TP 10
.B none
.LP
.ne 4
The following path specifier types are supported:
.TP 10
.B \-N
The file name parameters to the
.B sccslog
command are not
.I s.filename
files but the names of the g-files.
The
.I s.filename
names are automatically derived from the g-file names by prepending
.B s.
to the last path name component.
Both,
.I s.filename
and the g-file are in the same directory.
.TP
.B \-Ns.
The file name parameters to the
.B sccslog
command are
.I s.filename
files.
The the g-files names are automatically derived by removing
.B s.
from the beginning of last path name component of the
.IR s.filename.
Both,
.I s.filename
and the g-file are in the same directory.
.TP
.BI \-N dir
The file name parameters to the
.B sccslog
command are not
.I s.filename
files but the names of the g-files.
The
.I s.filename
names are put into directory
.IR dir ,
the names are automatically derived from the g-file names by prepending
.IB dir /s.
to the last path name component.
.TP
.BI \-N dir /s.
The file name parameters to the
.B sccslog
command are
.I s.filename
files in directory
.IR dir .
The the g-files names are automatically derived by removing
.IB dir /s.
from the beginning of last path name component of the
.IR s.filename.
.PP
A typical value for
.I dir
is
.BR SCCS .
.PP
In order to overcome the limited number of
.BR exec (2)
arguments, it is recommended to use
.RB ` \(mi \&'
as the file name parameter for
.BR sccslog (1)
and to send a list of path names to
.BR stdin .
.RE

.br
.ne 3
.TP
.BI \-X extended\-options
Specify extended options. The argument
.I extended\-options
may be a comma separated list of extended option names.
.sp
The following extended options are supported, they may be abbreviated as long
ad the abbreviation is still unique. Options with parameter may not be
abbreviated.
.sp
.RS
.TP
.B 0
When reading filenames from
.BR stdin ,
triggered by a file name argument
.RB ` - ',
the filename separator is a
.B null byte
instead of a
.BR newline .
This allows one to use long lists with arbitrary filenames.
.TP
.B help
Print a short online help for available options.
.PP
The
.B \-X
option is a
.B \s-1SCHILY\s+1
extension that does not exist in historic
.B sccs
implementations.
.RE

.br
.ne 2
.TP
.PD 0
.B \-V
.TP
.B \-version
.TP
.B \-\-version
.PD
Prints the
.B sact
version number string and exists.
.sp
This option is a
.B \s-1SCHILY\s+1
extension that does not exist in historic
.B sccs
implementations.

.SH ENVIRONMENT VARIABLES
.sp
.LP
See
.BR environ (5)
for descriptions of the following environment variables that affect the
execution of
.BR sact (1):
.BR LANG ,
.BR LC_ALL ,
.BR LC_COLLATE ,
.BR LC_CTYPE ,
.BR LC_MESSAGES ,
and
.BR NLSPATH .

.br
.ne 4
.TP
.B SCCS_NO_HELP
If set,
.BR sact (1)
will not automatically call
.BR help (1)
with the SCCS error code in order to print a more helpful
error message. Scripts that depend on the exact error messages
of SCCS commands should set the environment variable
.B SCCS_NO_HELP
and set
.BR LC_ALL=C .

.SH EXIT STATUS
.sp
.LP
The following exit values are returned:
.sp
.ne 2
.TP 5
.B 0
Successful completion.
.sp
.ne 2
.TP
.B 1
An error occurred.

.SH FILES

.br
.ne 3
.TP 12
.BI p. file
permissions (lock) file for checked-out versions.
See
.BR sccs-get (1)
for a description of the layout of the
.BR p. file.

.br
.ne 3
.TP
.BI s. file
.B SCCS
history file, see
.BR sccsfile (4).

.br
.ne 3
.TP
.B dump.core
If the file
.B dump.core
exists in the current directory and a fatal signal is received, a coredump
is initiated via
.BR abort (3).

.SH ATTRIBUTES
.LP
See 
.BR attributes (5)
for descriptions of the following attributes:
.LP
.TS
tab() box;
cw(2.75i) |cw(2.75i) 
lw(2.75i) |lw(2.75i) 
.
ATTRIBUTE TYPEATTRIBUTE VALUE
_
AvailabilitySUNWsprot
_
Interface StabilityStandard
.TE

.SH SEE ALSO
.nh
.LP
.BR sccs (1),
.BR sccs\-add (1),
.BR sccs\-admin (1),
.BR sccs\-branch (1),
.BR sccs\-cdc (1),
.BR sccs\-check (1),
.BR sccs\-clean (1),
.BR sccs\-comb (1),
.BR sccs\-commit (1),
.BR sccs\-create (1),
.BR sccs\-cvt (1),
.BR sccs\-deledit (1),
.BR sccs\-delget (1),
.BR sccs\-delta (1),
.BR sccs\-diffs (1),
.BR sccs\-edit (1),
.BR sccs\-editor (1),
.BR sccs\-enter (1),
.BR sccs\-fix (1),
.BR sccs\-get (1),
.BR sccs\-help (1),
.BR sccs\-histfile (1),
.BR sccs\-info (1),
.BR sccs\-init (1),
.BR sccs\-istext (1),
.BR sccs\-ldiffs (1),
.BR sccs\-log (1),
.BR sccs\-print (1),
.BR sccs\-prs (1),
.BR sccs\-prt (1),
.BR sccs\-rcs2sccs (1),
.BR sccs\-remove (1),
.BR sccs\-rename (1),
.BR sccs\-rmdel (1),
.BR sccs\-root (1),
.BR sccs\-sccsdiff (1),
.BR sccs\-status (1),
.BR sccs\-tell (1),
.BR sccs\-unedit (1),
.BR sccs\-unget (1),
.BR sccs\-val (1),
.BR bdiff (1), 
.BR diff (1), 
.BR what (1),
.BR sccschangeset (4),
.BR sccsfile (4),
.BR attributes (5),
.BR environ (5),
.BR standards (5).
.hy 14

.SH DIAGNOSTICS
.LP
Use the SCCS
.B help
command for explanations (see 
.BR sccs-help (1)).

.SH BUGS
.PP
None currently known.
.PP
Mail bugs and suggestions to
.B schilytools@mlists.in-berlin.de
or open a ticket at
.BR https://codeberg.org/schilytools/schilytools/issues .
.PP
The mailing list archive may be found at:
.PP
.nf
.BR https://mlists.in-berlin.de/mailman/listinfo/schilytools-mlists.in-berlin.de .
.fi

.SH AUTHORS
The
.B SCCS
suite was originally written by Marc J. Rochkind at Bell Labs in 1972.
Release 4.0 of
.BR SCCS ,
introducing new versions of the programs
.BR admin (1),
.BR get (1),
.BR prt (1),
and
.BR delta (1)
was published on February 18, 1977; it introduced the new text based
.B SCCS\ v4
history file format (previous
.B SCCS
releases used a binary history file format).
The
.B SCCS
suite
was later maintained by various people at AT&T and Sun Microsystems.
Since 2006, the
.B SCCS
suite has been maintained by J\*org Schilling and the schilytools
project authors.

.SH "SOURCE DOWNLOAD"
The source code for
.B sccs
is included in the
.B schilytools
project and may be retrieved from the
.B schilytools
project at Codeberg at
.LP
.BR https://codeberg.org/schilytools/schilytools .
.LP
The download directory is
.LP
.BR https://codeberg.org/schilytools/schilytools/releases .
