'\" te
.\" @(#)sccs-sccsdiff.1	1.9 14/09/15 Copyright 2007-2014 J. Schilling
.\" CDDL HEADER START
.\"
.\" The contents of this file are subject to the terms of the
.\" Common Development and Distribution License ("CDDL"), version 1.0.
.\" You may only use this file in accordance with the terms of version
.\" 1.0 of the CDDL.
.\"
.\" A full copy of the text of the CDDL should have accompanied this
.\" source.  A copy of the CDDL is also available via the Internet at
.\" http://www.opensource.org/licenses/cddl1.txt
.\"
.\" When distributing Covered Code, include this CDDL HEADER in each
.\" file and include the License file at usr/src/OPENSOLARIS.LICENSE.
.\" If applicable, add the following below this CDDL HEADER, with the
.\" fields enclosed by brackets "[]" replaced with your own identifying
.\" information: Portions Copyright [yyyy] [name of copyright owner]
.\"
.\" CDDL HEADER END
.\" Copyright (c) 2001, Sun Microsystems, Inc.
.if t .ds a \v'-0.55m'\h'0.00n'\z.\h'0.40n'\z.\v'0.55m'\h'-0.40n'a
.if t .ds o \v'-0.55m'\h'0.00n'\z.\h'0.45n'\z.\v'0.55m'\h'-0.45n'o
.if t .ds u \v'-0.55m'\h'0.00n'\z.\h'0.40n'\z.\v'0.55m'\h'-0.40n'u
.if t .ds A \v'-0.77m'\h'0.25n'\z.\h'0.45n'\z.\v'0.77m'\h'-0.70n'A
.if t .ds O \v'-0.77m'\h'0.25n'\z.\h'0.45n'\z.\v'0.77m'\h'-0.70n'O
.if t .ds U \v'-0.77m'\h'0.30n'\z.\h'0.45n'\z.\v'0.77m'\h'-0.75n'U
.if t .ds s \\(*b
.if t .ds S SS
.if n .ds a ae
.if n .ds o oe
.if n .ds u ue
.if n .ds s sz
.TH sccs-sccsdiff 1 "2014/09/15" "SunOS 5.11" "User Commands"
.SH NAME
sccs-sccsdiff, sccsdiff \- compare two versions of an SCCS file
.SH SYNOPSIS
.LP
.nf
.B "/usr/ccs/bin/sccsdiff \c
.RB [ -p "] \c
.BI -r "sid \c
.BI -r "sid \c
.RI [ diff-options "] \c
.I s.filename
.fi

.SH DESCRIPTION

.LP
\fBsccsdiff\fR compares two versions of an \fBSCCS\fR file and displays the differences between the two versions. Any number of \fBSCCS\fR files may be specified. The options specified apply to all named \fBs.\fRfiles.
.sp

.SH OPTIONS

.LP
The following options are supported:
.sp

.sp
.ne 2
.TP 13
\fB\fB-p\fR\fR
Pipe output for each file through 
\fBpr\fR(1).

.sp
.ne 2
.TP
\fB\fB-r\fR\fIsid\fR\fR
Specify a version corresponding to the indicated \fBSCCS\fR delta \fBID\fR (SID) for comparison.  Versions are passed to 
\fBdiff\fR(1) in the order given.

.sp
.ne 2
.TP
\fB\fIdiff-options\fR\fR
Pass options to 
\fBdiff\fR(1), including: \fB-b\fR, \fB-c\fR, \fB-e\fR, \fB-f\fR, \fB-h\fR, \fB-u\fR, \fB-C\fR \fInumber\fR, \fB-U\fR \fInumber\fR, and \fB-D\fR \fIstring\fR.

.ne 3
.TP
.B \-V
Prints the
.B sccsdiff
version number string and exists.

.SH ENVIRONMENT VARIABLES
.sp
.LP
See
.BR environ (5)
for descriptions of the following environment variables that affect the
execution of
.BR sccsdiff (1):
.BR LANG ,
.BR LC_ALL ,
.BR LC_COLLATE ,
.BR LC_CTYPE ,
.BR LC_MESSAGES ,
and
.BR NLSPATH .
.br
.ne 4
.TP
.B SCCS_NO_HELP
If set,
.BR sccsdiff (1)
will not automatically call
.BR help (1)
with the SCCS error code in order to print a more helpful
error message. Scripts that depend on the exact error messages
of SCCS commands should set the environment variable
.B SCCS_NO_HELP
and set
.BR LC_ALL=C .

.SH FILES

.sp
.ne 2
.mk
.na
\fB\fB/tmp/get?????\fR\fR
.ad
.RS 15n
.rt  
temporary files
.sp

.RE

.SH ATTRIBUTES

.LP
See 
\fBattributes\fR(5) for descriptions of the following attributes:
.sp

.LP

.sp
.TS
tab() box;
cw(2.75i) |cw(2.75i) 
lw(2.75i) |lw(2.75i) 
.
ATTRIBUTE TYPEATTRIBUTE VALUE
_
AvailabilitySUNWsprot
.TE

.SH SEE ALSO
.LP
.BR sccs (1),
.BR sccs-admin (1),
.BR sccs-cdc (1),
.BR sccs-comb (1),
.BR sccs-delta (1),
.BR sccs-get (1),
.BR sccs-help (1),
.BR sccs-prs (1),
.BR sccs-prt (1),
.BR sccs-rmdel (1),
.BR sccs-sact (1),
.BR sccs-unget (1),
.BR sccs-val (1),
.BR sccscvt (1),
.BR sccslog (1),
.BR bdiff (1), 
.BR diff (1), 
.BR what (1),
.BR changeset (4),
.BR sccsfile (4),
.BR attributes (5),
.BR environ (5),
.BR standards (5).

.SH DIAGNOSTICS

.sp
.ne 2
.mk
.na
\fB\fIfilename\fR\fB: No differences\fR\fR
.ad
.RS 26n
.rt  
If the two versions are the same.
.sp

.RE

.LP
Use the SCCS
.B help
command for explanations of other messages. See 
.BR sccs-help (1).

.SH AUTHORS
The
.B SCCS
suite was origininally written by Marc J. Rochkind at Bell Labs in 1972.
Release 4.0 of
.BR SCCS ,
introducing new versions of the programs
.BR admin (1),
.BR get (1),
.BR prt (1),
and
.BR delta (1)
was published on February 18, 1977; it introduced the new text based
.B SCCS\ v4
history file format (previous
.B SCCS
releases used a binary history file format).
The
.B SCCS
suite
was later maintained by various people at AT&T and Sun Microsystems.
Since 2006, the
.B SCCS
suite is maintained by J\*org Schilling.
