'\" te
.\" CDDL HEADER START
.\"
.\" The contents of this file are subject to the terms of the
.\" Common Development and Distribution License (the "License").  
.\" You may not use this file except in compliance with the License.
.\"
.\" You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
.\" or http://www.opensolaris.org/os/licensing.
.\" See the License for the specific language governing permissions
.\" and limitations under the License.
.\"
.\" When distributing Covered Code, include this CDDL HEADER in each
.\" file and include the License file at usr/src/OPENSOLARIS.LICENSE.
.\" If applicable, add the following below this CDDL HEADER, with the
.\" fields enclosed by brackets "[]" replaced with your own identifying
.\" information: Portions Copyright [yyyy] [name of copyright owner]
.\"
.\" CDDL HEADER END
.\" Copyright (c) 2001, Sun Microsystems, Inc.
.\" Copyright 2007-2011 J. Schilling
.TH sccs-sccsdiff 1 "2011/08/24" "SunOS 5.11" "User Commands"
.SH NAME
sccs-sccsdiff, sccsdiff \- compare two versions of an SCCS file
.SH SYNOPSIS
.LP
.nf
\fB/usr/ccs/bin/sccsdiff\fR [\fB-p\fR] \fB-r\fR\fIsid\fR \fB-r\fR\fIsid\fR [\fIdiff-options\fR] \fIs.filename\fR
.fi

.SH DESCRIPTION

.LP
\fBsccsdiff\fR compares two versions of an \fBSCCS\fR file and displays the differences between the two versions. Any number of \fBSCCS\fR files may be specified. The options specified apply to all named \fBs.\fRfiles.
.sp

.SH OPTIONS

.LP
The following options are supported:
.sp

.sp
.ne 2
.TP 13
\fB\fB-p\fR\fR
Pipe output for each file through 
\fBpr\fR(1).

.sp
.ne 2
.TP
\fB\fB-r\fR\fIsid\fR\fR
Specify a version corresponding to the indicated \fBSCCS\fR delta \fBID\fR (SID) for comparison.  Versions are passed to 
\fBdiff\fR(1) in the order given.

.sp
.ne 2
.TP
\fB\fIdiff-options\fR\fR
Pass options to 
\fBdiff\fR(1), including: \fB-b\fR, \fB-c\fR, \fB-e\fR, \fB-f\fR, \fB-h\fR, \fB-u\fR, \fB-C\fR \fInumber\fR, \fB-U\fR \fInumber\fR, and \fB-D\fR \fIstring\fR.

.ne 3
.TP
.B \-V
Prints the
.B sccsdiff
version number string and exists.

.SH FILES

.sp
.ne 2
.mk
.na
\fB\fB/tmp/get?????\fR\fR
.ad
.RS 15n
.rt  
temporary files
.sp

.RE

.SH ATTRIBUTES

.LP
See 
\fBattributes\fR(5) for descriptions of the following attributes:
.sp

.LP

.sp
.TS
tab() box;
cw(2.75i) |cw(2.75i) 
lw(2.75i) |lw(2.75i) 
.
ATTRIBUTE TYPEATTRIBUTE VALUE
_
AvailabilitySUNWsprot
.TE

.SH SEE ALSO
.LP
.BR sccs (1),
.BR sccs-admin (1),
.BR sccs-cdc (1),
.BR sccs-comb (1)
.BR sccs-delta (1),
.BR sccs-get (1),
.BR sccs-help (1),
.BR sccs-prs (1),
.BR sccs-prt (1),
.BR sccs-rmdel (1),
.BR sccs-sact (1),
.BR sccs-unget (1),
.BR sccs-val (1),
.BR sccscvt (1),
.BR sccslog (1),
.BR bdiff (1), 
.BR diff (1), 
.BR what (1),
.BR sccsfile (4),
.BR attributes (5),
.BR environ (5),
.BR standards (5).

.SH DIAGNOSTICS

.sp
.ne 2
.mk
.na
\fB\fIfilename\fR\fB: No differences\fR\fR
.ad
.RS 26n
.rt  
If the two versions are the same.
.sp

.RE

.LP
Use the \fBSCCS\fR \fBhelp\fR command for explanations of other messages. See 
\fBsccs-help\fR(1).
.sp

