'\" te
.\" CDDL HEADER START
.\"
.\" The contents of this file are subject to the terms of the
.\" Common Development and Distribution License (the "License").  
.\" You may not use this file except in compliance with the License.
.\"
.\" You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
.\" or http://www.opensolaris.org/os/licensing.
.\" See the License for the specific language governing permissions
.\" and limitations under the License.
.\"
.\" When distributing Covered Code, include this CDDL HEADER in each
.\" file and include the License file at usr/src/OPENSOLARIS.LICENSE.
.\" If applicable, add the following below this CDDL HEADER, with the
.\" fields enclosed by brackets "[]" replaced with your own identifying
.\" information: Portions Copyright [yyyy] [name of copyright owner]
.\"
.\" CDDL HEADER END
.\" Copyright (c) 2002, Sun Microsystems, Inc. All Rights Reserved
.\" Copyright 2007-2011 J. Schilling
.TH sccs-val 1 "2011/05/18" "SunOS 5.11" "User Commands"
.SH NAME
sccs-val, val \- validate an SCCS file
.SH SYNOPSIS
.LP
.nf
\fB/usr/ccs/bin/val\fR \fB-\fR
.fi
.LP
.nf
\fB/usr/ccs/bin/val\fR [\fB-T\fR] [\fB-s\fR] [\fB-m\fR \fIname\fR] [\fB-r\fR\fIsid\fR] [\fB-y\fR \fItype\fR] \fIs.filename\fR...
.fi

.SH DESCRIPTION

.LP
The \fBval\fR utility determines if the specified \fBs.\fRfiles meet the characteristics specified by the indicated arguments. \fBval\fR can process up to 50 files on a single command line.
.sp

.LP
\fBval\fR has a special argument, `\fB\(mi\fR', which reads the standard input until the end-of-file condition is detected. Each line read is independently processed as if it were a command line argument list.
.sp

.LP
If a directory name is used in place of the \fIs.filename\fR command line argument,
the
.B val
command applies to all \fBs.\fRfiles in that directory. Unreadable \fBs.\fRfiles produce an error; processing continues with the next file (if any).
.sp

.LP
\fBval\fR generates diagnostic messages on the standard output for each command line and file processed and also returns a single 8\(mibit code upon exit as described below.
.sp

.LP
The 8-bit code returned by \fBval\fR is a disjunction of the possible errors, that is, it can be interpreted as a bit string where (moving from left to right) the bits set are interpreted as follows:
.sp

.LP
.in +2
.nf
bit 0 (value 128) = missing file argument
bit 1 (value  64) = unknown or duplicate option
bit 2 (value  32) = corrupted s.file
bit 3 (value  16) = can not open file or file not in s.file format
bit 4 (value   8) = the SCCS delta ID (SID) is invalid or ambiguous
bit 5 (value   4) = the SID does not exist
bit 6 (value   2) = mismatch between %\&Y% and -y argument
bit 7 (value   1) = mismatch between %\&M% and -m argument
.fi
.in -2
.sp

.LP
\fBval\fR can process two or more files on a given command line, and in turn can process multiple command lines (when reading the standard input). In these cases, an aggregate code is returned which is the logical \fBOR\fR of the codes generated for each command line and file processed.
.sp

.SH OPTIONS

.LP
The following options are supported:
.sp

.sp
.ne 2
.TP 9
.B \-s
Silent.  Suppresses the normal error or warning messages.

.sp
.ne 2
.TP
.BI \-m " name
Compares
.I name
with the 
.B "%\&M%"
ID keyword in the \fBs.\fRfile.

.sp
.ne 2
.TP
.BI \-r sid
Checks to see if the indicated
.B SID
is ambiguous, invalid, or absent from the \fBs.\fRfile.

.sp
.ne 2
.TP
.BI \-y " type
Compares
.I type
with the 
.B "%\&Y%"
ID keyword.

.sp
.ne 2
.TP
.B \-T
Trace. Print extra debug messages.
This disables the silent mode.
When in debug mode, extra tests are enabled for:
.RS
.TP 12
.B statistics
The statistics line in the SCCS history file is written but not used.
This is why this test is only enabled in debug mode and why a defective
statistics line does not affect the exit code.
.TP
.B time stamps
The time stamps in the SCCS history file are only used when a cut-off time
was specified. This test checks for monotonic growing time stamps. A warning
caused by time stamps that go backwards does not affect the exit code.
.LP
For a complete consistency check, it is recommended to run
.B val
in debug mode to check for all problems.
.RE

.ne 3
.TP
.B \-V
Prints the
.B val
version number string and exists.

.SH ENVIRONMENT VARIABLES

.LP
See 
\fBenviron\fR(5) for descriptions of the following environment variables that affect the execution of \fBval\fR: LANG, LC_ALL, LC_CTYPE, LC_MESSAGES, and NLSPATH.
.sp

.SH ATTRIBUTES

.LP
See 
\fBattributes\fR(5) for descriptions of the following attributes:
.sp

.LP

.sp
.TS
tab() box;
cw(2.75i) |cw(2.75i) 
lw(2.75i) |lw(2.75i) 
.
ATTRIBUTE TYPEATTRIBUTE VALUE
_
AvailabilitySUNWsprot
_
Interface StabilityStandard
.TE

.SH SEE ALSO

.LP

\fBsccs\fR(1), 
\fBsccs-admin\fR(1), 
\fBsccs-delta\fR(1), 
\fBsccs-get\fR(1), 
\fBsccs-help\fR(1), 
\fBwhat\fR(1), 
\fBsccsfile\fR(4), 
\fBattributes\fR(5), 
\fBenviron\fR(5), 
\fBstandards\fR(5)
.sp

.SH DIAGNOSTICS

.LP
Use the SCCS \fBhelp\fR command for explanations (see 
\fBsccs-help\fR(1)).
.sp

