'\" te
.\" CDDL HEADER START
.\"
.\" The contents of this file are subject to the terms of the
.\" Common Development and Distribution License ("CDDL"), version 1.0.
.\" You may only use this file in accordance with the terms of version
.\" 1.0 of the CDDL.
.\"
.\" A full copy of the text of the CDDL should have accompanied this
.\" source.  A copy of the CDDL is also available via the Internet at
.\" http://www.opensource.org/licenses/cddl1.txt
.\"
.\" When distributing Covered Code, include this CDDL HEADER in each
.\" file and include the License file at usr/src/OPENSOLARIS.LICENSE.
.\" If applicable, add the following below this CDDL HEADER, with the
.\" fields enclosed by brackets "[]" replaced with your own identifying
.\" information: Portions Copyright [yyyy] [name of copyright owner]
.\"
.\" CDDL HEADER END
.\" Copyright (c) 1999, Sun Microsystems, Inc.
.\" Copyright 2007-2013 J. Schilling
.TH sccs-sact 1 "2013/06/16" "SunOS 5.11" "User Commands"
.SH NAME
sccs-sact, sact \- show editing activity status of an SCCS file
.SH SYNOPSIS
.LP
.nf
\fB/usr/ccs/bin/sact\fR [\fB\-s\fR] \fIs.filename\fR...
.fi

.SH DESCRIPTION
.LP
The
.B sact
utility informs the user of any
.B SCCS
files that are checked out for editing.
.LP
The output for each named file consists of five fields separated by
.B SPACE
characters.
.RS +4
.TP
.ie t \(bu
.el o
\fBSID\fR of a delta that currently exists in the \fBSCCS\fR file, to which changes will be made to make the new delta
.RE
.RS +4
.TP
.ie t \(bu
.el o
\fBSID\fR for the new delta to be created
.RE
.RS +4
.TP
.ie t \(bu
.el o
Username of the person who has the file checked out for editing.
.RE
.RS +4
.TP
.ie t \(bu
.el o
Date that the version was checked out.
.RE
.RS +4
.TP
.ie t \(bu
.el o
Time that the version was checked out.
.RE
.LP
If a directory name is used in place of the \fIs.filename\fR argument, the \fBsact\fR command applies to all \fBs.\fRfiles in that directory. Unreadable \fBs.\fRfiles produce an error; processing continues with the next file (if any). The use of `\fB\(mi\fR' as the \fIs.filename\fR argument indicates that the names of files are to be read from the standard input, one \fBs.\fRfile per
line.
.SH OPTIONS
.br
.ne 2
.TP
.B \-s
Suppresses the error message when a file is not currently edited.
.br
.ne 2
.TP
.B \-V
Prints the
.B sact
version number string and exists.

.SH ENVIRONMENT VARIABLES
.LP
See 
\fBenviron\fR(5) for descriptions of the following environment variables that affect the execution of \fBsact\fR: LANG, LC_ALL, LC_CTYPE, LC_MESSAGES, and NLSPATH.
.SH ATTRIBUTES
.LP
See 
.BR attributes (5)
for descriptions of the following attributes:
.LP
.TS
tab() box;
cw(2.75i) |cw(2.75i) 
lw(2.75i) |lw(2.75i) 
.
ATTRIBUTE TYPEATTRIBUTE VALUE
_
AvailabilitySUNWsprot
_
Interface StabilityStandard
.TE

.SH SEE ALSO
.LP
.BR sccs (1),
.BR sccs-admin (1),
.BR sccs-cdc (1),
.BR sccs-comb (1),
.BR sccs-delta (1),
.BR sccs-get (1),
.BR sccs-help (1),
.BR sccs-prs (1),
.BR sccs-prt (1),
.BR sccs-rmdel (1),
.BR sccs-sccsdiff (1),
.BR sccs-unget (1),
.BR sccs-val (1),
.BR sccscvt (1),
.BR sccslog (1),
.BR bdiff (1), 
.BR diff (1), 
.BR what (1),
.BR changeset (4),
.BR sccsfile (4),
.BR attributes (5),
.BR environ (5),
.BR standards (5).

.SH DIAGNOSTICS

.LP
Use the SCCS
.B help
command for explanations (see 
.BR sccs-help (1)).
