'\" te
.\" CDDL HEADER START
.\"
.\" The contents of this file are subject to the terms of the
.\" Common Development and Distribution License ("CDDL"), version 1.0.
.\" You may only use this file in accordance with the terms of version
.\" 1.0 of the CDDL.
.\"
.\" A full copy of the text of the CDDL should have accompanied this
.\" source.  A copy of the CDDL is also available via the Internet at
.\" http://www.opensource.org/licenses/cddl1.txt
.\"
.\" When distributing Covered Code, include this CDDL HEADER in each
.\" file and include the License file at usr/src/OPENSOLARIS.LICENSE.
.\" If applicable, add the following below this CDDL HEADER, with the
.\" fields enclosed by brackets "[]" replaced with your own identifying
.\" information: Portions Copyright [yyyy] [name of copyright owner]
.\"
.\" CDDL HEADER END
.\" Copyright (c) 1990, Sun Microsystems, Inc.
.\" Copyright 2007-2013 J. Schilling
.TH sccs-unget 1 "2013/06/16" "SunOS 5.11" "User Commands"
.SH NAME
sccs-unget, unget \- undo a previous get of an SCCS file
.SH SYNOPSIS
.LP
.nf
\fB/usr/ccs/bin/unget\fR [\fB-ns\fR] [\fB-r\fR\fIsid\fR] \fIs.filename\fR...
.fi

.SH DESCRIPTION

.LP
The \fBunget\fR utility undoes the effect of a \fBget\fR\fB-e\fR command executed before the creation of the pending delta.
.sp

.LP
If a directory name is used in place of the \fIs.filename\fR argument, the \fBunget\fR command applies to all \fBs.\fRfiles in that directory. Unreadable \fBs.\fRfiles produce an error; processing continues with the next file (if any). The use of `\fB\(mi\fR' as the \fIs.filename\fR argument indicates that the names of files are to be read from the standard input, one \fBs.\fRfile per
line.
.sp

.SH OPTIONS

.LP
The following options are supported:
.sp

.sp
.ne 2
.TP 7
\fB\fB-n\fR\fR
Retains the retrieved version, which is otherwise removed.

.sp
.ne 2
.TP
\fB\fB-s\fR\fR
Suppress display of the \fBSCCS\fR delta \fBID\fR (SID).

.sp
.ne 2
.TP
\fB\fB-r\fR\fIsid\fR\fR
When multiple versions are checked out, this option specifies which pending delta to abort. A diagnostic results if the specified \fBSID\fR is ambiguous, or if it is necessary but omitted from the command line.

.ne 3
.TP
.B \-V
Prints the
.B unget
version number string and exists.

.SH ENVIRONMENT VARIABLES

.LP
See 
\fBenviron\fR(5) for descriptions of the following environment variables that affect the execution of \fBunget\fR: LANG, LC_ALL, LC_COLLATE, LC_CTYPE, LC_MESSAGES, and NLSPATH.
.sp

.SH FILES

.sp
.ne 2
.TP
.BI p. file
permissions (lock) file for checked-out versions

.sp
.ne 3
.TP
.BI q. file
temporary copy of the 
.BR p. file; 
renamed to the 
.BR p. file 
after completion 

.sp
.ne 3
.TP
.BI z. file
temporary lock file contains the binary process id in host byte order 
followed by the host name

.SH ATTRIBUTES

.LP
See 
\fBattributes\fR(5) for descriptions of the following attributes:
.sp

.LP

.sp
.TS
tab() box;
cw(2.75i) |cw(2.75i) 
lw(2.75i) |lw(2.75i) 
.
ATTRIBUTE TYPEATTRIBUTE VALUE
_
AvailabilitySUNWsprot
_
Interface StabilityStandard
.TE

.SH SEE ALSO
.LP
.BR sccs (1),
.BR sccs-admin (1),
.BR sccs-cdc (1),
.BR sccs-comb (1),
.BR sccs-delta (1),
.BR sccs-get (1),
.BR sccs-help (1),
.BR sccs-prs (1),
.BR sccs-prt (1),
.BR sccs-rmdel (1),
.BR sccs-sact (1),
.BR sccs-sccsdiff (1),
.BR sccs-val (1),
.BR sccscvt (1),
.BR sccslog (1),
.BR bdiff (1), 
.BR diff (1), 
.BR what (1),
.BR changeset (4),
.BR sccsfile (4),
.BR attributes (5),
.BR environ (5),
.BR standards (5).

.SH DIAGNOSTICS

.LP
Use the SCCS
.B help
command for explanations (see 
.BR sccs-help (1)).
