'\" te
.\" @(#)sccsfile.4	1.23 11/11/01 Copyright 2007-2011 J. Schilling */
.\" CDDL HEADER START
.\"
.\" The contents of this file are subject to the terms of the
.\" Common Development and Distribution License (the "License").  
.\" You may not use this file except in compliance with the License.
.\"
.\" You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
.\" or http://www.opensolaris.org/os/licensing.
.\" See the License for the specific language governing permissions
.\" and limitations under the License.
.\"
.\" When distributing Covered Code, include this CDDL HEADER in each
.\" file and include the License file at usr/src/OPENSOLARIS.LICENSE.
.\" If applicable, add the following below this CDDL HEADER, with the
.\" fields enclosed by brackets "[]" replaced with your own identifying
.\" information: Portions Copyright [yyyy] [name of copyright owner]
.\"
.\" CDDL HEADER END
.\" Copyright (c) 2002, Sun Microsystems, Inc. All Rights Reserved.
.\" Copyright 1989 AT&T
.\"  Copyright 2007-2011 J. Schilling
.TH sccsfile 4 "2011/11/01" "SunOS 5.11" "File Formats"
.SH NAME
sccsfile \- format of an SCCS history file
.SH DESCRIPTION

.LP
An SCCS file is an \fBASCII\fR file consisting of six logical parts:
.sp
.ne 3
.TP 12
.I checksum
Character count used for error detection.
.sp
.ne 3
.TP
.I "delta table
Log containing version info and statistics about each delta.
.sp
.ne 3
.TP
.I usernames
Login names and/or group IDs of users who may add deltas.
.sp
.ne 3
.TP
.I flags
Definitions of internal keywords.
.sp
.ne 3
.TP
.I v6 flags
Optional further internal definitions.
.B "SCCS v6
only.
.sp
.ne 3
.TP
.I v6 metadata
Optional global metadata.
.B "SCCS v6
only.
.sp
.ne 3
.TP
.I comments
An arbitrary descriptive information block about the file.
.sp
.ne 3
.TP
.I body
the Actual text lines intermixed with control lines.
This body is also known as
.B interleaved deltas
or
.BR "the weave" .

.LP
Each section is described in detail below.
.LP
This document describes the
.B SCCS v4
history file format that has been introduced in February 1977 as well
as the
.B SCCS v6
enhancements that have been introduced in summer 2011.

.SS Conventions

.LP
Throughout an SCCS file there are lines which begin with the
.B ASCII SOH
(start of heading) character (octal 001). This character is 
hereafter referred to as the
.IR "control character" ,
and will be represented as
.RB ` ^A '.
If a line described below is not depicted as beginning with the
control character, it cannot do so and still be within SCCS file format.

.LP
Entries of the form 
.I ddddd
represent a decimal number.
In the statistics line from the delta table, this represents a
five digit string (a number between 00000 and 99999).
Other numbers are not artificially limited to a specific range.
.B Serial numbers
and
.B SID
number components may be any non negative number representable by a
signed 32 bit integer.
.LP
The usable range is however limited by the available virtual memory.
This implementation needs virtual memory that is 
approx. 100 times the highest serial number from the file.

.br
.ne 5
.SS Checksum

.LP
The checksum is the first line of an SCCS file. The form of the line is:

.LP
.in +2
.nf
^Ah\fIddddd\fR
.fi
.in -2

.LP
The value of the checksum is the low 16 bits from the signed sum of all characters,
except those contained in the first line.
When reading files, values computed as the unsigned sum of all characters are accepted too.
The
.B ^Ah
provides a 16 bit
.I magic number
of (octal) 064001 in PDP-byteorder and 000550 in Motorola-byteorder ("\e001\e150").
.br
.ne 5
.SS SCCS v6 Checksum
.LP
SCCS v6 introduces a modified checksum line:
.LP
.in +2
.nf
^AhV6,sum=\fIddddd\fR
.fi
.in -2
.LP
The checksum line was changed in order to prevent historic SCCS
implementations from accidentally ignoring project-related (project-global)
locks. It permits future versions to decide on different checksum
algorithms without a need to introduce a new history file format.
.LP
In SCCS v6, the
.B ^Ah
magic is not directly followed by the checksum but by the letter
.B V
that is followed by the SCCS version number. The version number is followed by
a comma and the checksum algorithm name. The string
.B sum
is interpreted as the SCCS v4 checksum method. The SCCS v4 checksum entry must
directly follow the SCCS version number.
.LP
Further checksums may be added in the future, e.g.:
.LP
.in +2
.nf
^AhV6,sum=\fIddddd\fR,md5=\fIhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh\fR
.fi
.in -2
.LP
but the
.B sum=
entry is mandatory. SCCS v6 currently does not implement 
checksum algorithms other than 
.BR sum .
Other entries are currently ignored when reading and silently discarded when
copying or modifying files.

.br
.ne 5
.SS Delta Table

.LP
The delta table consists of a variable number of entries of the form:

.LP
.in +2
.nf
^As \fIinserted\|\fR/\fIdeleted\fR/\fIunchanged\fR
^Ad \fItype  sid  yr\fR/\fImo\fR/\fIda hr\fR:\fImi\fR:\fIse  username  serial-number \e
predecessor-sn\fR
^Ai \fIinclude-list\fR
^Ax \fIexclude-list\fR
^Ag \fIignored-list\fR
^Am \fImr-number\fR
\&...
^Ac \fIcomments\fR ...
\&...
^Ae 
.fi
.in -2
.sp

.LP
The first line
.RB ( ^As )
contains the number of lines inserted/deleted/unchanged respectively.
The actual values for inserted/deleted/unchanged are five digit numbers.
If an actual value is greater than 99999, then it is replaced by 99999.
.LP
The second line
.RB ( ^Ad )
contains the type of the delta (normal:
.B D
and removed:
.BR R ),
the SCCS ID
.RB ( SID )
of the delta, the date and
time of creation of the delta as local time, the user-name corresponding to the
real user ID at the time the delta was created, and the serial numbers
of the delta and its predecessor, respectively. The year is either represented
by a two digit year in the range 69..99 for 1969..1999 or 00..68 for 2000..2068
or by a four digit year number. Year numbers before 1969 are currently not
supported.
.LP
The
.BR ^Ai ,
.BR ^Ax ,
and 
.B ^Ag
lines contain the serial numbers
of deltas included, excluded, and ignored, respectively.
These lines do not always appear.
.LP
The
.B ^Am
lines (optional) each contain one MR number associated with the delta. The
.B ^Ac
lines contain comments associated with the delta.
.LP
The
.B ^Ae
line ends the delta table entry.

.br
.ne 8
.SS SCCS v6 Delta Table
.LP
SCCS v6 uses an enhanced delta table:
.LP
.in +2
.nf
^As \fIinserted\|\fR/\fIdeleted\fR/\fIunchanged\fR
^Ad \fItype  sid  yr\fR/\fImo\fR/\fIda hr\fR:\fImi\fR:\fIse\fR[.\fIss\fR]+-\fIhhmm\fR \fIusername \e
serial-number predecessor-sn\fR
^Ai \fIinclude-list\fR
^Ax \fIexclude-list\fR
^Ag \fIignored-list\fR
^Am \fImr-number\fR
\&...
^AS \fIsid-specific metadata\fR
\&...
^Ac \fIcomments\fR ...
\&...
^Ae 
.fi
.in -2
.sp
.LP
The second line
.RB ( ^Ad )
must have a four digit year number,
may add sub-second time stamp granularity and must have a time zone offset.
.LP
Optional sub-second time stamp granularity is introduced by a dot
.RB ` . '
and adds one to nine decimal digits that represent a fraction of a second
up to nanosecond granularity. This number must be non-negative.
.LP
The time zone offset starts with a 
.RB ` + '
or a
.RB ` - ',
the value
.B 0000
starts with a
.RB ` + ',
negative values start with a
.RB ` - '.
Positive values are east to GMT.
The first two decimal digits represent the hour part of the GMT offset, the last
two decimal digits represent the minute part of the GMT offset. A granularity
less than a minute cannot be represented.
.LP
The date and time part represents local time as in SCCS v4 entries.
.LP
The entry
.B ^AS
introduces a SID specific SCCS v6 extension.
SID specific extension lines are in name/value format and take the form:
.LP
.RS
 ^AS
.B name
.I optional value text
.RE
.br
.ne 8
.LP
The following
.B name
parameters are defined:
.LP
.RS
.br
.ne 5
.TP 10
.BI p " path
Record the current path of the
.B g-file
relatively to the project's file set home directory. A
.B path
entry only appears in case a rename has been applied to the file.
.sp
The
.B project set home
is a directory that holds a directory
.B .sccs
for project specific SCCS metadata. The location of this directory 
.B .sccs
is searched for by
scanning the filesystem towards the root directory starting from the
current working directory. All files that belong to a project must be
below the project's file set home directory.
.sp
See also the description for the same keyword in the section for 
global meta data, where the the initial file name is recorded.
.TP 10
.BI s " nnnnn
A SID specific additional checksum.
The value of the checksum is the low 16 bits from the unsigned
sum of all characters in the SID specific file content as retrieved by
.B `get -e'
(without keyword expansion).
If the file is archived UU-encoded (see 
.B `e'
flag), the checksum is computed on the UU-encoded text and not
on the original file.
.RE
.LP
The data format in the extended SCCS delta entry
.RB ( ^Ad )
and the SCCS SID specific metadata
.RB ( ^AS )
is not accepted by historic SCCS implementations.
When converting a SCCS v6 history file back to a SCCS v4 history file,
these entries are converted into special comment at the beginning of the
comment section. While converting,
.B ^Ad
is turned into
.B ^Ac_d
and
.B ^AS
is turned into
.BR ^Ac_S .

.SS User Names

.LP
The list of user-names and/or numerical group IDs of users who may add deltas to the file, separated by NEWLINE characters. The lines containing these login names and/or numerical group IDs are surrounded by the bracketing lines
.B ^Au
and
.BR ^AU .
An empty list allows anyone to make a delta.

.SS Flags

.LP
Flags are keywords that are used internally (see 
\fBsccs-admin\fR(1) for more information on their use). 
Each flag line takes the form:

.LP
.RS
 ^Af
.B flag
.I optional text
.RE
.LP
Flags may be selected from the set of 26 lower case characters in the range
.RB ` a '..` z '.
Historical SCCS implementations will dump core in case a
character outside the specified range appears as flag character.

.LP
The following flags are defined in order of appearance:
.ne 3
.TP 24
\fB\fB^Af t\fR \fItype-of-program\fR\fR
Defines the replacement for the \fB%\&Y%\fR ID keyword.
.ne 3
.TP
\fB\fB^Af v\fR \fIprogram-name\fR\fR
Controls prompting for MR numbers in addition to comments. If the optional text is present, it defines an MR number validity checking program.
.sp
The
.B v
flag and the
.B z
flag are mutually exclusive.
.ne 3
.TP
\fB\fB^Af i\fR [\fIvalue\fR]
Indicates that the
.RB `  "No id keywords" '
message is to generate an error that terminates the SCCS command.
Otherwise, the message is treated as a warning only.
.sp
If the parameter
.I value
to the
.RB ` i '
flag is not empty, then it holds a line fragment with keywords
starting with a
.RB ` "%" ',
e.g.
.br
.RB "        `" "%\&Z%%\&M%	%\&I% %\&E%" '
.br
This line fragment needs to exactly match a part of a line in the file
and to result in expanded keywords. Otherwise an attempt to check in a 
new delta will fail.
The parameter to the
.RB ` i '
flag is a
.B \s-1SUN\s+1
extension.
.ne 3
.TP
\fB\fB^Af b\fR \fR
Indicates that the \fB-b\fR option may be used with the SCCS \fBget\fR command to create a branch in the delta tree.
.ne 3
.TP
\fB\fB^Af m\fR \fImodule-name\fR\fR
Defines the first choice for the replacement text of the \fB%\&M%\fR ID keyword.
.ne 3
.TP
\fB\fB^Af f\fR \fIfloor\fR\fR
Defines the "floor" release, that is, the release below which no deltas may be added.
.ne 3
.TP
\fB\fB^Af c\fR \fIceiling\fR\fR
Defines the "ceiling" release, that is, the release above which no deltas may be added.
.ne 3
.TP
\fB\fB^Af d\fR \fIdefault-sid\fR\fR
The \fBd\fR flag defines the default SID to be used when none is specified on an SCCS \fBget\fR command.
.ne 3
.TP
\fB\fB^Af n\fR \fR
The \fBn\fR flag enables the SCCS \fBdelta\fR command to insert a "null" delta (a delta that applies \fIno\fR changes) in those releases that are skipped when a delta is made in a \fInew\fR release (for example,
when delta 5.1 is made after delta 2.7, releases 3 and 4 are skipped).
.ne 3
.TP
\fB\fB^Af j\fR \fR
Enables concurrent
.B get \-e
calls for editing on the same base
.B SID
of an SCCS file.
This allows multiple concurrent updates to take place on the same version of the SCCS file.
.ne 3
.TP
\fB\fB^Af l\fR \fIlock-releases\fR\fR
Defines a list of releases that are locked against editing.
.ne 3
.TP
\fB\fB^Af q\fR \fIuser-defined\fR\fR
Defines the replacement for the \fB%\&Q%\fR ID keyword.
.ne 3
.TP
\fB\fB^Af e\fR \fB0\fR|\fB1\fR\fR
The \fBe\fR flag indicates whether a source file is encoded or not. A \fB1\fR indicates that the file is encoded. Source files need to be encoded when they contain control characters, or when they do not end with a NEWLINE. The \fBe\fR flag
allows files that contain binary data to be checked in.
.ne 3
.TP
.BI "^Af z " application
The name of an
.B application
for the
.B CMF
enhancements.
.B CMF
enhancements are currently undocumented and it is not known
how they are expected to work.
.sp
The
.B v
flag and the
.B z
flag are mutually exclusive.
.ne 3
.TP
.BI "^Af s " nnn
The number of lines to be scanned for keyword expansion. 
.sp
This flag is a
.B \s-1SUN\s+1
extension that does not exist in historic
.B sccs
implementations.

.ne 3
.TP
.BR "^Af x SCHILY" | 0
Enable 
.B sccs
extensions that are not implemented in classical 
.B sccs
variants. If the
.B `x'
flag is enabled, the keywords
.BR %\&d\&% ", " %\&e\&% ", " %\&g\&% 
and
.B %\&h\&%
are expanded even though not explicitly enabled by the
.B `y'
flag.
.sp
This flag is a
.B \s-1SCHILY\s+1
extension that does not exist in historic
.B sccs 
implementations. 
.sp
This version of SCCS implements compatibility support for a SCO SCCS
extension that sets the executable bit in the file permissions of a
gotten file if the
.BR x -flag
was set in the history file with no parameter. This version of SCCS
does not allow to set this variant of the
.BR x -flag
in the history file.
If you like to get executable files from SCCS, set the executable
bit in the file permissions of the history file.

.ne 5
.TP
.BI "^Af y " "val .\|.\|.
The list of sccs keywords to be expanded.
If the
.BR y -flag
is missing in the sccs historyfile, all sccs keywords are expanded.
If the flag is present but the list is empty, no keyword is expanded
and no
.RB `  "No id keywords" '
message is generated.
The value `\fB*\fP' controls the 
expansion of the \fB%\&sccs.include.\fIfilename\fB\&%\fR keyword.
.sp
This flag is a
.BR \s-1SUN\s+1 / SCHILY
extension that does not exist in historic
.B sccs 
implementations. 

.br
.ne 6
.SS SCCS v6 Flags
.LP
Scccs v6 flags are additional keywords that are used internally (see 
\fBsccs-admin\fR(1) for more information on their use).
Each flag line takes the form:
.LP
.RS
 ^AF
.B flag
.I optional text
.RE
.LP
No SCCS v6 flags are currently defined.
.LP
Historical SCCS implementations do not complain about SCCS v6 flags when
reading SCCS history files and retain SCCS v6 flags when modifying history files.
This is why SCCS v6 flags may be kept unmodified when converting a SCCS v6
history file back to a SCCS v4 history file.

.br
.ne 6
.SS SCCS v6 Metadata
.LP
Scccs v6 metadata is additional global metadata that is used internally (see 
\fBsccs-admin\fR(1) for more information on it's use).
Each metadata line takes the form:
.LP
.RS
 ^AG
.B keyword
.I optional text
.RE
.br
.ne 8
.LP
The following
.B keywords
are defined:
.LP
.RS
.br
.ne 6
.TP 10
.BI p " path
Record the initial path of the
.B g-file
relatively to the project's file set home directory. Once set up, this name
must never change.
.sp
See also the description for the project set home in the documentation for the
same keyword in the section for SID specific meta data of the delta table.
In case of a rename, the new file name is recorded in in the SID specific
meta data of the delta table.
.br
.ne 6
.TP
.BI r " random
A unified pseudo random number that is used to help to identify single files
across renames during the lifetime of the sccs history.
.sp
The pseudo random number is a hexadecimal string that represents the
microseconds since 2004\ Jan\ 10\ 13:37:04\ UTC when initially creating the
sccs history file. Including microseconds gives sufficient randomness
to make clashes rare.
.sp
With a 32 bit signed
.BR time_t ,
52 bits in the pseudo random number are sufficient.
With a 64 bit pseudo random number, more than 500000 years are covered.
.RE
.LP
The
.B random
metadata is mandatory for SCCS v6 history files. The initial path tag may be
recorded later but before the changeset file is created.
The value for this metadata tags must not change.
.LP
Historical SCCS implementations do not complain about SCCS v6 metadata when
reading SCCS history files and retain SCCS v6 metadata when modifying history files.
This is why SCCS v6 metadata may be kept unmodified when converting a SCCS v6
history file back to a SCCS v4 history file.


.SS Comments

.LP
Arbitrary text surrounded by the bracketing lines \fB^At\fR and \fB^AT\fR. The comments section typically will contain a description of the file's purpose.

.SS Body

.LP
The body consists of text lines and control lines.
Text lines do not begin with the control character, unless they
are using SCCS v6 escape extensions. Control lines always begin with the
control character.
.LP
There are three kinds of control lines:
.IR insert ,
.IR delete ,
and
.IR end ,
represented by:

.LP
.in +2
.nf
^AI \fIddddd\fR
^AD \fIddddd\fR
^AE \fIddddd\fR 
.fi
.in -2

.LP
respectively. The digit string is the serial number corresponding to the delta for the control line.

.SS "SCCS v6 Body escape extensions"
.LP
There are two additional types of text lines with a control character at the
beginning that represent features introduced by SCCS v6.
These features are not understood by SCCS implementations that support the
SCCS v4 history file format only.
.LP
.RS +2
.TP 10
^A^A
A line in the interleaved delta block that begins with two control characters
represents a text line that begins at the second control character.
.TP
^AN
A line in the interleaved delta block that begins with the
.B "^AN"
sequence represents a text line that does not end with a newline character.
A line in the form
.B "^AN^Atext"
is extracted as
.B "^Atext"
without a need to add another quote.
.RE

.br
.ne 5
.SH SEE ALSO
.LP
.BR sccs (1),
.BR sccs-admin (1),
.BR sccs-cdc (1),
.BR sccs-comb (1)
.BR sccs-delta (1),
.BR sccs-get (1),
.BR sccs-help (1),
.BR sccs-prs (1),
.BR sccs-prt (1),
.BR sccs-rmdel (1),
.BR sccs-sact (1),
.BR sccs-sccsdiff (1),
.BR sccs-unget (1),
.BR sccs-val (1),
.BR sccscvt (1),
.BR sccslog (1),
.BR bdiff (1), 
.BR diff (1), 
.BR what (1).

.SH BUGS
.LP
SCCS v4 uses local time without a timezone offset. If a delta is created less
than an hour after switching from DST to non-DST, it may look as if the clock
is going backwards.
SCCS v6 fixes this problem by introducing a timezone offset.
