. \" %Z%%M%	%I% %E% Copyr 2009 J. Schilling
. \"  Manual page for mdigest
. \"
.if t .ds a \v'-0.55m'\h'0.00n'\z.\h'0.40n'\z.\v'0.55m'\h'-0.40n'a
.if t .ds o \v'-0.55m'\h'0.00n'\z.\h'0.45n'\z.\v'0.55m'\h'-0.45n'o
.if t .ds u \v'-0.55m'\h'0.00n'\z.\h'0.40n'\z.\v'0.55m'\h'-0.40n'u
.if t .ds A \v'-0.77m'\h'0.25n'\z.\h'0.45n'\z.\v'0.77m'\h'-0.70n'A
.if t .ds O \v'-0.77m'\h'0.25n'\z.\h'0.45n'\z.\v'0.77m'\h'-0.70n'O
.if t .ds U \v'-0.77m'\h'0.30n'\z.\h'0.45n'\z.\v'0.77m'\h'-.75n'U
.if t .ds s \(*b
.if t .ds S SS
.if n .ds a ae
.if n .ds o oe
.if n .ds u ue
.if n .ds s sz
.TH MDIGEST 1L "2022/08/17" "J\*org Schilling" "Schily\'s USER COMMANDS"
.SH NAME
mdigest \- calculate a message digest
.SH SYNOPSIS
.B
mdigest
.B \-a
.I algorithm
[
.I options
] [
.I file1 .\|.\. filen
]
.SH DESCRIPTION
.B mdigest
reads the files from the argument list and computes a message digest hash
for the file content.
If the argument list is empty
.B mdigest
reads from standard in.

.SH OPTIONS
All options can be abbreviated by their first letter.
.TP
.BI \-a " algorithm"
Specified the message digest hash algorithm to use.
.TP
.B \-l
Lists the available message digest hash algorithms. This list may depend on the
platform and the compiler that was used to create the binary.
.TP
.B \-help
Prints a short summary of the 
.BR mdigest (1)
options and exists.
.TP
.B \-verbose
Verbose output. Includes the message digest hash algorithm name in the output.
.TP
.B \-version
Prints the 
.BR mdigest (1)
version number string and exists.

.\" .SH ENVIRONMENT
.\" .SH FILES
.SH NOTES
If you call
.B mdigest
with no file type arguments, it will compute the digest for
.BR stdin .

.SH BUGS
.PP
None currently known.
.PP
Mail bugs and suggestions to
.B schilytools@mlists.in-berlin.de
or open a ticket at
.BR https://codeberg.org/schilytools/schilytools/issues .
.PP
The mailing list archive may be found at:
.PP
.nf
.BR https://mlists.in-berlin.de/mailman/listinfo/schilytools-mlists.in-berlin.de .
.fi

.SH AUTHORS
J\*org Schilling and the schilytools project authors.

.SH "SOURCE DOWNLOAD"
The source code for
.B mdigest
is included in the
.B schilytools
project and may be retrieved from the
.B schilytools
project at Codeberg at
.LP
.BR https://codeberg.org/schilytools/schilytools .
.LP
The download directory is
.LP
.BR https://codeberg.org/schilytools/schilytools/releases .
