. \" @(#)udiff.1	1.5 10/05/11 Copyright 1985-2010 J. Schilling
. \"  Manual page for diff
. \"
.if t .ds a \v'-0.55m'\h'0.00n'\z.\h'0.40n'\z.\v'0.55m'\h'-0.40n'a
.if t .ds o \v'-0.55m'\h'0.00n'\z.\h'0.45n'\z.\v'0.55m'\h'-0.45n'o
.if t .ds u \v'-0.55m'\h'0.00n'\z.\h'0.40n'\z.\v'0.55m'\h'-0.40n'u
.if t .ds A \v'-0.77m'\h'0.25n'\z.\h'0.45n'\z.\v'0.77m'\h'-0.70n'A
.if t .ds O \v'-0.77m'\h'0.25n'\z.\h'0.45n'\z.\v'0.77m'\h'-0.70n'O
.if t .ds U \v'-0.77m'\h'0.30n'\z.\h'0.45n'\z.\v'0.77m'\h'-.75n'U
.if t .ds s \(*b
.if t .ds S SS
.if n .ds a ae
.if n .ds o oe
.if n .ds u ue
.if n .ds s sz
.TH UDIFF 1 "10/05/11" "J\*org Schilling" "Schily\'s USER COMMANDS"
.SH NAME
udiff \- shows where two files differ
.SH SYNOPSIS
.B
.B udiff
[ 
.I options 
]
.I file1 file2
.SH DESCRIPTION
diff shows what lines differ between two files.
.SH OPTIONS
.TP
.B \-help
Prints a short summary of the 
.B udiff
options and exists.
.TP
.B \-version
Prints the 
.B udiff
version number string and exists.
.TP
.BI nmatch= #
Sets the number of matching lines to resync.
If
.B udiff
is called as 
.BR udiff ,
the default is two lines, otherwise it is one line.
.TP
.B \-posix
Outout the differences in POSIX style instead of using
.B udiff
style.
.SH NOTES
No output is generated if the files are the same.
