. \" @(#)librmt.3	1.10 20/09/04 Copyr 2002-2020 J. Schilling
. \" Manual page for librmt
. \"
.if t .ds a \v'-0.55m'\h'0.00n'\z.\h'0.40n'\z.\v'0.55m'\h'-0.40n'a
.if t .ds o \v'-0.55m'\h'0.00n'\z.\h'0.45n'\z.\v'0.55m'\h'-0.45n'o
.if t .ds u \v'-0.55m'\h'0.00n'\z.\h'0.40n'\z.\v'0.55m'\h'-0.40n'u
.if t .ds A \v'-0.77m'\h'0.25n'\z.\h'0.45n'\z.\v'0.77m'\h'-0.70n'A
.if t .ds O \v'-0.77m'\h'0.25n'\z.\h'0.45n'\z.\v'0.77m'\h'-0.70n'O
.if t .ds U \v'-0.77m'\h'0.30n'\z.\h'0.45n'\z.\v'0.77m'\h'-.75n'U
.if t .ds s \(*b
.if t .ds S SS
.if n .ds a ae
.if n .ds o oe
.if n .ds u ue
.if n .ds s sz
.TH LIBRMT 3L "2022/09/11" "J\*org Schilling" "Schily\'s LIBRARY FUNCTIONS"
.SH NAME
librmt \- remote magtape protocol client interface library (-lrmt)
.SH SYNOPSIS
.LP
.B #include <schily/librmt.h>
.SH DESCRIPTION
.LP
Functions in this library provide an interface to a remote tape server program.
.LP
This implementation takes care of
.B RMT protocol VERSION 1 
that is needed in case that
.B rmt
client and
.B rmt
server do not run on the same OS and use a CPU with the same bit width and byte order.
.LP
In addition, this implementation supports a GNU extension that allows one to use
.BR open (2)
flags beyond
.BR O_RDONLY ", " O_WRONLY ", " O_RDWR .

.SH ENVIRONMENT
.LP
.TP
.B RSH
If the 
.B RSH
environment is present, the remote connection will not be created via
.BR rcmd (3)
but by calling the program pointed to by
.BR RSH .
Use e.g. 
.BR RSH= /usr/bin/ssh
to create a secure shell connection.
.sp
If the environment
.B RSH
is empty, then the default
.BR rcmd (3)
is used even in case
.BR rmtrsh (3)
has been called.
.TP
.B RMT
If the 
.B RMT
environment is present, the remote tape server will not be the program
.B /etc/rmt
but the program pointed to by
.BR RMT .
.sp
If the environment
.B RMT
is empty, then the default
.B /etc/rmt
is used even in case
.BR rmtrmt (3)
has been called.
.sp
Note that the remote tape server program name will be ignored if you log in
using an account that has been created with a remote tape server program as
login shell.
.SH INTERFACES

.BR rmtinit (3),
.BR rmtdebug (3),
.BR rmtrmt (3),
.BR rmtrsh (3),
.BR rmthostname (3),\%
.BR rmtfilename (3),
.BR rmtgetconn (3),
.BR rmtopen (3),
.BR rmtioctl (3),
.BR rmtclose (3),
.BR rmtread (3),
.BR rmtwrite (3),
.BR rmtseek (3),
.BR rmtxstatus (3),
.BR rmtstatus (3),
.BR _mtg2rmtg (3),
.BR _rmtg2mtg (3)

.\" .SH FILES
.SH "SEE ALSO"
.BR rmt (1),
.BR rsh (1),
.BR ssh (1),
.BR rcmd (3)

.\".SH NOTES
.SH BUGS
.PP
None currently known.
.PP
Mail bugs and suggestions to
.B schilytools@mlists.in-berlin.de
or open a ticket at
.BR https://codeberg.org/schilytools/schilytools/issues .
.PP
The mailing list archive may be found at:
.PP
.nf
.BR https://mlists.in-berlin.de/mailman/listinfo/schilytools-mlists.in-berlin.de .
.fi

.SH AUTHORS
.B librmt
has been written in 1990 by J\*org Schilling.
In 1995, support for
.B RMT VERSION 1
has been added.
.B librmt
is now maintained by the schilytools project authors.

.SH "SOURCE DOWNLOAD"
The source code for
.B librmt
and
.B rmt
is included in the
.B schilytools
project and may be retrieved from the
.B schilytools
project at Codeberg at
.LP
.BR https://codeberg.org/schilytools/schilytools .
.LP
The download directory is
.LP
.BR https://codeberg.org/schilytools/schilytools/releases .
