#!/bin/sh
###########################################################################
#ident "@(#)MKLINKS	1.1 08/07/31 "
###########################################################################
# Written 2008 by J. Schilling
###########################################################################
# Copyright (c) 2008 J. Schilling
###########################################################################
# The contents of this file are subject to the terms of the
# Common Development and Distribution License, Version 1.0 only
# (the "License").  You may not use this file except in compliance
# with the License.
#
# See the file CDDL.Schily.txt in this distribution for details.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file CDDL.Schily.txt from this distribution.
###########################################################################
if [ ! -d RULES/. ]; then
	ln -s makefiles/RULES		.
fi
if [ ! -d DEFAULTS_DIST/. ]; then
	ln -s makefiles/DEFAULTS	DEFAULTS_DIST
fi
if [ ! -d autoconf/. ]; then
	ln -s conf			autoconf
fi
if [ ! -d libedc/. ]; then
	ln -s libedc_ecc		libedc
fi
if [ ! -d libschily/. ]; then
	ln -s lib			libschily
fi
if [ ! -d readcd/. ]; then
	ln -s cdrecord			readcd
fi
if [ ! -d smake/. ]; then
	ln -s build			smake
fi
