#!/bin/sh
###########################################################################
#ident "@(#)MKLINKS	1.5 11/08/04 "
###########################################################################
# Written 2008-2011 by J. Schilling
###########################################################################
# Copyright (c) 2008-2011 J. Schilling
###########################################################################
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2
# as published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# this program; see the file COPYING.  If not, write to the Free Software
# Foundation, 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
###########################################################################
symlink="ln -s"
MKLINKS_TEST=${MKLINKS_TEST-:}
if [ ".$MKLINKS_COPY" = '.' ]; then
	rm -f xxzzy.123 xxzzy.345
	echo test > xxzzy.123
	$symlink xxzzy.123 xxzzy.345
	test $? = 0 || symlink=cp
	test -r xxzzy.345 || symlink=cp
	${MKLINKS_TEST} -h xxzzy.345 || symlink=cp
	rm -f xxzzy.123 xxzzy.345
else
	symlink=cp
fi
###########################################################################

$symlink ../scsi.c		.
