#ident @(#)Makefile	1.8 21/06/05 
###########################################################################
SRCROOT=	../../../../..
RULESDIR=	RULES
include		$(SRCROOT)/$(RULESDIR)/rules.top
###########################################################################

#.SEARCHLIST:	. $(ARCHDIR) stdio $(ARCHDIR)
#VPATH=		.:stdio:$(ARCHDIR)
INSDIR=		lib
TARGETLIB=	mksh
CPPOPTS +=	-I../../../../include
CPPOPTS +=	-I../../../include
#CPPOPTS +=	-compat=4
CPPOPTS +=	-DSCHILY_INCLUDES
CPPOPTS +=	-DUSE_LARGEFILES
CPPOPTS +=	-DSUN5_0
CPPOPTS +=	-DSUNOS4_AND_AFTER
CPPOPTS +=	-DPMAKE
CPPOPTS +=	-DREDIRECT_ERR
#CPPOPTS +=	-DDO_DIRECTIO	# Fall back to the Sun O_DSYNC method

C++FILES=	dosys.cc globals.cc i18n.cc macro.cc misc.cc mksh.cc read.cc

LIBS=		

###########################################################################
include		$(SRCROOT)/$(RULESDIR)/rules.lib
###########################################################################
#CC=		echo "	==> COMPILING \"$@\""; cc
###########################################################################
