#ident @(#)Makefile.def	1.3 18/03/14 
###########################################################################
# Sample makefile for installing non-localized auxiliary files
###########################################################################
SRCROOT=	..
RULESDIR=	RULES
include		$(SRCROOT)/$(RULESDIR)/rules.top
###########################################################################

INSDIR=		share/lib/smake/
TARGET=		defaults.smk
XMK_FILE=	

###########################################################################
include		$(SRCROOT)/$(RULESDIR)/rules.aux
###########################################################################
