#ident @(#)Makefile.def	1.2 00/11/19 
###########################################################################
# Sample makefile for installing non-localized auxiliary files
###########################################################################
SRCROOT=	..
RULESDIR=	RULES
include		$(SRCROOT)/$(RULESDIR)/rules.top
###########################################################################

INSDIR=		lib/
TARGET=		defaults.smk
XMK_FILE=	

###########################################################################
include		$(SRCROOT)/$(RULESDIR)/rules.aux
###########################################################################
