'\" t
. \" @(#)star.4	1.43 20/09/04 Copyr 2003-2020 J. Schilling
. \" star archive formats
. \"
.if t .ds a \v'-0.55m'\h'0.00n'\z.\h'0.40n'\z.\v'0.55m'\h'-0.40n'a
.if t .ds o \v'-0.55m'\h'0.00n'\z.\h'0.45n'\z.\v'0.55m'\h'-0.45n'o
.if t .ds u \v'-0.55m'\h'0.00n'\z.\h'0.40n'\z.\v'0.55m'\h'-0.40n'u
.if t .ds A \v'-0.77m'\h'0.25n'\z.\h'0.45n'\z.\v'0.77m'\h'-0.70n'A
.if t .ds O \v'-0.77m'\h'0.25n'\z.\h'0.45n'\z.\v'0.77m'\h'-0.70n'O
.if t .ds U \v'-0.77m'\h'0.30n'\z.\h'0.45n'\z.\v'0.77m'\h'-.75n'U
.if t .ds s \(*b
.if t .ds S SS
.if n .ds a ae
.if n .ds o oe
.if n .ds u ue
.if n .ds s sz
.TH STAR 5L "2022/10/06" "J\*org Schilling" "Schily\'s USER COMMANDS"
.SH NAME
star \- tape archive file format
.SH DESCRIPTION
.PP
.B Tar
Archives are layered archives.
The basic structure is defined by the POSIX.1-1988 archive format and 
documented in the
.B "BASIC TAR HEADER DESCRIPTION"
section below.
The higher level structure is defined by the POSIX.1-2001 extended headers
and documented in the
.B "EXTENDED TAR (PAX) HEADER STRUCTURE"
section below.
POSIX.1-2001 extended headers are pseudo files that contain an unlimited number
of extended header keywords and associated values. The header keywords are
documented in the
.B "EXTENDED TAR (PAX) HEADER KEYWORDS"
section below.
.SH "BASIC TAR STRUCTURE"
.PP
A
.B tar
archive consists of a series of 512 byte
.RB ( TBLOCK )
records that are grouped to blocks
of typically 20 records (10240 bytes).
.LP
A number of TBLOCK sizes records are grouped together to a tape block for physical I/O
operations. Each block of 
.I n
records is written with a single
.BR write (2)
operation.
On magnetic tapes, this results in a single
.B tape record
in case the tape drive is in
.BR "variable length record mode" .
.LP
The block structure is only visible on blocked tapes.
A larger block size results in higher throughput.
Tapes that use a block size larger than
.B 63 kB
however may not be readable with any hardware and need to be avoided if 
read compatibility is important.
Older tar implementations do not support block sizes larger than 10240 bytes.
.LP
For fast backups, it is recommended to use block sizes of at least
.B 256\ kB
and to verify throughput and readability on available hardware.
.LP
Note that the terms
.B block
and
.B record
are frequently used inconsistently (starting in the historical documentation
from 1979 already) and that the term
.B block
is typically used for 512 bytes if the tape block size if not relevant in a
specific context.

.SH "BASIC TAR HEADER DESCRIPTION"
.PP
Physically, a POSIX.1-1988
.B tar
archive consists of a series of fixed sized blocks of TBLOCK (512) characters.
It contains a series of file entries terminated by a logical
end\-of\-archive marker, which consists of two blocks of 512 bytes of binary zeroes.
Each file entry is represented by a header block that describes the file followed by
zero or more blocks with the content of the file. The length of each file is rounded up
to a multiple of 512 bytes.
.PP
The header block is defined in star.h as follows:
.nf
/*
 * POSIX.1-1988 field size values and magic.
 */
#define	TBLOCK		512
#define	NAMSIZ		100
#define	PFXSIZ		155

#define	TMODLEN		8
#define	TUIDLEN		8
#define	TGIDLEN		8
#define	TSIZLEN		12
#define	TMTMLEN		12
#define	TCKSLEN		8

#define	TMAGIC		"ustar"	/* ustar magic 6 chars + '\e0' */
#define	TMAGLEN		6     	/* "ustar" including '\e0' */
#define	TVERSION		"00"
#define	TVERSLEN		2
#define	TUNMLEN		32
#define	TGNMLEN		32
#define	TDEVLEN		8

/*
 * POSIX.1-1988 typeflag values
 */
#define	REGTYPE		'0'	/* Regular File		*/
#define	AREGTYPE		'\e0'	/* Regular File (outdated) */
#define	LNKTYPE		'1'	/* Hard Link     		*/
#define	SYMTYPE		'2'	/* Symbolic Link		*/
#define	CHRTYPE		'3'	/* Character Special	*/
#define	BLKTYPE		'4'	/* Block Special		*/
#define	DIRTYPE		'5'	/* Directory     		*/
#define	FIFOTYPE		'6'	/* FIFO (named pipe)	*/
#define	CONTTYPE		'7'	/* Contiguous File		*/

/*
 * POSIX.1-2001 typeflag extensions.
 * POSIX.1-2001 calls the extended USTAR format PAX although it is
 * definitely derived from and based on USTAR. The reason may be that
 * POSIX.1-2001 calls the tar program outdated and lists the
 * pax program as the successor.
 */
#define	LF_GHDR		'g'	/* POSIX.1-2001 global extended header */
#define	LF_XHDR		'x'	/* POSIX.1-2001 extended header */
.fi
.PP
See section
.B "EXTENDED TAR (PAX) HEADER KEYWORDS"
for more information about the structure of a POSIX.1-2001 header.
.PP
.nf
/*
 * star/gnu/Sun tar extensions:
 *
 * Note that the standards committee allows only capital A through
 * capital Z for user-defined expansion.  This means that defining
 * something as, say '8' is a *bad* idea.
 */

#define	LF_ACL     	'A'	/* Solaris Access Control List	*/
#define	LF_DUMPDIR 	'D'	/* GNU dump dir               	*/
#define	LF_EXTATTR 	'E'	/* Solaris Extended Attribute File	*/
#define	LF_META    	'I'	/* Inode (metadata only) no file content */
#define	LF_LONGLINK	'K'	/* NEXT file has a long linkname	*/
#define	LF_LONGNAME    'L'	/* NEXT file has a long name    	*/
#define	LF_MULTIVOL	'M'	/* Continuation file rest to be skipped */
#define	LF_NAMES   	'N'	/* OLD GNU for names > 100 characters	*/
#define	LF_SPARSE  	'S'	/* This is for sparse files		*/
#define	LF_VOLHDR  	'V'	/* tape/volume header Ignore on extraction */
#define	LF_VU_XHDR 	'X'	/* POSIX.1-2001 xtended (Sun VU version) */

/*
 * Definitions for the t_mode field
 */
#define	TSUID   	04000	/* Set UID on execution	*/
#define	TSGID   	02000	/* Set GID on execution	*/
#define	TSVTX   	01000	/* On directories, restricted deletion flag */
#define	TUREAD  	00400	/* Read by owner    	*/
#define	TUWRITE 	00200	/* Write by owner special */
#define	TUEXEC  	00100	/* Execute/search by owner */
#define	TGREAD  	00040	/* Read by group      	*/
#define	TGWRITE 	00020	/* Write by group     	*/
#define	TGEXEC  	00010	/* Execute/search by group */
#define	TOREAD  	00004	/* Read by other		*/
#define	TOWRITE 	00002	/* Write by other		*/
#define	TOEXEC  	00001	/* Execute/search by other */

#define	TALLMODES	07777	/* The low 12 bits   	*/

/*
 * This is the ustar (Posix 1003.1) header.
 */
struct header {
	char t_name[NAMSIZ];	/*   0 Filename			*/
	char t_mode[8];		/* 100 Permissions   		*/
	char t_uid[8];  		/* 108 Numerical User ID		*/
	char t_gid[8];  		/* 116 Numerical Group ID	*/
	char t_size[12];		/* 124 Filesize			*/
	char t_mtime[12];   	/* 136 st_mtime			*/
	char t_chksum[8];   	/* 148 Checksum			*/
	char t_typeflag;		/* 156 Typ of File   		*/
	char t_linkname[NAMSIZ]; /* 157 Target of Links		*/
	char t_magic[TMAGLEN];   /* 257 "ustar"        		*/
	char t_version[TVERSLEN]; /* 263 Version fixed to 00	*/
	char t_uname[TUNMLEN];   /* 265 User Name          	*/
	char t_gname[TGNMLEN];   /* 297 Group Name         	*/
	char t_devmajor[8];   	/* 329 Major for devices		*/
	char t_devminor[8];   	/* 337 Minor for devices		*/
	char t_prefix[PFXSIZ];	/* 345 Prefix for t_name		*/
	                  		/* 500 End            		*/
	char t_mfill[12];    	/* 500 Filler up to 512		*/
};

/*
 * star header specific definitions
 */
#define	STMAGIC		"tar"	/* star magic */
#define	STMAGLEN		4    	/* "tar" including '\e0' */

/*
 * This is the new (post Posix 1003.1-1988) xstar header
 * defined in 1994.
 *
 * t_prefix[130]	is guaranteed to be '\0' to prevent ustar
 *				compliant implementations from failing.
 * t_mfill & t_xmagic need to be zero for a 100% ustar compliant
 *				implementation, so setting t_xmagic to
 *				"tar" should be avoided in the future.
 *
 * A different method to recognize this format is to verify that
 * t_prefix[130]    		is equal to '\0' and
 * t_atime[0]/t_ctime[0]    	is an octal number and
 * t_atime[11]      		is equal to ' ' and
 * t_ctime[11]      		is equal to ' '.
 *
 * Note that t_atime[11]/t_ctime[11] may be changed in future.
 */
struct xstar_header {
	char t_name[NAMSIZ];	/*   0 Filename			*/
	char t_mode[8];		/* 100 Permissions   		*/
	char t_uid[8];  		/* 108 Numerical User ID		*/
	char t_gid[8];  		/* 116 Numerical Group ID	*/
	char t_size[12];		/* 124 Filesize			*/
	char t_mtime[12];   	/* 136 st_mtime			*/
	char t_chksum[8];   	/* 148 Checksum			*/
	char t_typeflag;		/* 156 Typ of File   		*/
	char t_linkname[NAMSIZ]; /* 157 Target of Links		*/
	char t_magic[TMAGLEN];   /* 257 "ustar"        		*/
	char t_version[TVERSLEN]; /* 263 Version fixed to 00	*/
	char t_uname[TUNMLEN];   /* 265 User Name          	*/
	char t_gname[TGNMLEN];   /* 297 Group Name         	*/
	char t_devmajor[8];   	/* 329 Major for devices		*/
	char t_devminor[8];   	/* 337 Minor for devices		*/
	char t_prefix[131];   	/* 345 Prefix for t_name		*/
	char t_atime[12];		/* 476 st_atime			*/
	char t_ctime[12];		/* 488 st_ctime			*/
	char t_mfill[8];		/* 500 Filler up to star magic	*/
	char t_xmagic[4];     	/* 508 "tar"           		*/
};

struct sparse {
	char t_offset[12];
	char t_numbytes[12];
};

#define	SPARSE_EXT_HDR  21

struct xstar_ext_header {
	struct sparse t_sp[21];
	char t_isextended;
};

typedef union hblock {
	char dummy[TBLOCK];
	long ldummy[TBLOCK/sizeof (long)];	/* force long alignment */
	struct header          	dbuf;
	struct xstar_header    	xstar_dbuf;
	struct xstar_ext_header	xstar_ext_dbuf;
} TCB;
.fi
.PP
For maximum portability, all fields that contain character strings should be
limited to use the low 7 bits of a character.
.PP
The
.IR name ,
.I linkname
and
.I prefix
field contain character strings. The strings are null terminated
except when they use the full space of 100 characters for the
.I name
or
.I linkname
field or 155 characters
for the
.I prefix
field.
.PP
If the
.I prefix
does not start with a null character, then
.I prefix
and
.I name
need to be concatenated by using the
.IR prefix ,
followed by a slash character followed by the
.I name
field.
If a null character appears in
.I name
or
.I prefix
before the maximum size is reached, the field in question is terminated.
This way file names up to 256 characters may be archived.
The
.I prefix
is not used together with the
.I linkname
field, so the maximum length of a link name is 100 characters.
.PP
The fields
.IR magic ,
.I uname
and
.I gname
contain null terminated character strings.
.PP
The version field contains the string \fB"00"\fP
without a trailing zero. It cannot be set to different values as POSIX.1-1988
did not specify a way to handle different version strings.
.PP
The
.I typeflag
field contains a single character.
.PP
All numeric fields contain
.I size-1
leading zero-filled numbers using octal digits.
They are followed by one or more space or null characters.
All recent implementations only use one space or null character at the end
of a numerical field to get maximum space for the octal number.
.B Star
always uses a space character as terminator.
Numeric fields with 8 characters may hold up to 7 octal digits (7777777)
which results is a maximum value of 2097151.
Numeric fields with 12 characters may hold up to 11 octal digits (77777777777)
which results is a maximum value of 8589934591.
.PP
.B Star
implements a vendor specific (and thus non-POSIX) extension to put bigger numbers
into the numeric fields. This is done by using a 
.B base 256
coding.
The top bit of the first character in the appropriate 8 character or
12 character field is set to flag non octal coding.
If
.B base 256
coding is in use, then all remaining characters are used to code
the number. This results in 7
.B base 256
digits in 8 character fields and in 11
.B base 256
digits in 12 character fields.
All
.B base 256
numbers are two's complement numbers. A
.B base 256
number in a
8 character field may hold 56 bits, a
.B base 256
number in a 12 character
field may hold 88 bits.
.sp
This may be extended to 63 bits for 8 character fields
and to 95 bits for 12 character fields. For a negative number, the first
character currently is set to a value of 255 (all 8 bits are set).
For a positive number, the first character currently is set to 128 (the top
bit is set and all other bits are cleared).
.sp
The rightmost character in a 8 or 12 character field contains the least
significant
.B base 256
number.
.sp
Recent GNU tar and BSD libarchive versions implement the same extension.
.PP
While the POSIX standard makes it obvious that the fields
.IR "mode" , " uid" , " gid" ,
.IR " size", " chksum" ,
.I devmajor
and
.I devminor
should be treated as unsigned numbers, there is no such definition for the
.I time
field.
.PP
The mode field contains 12 bits holding permissions,
see above for the definitions for each of the permission bits.
.PP
The
.I uid
and
.I gid
fields contain the numerical user id and group id of the file.
These fields may use a
.B base 256
encoding.
.PP
The
.I size
field contains the size of the file in characters.
If the
.I tar header
is followed by file data, then the amount of data that follows is computed by
.IR "(size + 511) / 512" .
This field may use a
.B base 256
encoding.
.PP
The
.I mtime
field contains the number of seconds since Jan 1st 1970 00:00 UTC
as retrieved via 
.BR stat (2)
in 
.IR st_mtime .
If the
.I mtime
field is assumed to be a signed 33 bit number, the latest representable time
is 2106 Feb  7 06:28:15 GMT. This is because POSIX does not mention whether
the time has to be a signed or unsigned number and thus no more than 32 bits
may be used for a positive value if applications care about
portability.
This field may use a
.B base 256
encoding.
.PP
The
.I chksum
field contains a simple checksum over all bytes of the header.
To compute the value, all characters in the header are treated as
unsigned integers and the characters in the
.I chksum
field are treated as if they were all spaces. When the computation starts,
the checksum value is initialized to 0.
.PP
The
.I typeflag
field specifies the type of the file that is archived. If a specific
.B tar
implementation does not include support for a specific typeflag value,
this implementation will extract the unknown file types as if they were
plain files. For this reason, the
.I size
field for any file type except directories, hard links, symbolic links,
character special, block specials and FIFOs
must always follow the rules for plain files.
.TP
.B '0' REGTYPE
A regular file.
If the
.I size
field is non zero, then file data follows the header.
.TP
.B '\e0' AREGTYPE
For backwards compatibility with pre POSIX.1-1988
.B tar
implementations, a nul character is also recognized as marker for plain files.
It is not generated by recent
.B tar
implementations.
If the
.I size
field is non zero, then file data follows the header.
.TP
.B '1' LNKTYPE
The file is a hard link to another file.
The name of the file that the file is linked to is in the 
.I linkname
part of the header.
For
.B tar
archives written by pre POSIX.1-1988 implementations, the
.I size
field usually contains the size of the file and
needs to be ignored as no data may follow this header type.
For POSIX.1-1988 compliant archives, the
.I size
field needs to be 0.
For POSIX.1-2001 compliant archives, the
.I size
field may be non zero, indicating that file data is included in the archive.
.TP
.B '2' SYMTYPE
The file is a symbolic link to another file.
The name of the file that the file is linked to is in the 
.I linkname
part of the header.
The
.I size
field needs to be 0.
No file data may follow the header.
.TP
.B '3' CHRTYPE
A character special file.
The fields
.I devmajor
and
.I devminor
contain information that defines the device id of the file.
The meaning of the
.I size
field is unspecified by the POSIX standard.
No file data may follow the header.
.TP
.B '4' BLKTYPE
A block special file.
The fields
.I devmajor
and
.I devminor
contain information that defines the device id of the file.
The meaning of the
.I size
field is unspecified by the POSIX standard.
No file data may follow the header.
.TP
.B '5' DIRTYPE
A directory or sub directory. Old (pre POSIX.1-1988)
.B tar
implementations did use the same
.I typeflag
value as for plain files and added a slash to the end of the
.I name
field.
If the
.I size
field is non zero then it indicates the maximum size in characters
the system may allocate for this directory. If the
.I size
field is 0, then
the system shall not limit the size of the directory. On operating systems
where the disk allocation is not done on a directory base, the
.I size
field is ignored on extraction.
No file data may follow the header.
.TP
.B '6' FIFOTYPE
A named pipe.
The meaning of the size field is unspecified by the POSIX standard.
The
.I size
field must be ignored on extraction.
No file data may follow the header.
.TP
.B '7' CONTTYPE
A contiguous file.
This is a file that gives special performance attributes.
Operating systems that don't support this file type extract this file type
as plain files.
If the
.I size
field is non zero, then file data follows the header.
.TP
.B 'g' GLOBAL POSIX.1-2001 HEADER
With POSIX.1-2001 pax archives, this type defines a global extended header.
The
.I size
is always non zero and denotes the sum of the length fields in the extended
header data.
The data that follows the header is in the
.B pax extended header
format.
The extended header records in this header type affect all
following files in the archive unless they are overwritten by new values.
See
.B "EXTENDED TAR (PAX) HEADER FORMAT"
section below.
.TP
.B 'x' EXTENDED POSIX.1-2001 HEADER
With POSIX.1-2001 pax archives, this type defines an extended header.
The
.I size
is always non zero and denotes the sum of the length fields in the extended
header data.
The data that follows the header is in the
.B pax extended header
format.
The extended header records in this header type only affect the
following file in the archive.
See
.B "EXTENDED TAR (PAX) HEADER FORMAT"
section below.
.TP
.B 'A' - 'Z'
Reserved for vendor specific implementations.
.TP
.B 'A'
A Solaris ACL entry as used by the 
.B tar
implementation from Sun.
The
.I size
is always non zero and denotes the length of the data that follows the header.
.B Star
currently is not able to handle this header type.
As the
.B ACL
data used by this format dos not include the numerical user and group id's,
this format is not recommended for archival.
.TP
.B 'D'
A GNU dump directory.
This header type is not created by
.B star
and handled like a POSIX type '5' directory during an extract operation,
so the data content is ignored by
.BR star .
The
.I size
field denotes the length of the data that follows the header.
.TP
.B 'E'
A Solaris Extended Attribute File that is used to archive
.B NFSv4
type extended attributes.
The
.I size
field denotes the length of the data that follows the header.
.B Star
currently is not able to handle this header type.
.TP
.B 'I'
A
.B inode metadata
entry.
This header type is used by
.B star
to archive inode meta data only.
To archive more inode meta data than possible with a POSIX-1.1988
.B tar
header, a header with type
.B 'I'
is usually preceded by a
.B 'x'
header.
It is used with incremental backups.
The
.I size
field holds the length of the file.
No file data follows this header.
.TP
.B 'K'
A long link name.
.B Star
is able to read and write this type of header with the
.BR star ", " xstar " and " gnutar
formats.
With the
.BR xustar " and " exustar
formats,
.B star
prefers to store long link names using the POSIX.1-2001 method.
The
.I size
is always non zero and denotes the length of the long link target name
including the trailing null byte.
The link name is in the data that follows the header.
.TP
.B 'L'
A long file name.
.B Star
is able to read and write this type of header with the
.BR star ", " xstar " and " gnutar
formats.
With the
.BR xustar " and " exustar
formats,
.B star
prefers to store long file names using the POSIX.1-2001 method.
The
.I size
is always non zero and denotes the length of the long file name including
the trailing null byte. The file name is in the data that follows the header.
.TP
.B 'M'
A multi volume continuation entry.
It is used by
.B star
to tell the extraction program via the 
.I size
field when the next regular archive header will follow.
This allows one to start extracting multi volume archives with a volume
number greater than one.
It is used by GNU tar to verify multi volume continuation volumes.
Other fields in the GNU multi volume continuation header are a result of
a GNU tar miss conception and cannot be used in a reliable tar implementation.
If the
.I size
field is non zero the data following the header is skipped by
.B star
if the volume that starts with it is mounted as the first volume.
This header is ignored if the volume that starts with it is mounted
as continuation volume. Instead, the following data is used as the continuation
of the file that is currently extracted.
.TP
.B 'N'
An outdated linktype used by old GNU tar versions to store long file names.
This type is unsupported by
.BR star .
.TP
.B 'S'
A sparse file.
This header type is used by
.B star
and
.BR "GNU tar" .
A sparse header is used instead of a plain file header to denote a sparse
file that follows. Directly after the header, a list of sparse hole descriptors
follows followed by the compacted file data.
With 
.I star
formats, the
.I size
field holds a size that represents the sum of the sparse hole descriptors
plus the size of the compacted file data. This allows other
.B tar
implementations to correctly skip to the next
.BR "tar header" .
With GNU tar, up to 4 sparse hole descriptors fit into the sparse header.
Additional hole descriptors are not needed if the file has less than 4 holes.
With GNU tar, the size field breaks general
.I tar
header rules in case more than 4 sparse hole descriptors are used
and is meaningless because the size of the additional sparse hole
descriptors used by GNU tar does not count and cannot be determined before
parsing all sparse hole descriptors.
.TP
.B 'V'
A volume header.
The 
.I name
field is is used to hold the volume name.
.B Star 
uses the
.I atime
field to hold the volume number in case there is no POSIX.1-2001 extended header.
This header type is used by
.B star
and
.BR "GNU tar" .
If the
.I size
field is non zero the data following the header is skipped by
.BR star .
.TP
.B 'X'
A vendor unique variant of the POSIX.1-2001 extended header type.
It has been implemented by Sun many years before the POSIX.1-2001
standard has been approved and the POSIX.1-2001 tar extensions are
based on this Sun tar extension.
See also the
.I typeflag
\&'x' header type.
.B Star
is able to read and write this type of header.
.PP
The
.I devmajor
and
.I devminor
fields contain the numerical 
.B major()
and
.B minor()
information that defines the device id of the file from the member
.B st_rdev
in
.BR "struct stat" .
These fields may use a
.B base 256
encoding.
.br
.ne 10
.SH "EXTENDED TAR (PAX) HEADER STRUCTURE"
.PP
.TS
tab (/);
lb  cb
l  ci .
Block type/Description

Ustar Header [typeflag='g']/Global Extended Header
Global Extended Data/
Ustar Header [typeflag='x']/Extended Header
Extended Data/
Ustar header [typeflag='0']/File with Extended Header
Data for File #1/
Ustar header [typeflag='0']/File without Extended Header
Data for File #2/
Block of binary zeroes/First EOF Block
Block of binary zeroes/Second EOF Block
.TE

.ne 10
.SH "EXTENDED TAR (PAX) HEADER FORMAT"
.PP
The data block that follows a
.B tar
archive header with
.I typeflag
.B "\&'g'
or
.B "\&'x'
contains one or more records in the following format:
.PP
.RS
\&"%d %s=%s\en",
.IR <length> ", " <keyword> ", " <value>
.RE
.PP
Each record starts with a a decimal length field. The length includes
the total size of a record including the length field itself and the trailing
new line.
.PP
The
.I keyword
may not include an equal sign.
All keywords beginning with lower case letters and digits are reserved for
future use by the POSIX standard.
.PP
If the value field is of zero length, it deletes any header field of the same
name that is in effect from the same extended header or from a previous global
header.
.PP
Null characters do not delimit any value. The data used for
.I value 
is only limited by its
implicit length.
.SH "EXTENDED TAR (PAX) HEADER KEYWORDS"
POSIX.1-2001 extended
.B pax
header keywords. All numerical values are represented as decimal strings.
All texts are represented as UTF-8 or an unspecified binary format (see
.B hdrcharset
keyword) that is expected to be understood by the receiving system:
.TP
.B atime
The time from
.B st_atime
in sub second granularity. 
.B Star
currently supports a nanosecond granularity.
.TP
.B charset
The name of the character set used to encode the data in the following file(s).
.RS
.PP
The following values are supported for
.BR charset :
.TP 25
.B "ISO-IR 646 1990"
ISO/IEC 646:1990
.TP
.B "ISO-IR 8859 1 1998"
ISO/IEC 8859-1:1998
.TP
.B "ISO-IR 8859 2 1998"
ISO/IEC 8859-2:1998
.TP
.B "ISO-IR 8859 3 1998"
ISO/IEC 8859-3:1998
.TP
.B "ISO-IR 8859 4 1998"
ISO/IEC 8859-4:1998
.TP
.B "ISO-IR 8859 5 1998"
ISO/IEC 8859-5:1998
.TP
.B "ISO-IR 8859 6 1998"
ISO/IEC 8859-6:1998
.TP
.B "ISO-IR 8859 7 1998"
ISO/IEC 8859-7:1998
.TP
.B "ISO-IR 8859 8 1998"
ISO/IEC 8859-8:1998
.TP
.B "ISO-IR 8859 9 1998"
ISO/IEC 8859-9:1998
.TP
.B "ISO-IR 8859 10 1998"
ISO/IEC 8859-10:1998
.TP
.B "ISO-IR 8859 11 1998"
ISO/IEC 8859-11:1998
.TP
.B "ISO-IR 8859 12 1998"
ISO/IEC 8859-12:1998
.TP
.B "ISO-IR 8859 13 1998"
ISO/IEC 8859-13:1998
.TP
.B "ISO-IR 8859 14 1998"
ISO/IEC 8859-14:1998
.TP
.B "ISO-IR 8859 15 1998"
ISO/IEC 8859-15:1998
.TP
.B "ISO-IR 10646 2000"
ISO/IEC 10646:2000
.TP
.B "ISO-IR 10646 2000 UTF-8"
ISO/IEC 10646, UTF-8 encoding
.TP
.B BINARY
None
.PP
This keyword is currently ignored by
.BR star .
.RE
.TP
.B comment
Any number of characters that  should be treated as comment.
.B Star
ignores the comment as documented by the POSIX standard.
.TP
.B ctime
The time from
.B st_ctime
in sub second granularity. 
.B Star
currently supports a nanosecond granularity.
.TP
.B gid
The group ID of the group that owns the file.
The argument is a decimal number.
This field is used if the group ID of a file is greater than 2097151 (octal 7777777).
.TP
.B gname
The group name keyword for the following file(s) is created if the group name does not
fit into 32 characters or cannot be expressed in 7-Bit ASCII.
It is coded in UTF-8
or (if the 
.B hdrcharset
keyword is present) coded to fit the charset value.
.TP
.B hdrcharset
The name of the character set used to encode the data for the
.BR gname ,
.BR linkpath ,
.BR path " and"
.B uname
fields in the POSIX.1-2001 extended header records
and for the
.BR gname ,
.B uname
and
.B path
parts in the vendor specific extended header records
.BR SCHILY.acl.ace ,
.BR SCHILY.acl.access ,
.B SCHILY.acl.default
and
.BR SCHILY.dir .
.RS
.PP
The following values are supported for
.BR hdrcharset :
.TP 25
.B "ISO-IR 10646 2000 UTF-8"
ISO/IEC 10646, UTF-8 encoding
.TP
.B BINARY
None
.PP
If the binary encoding is selected, the encoding is the same as used
by the creating system and it is assumed that the receiving system is
able to use the values in that encoding.
.RE
.TP
.B linkpath
The
.I linkpath
keyword is created if the linkpath
is longer than 100 characters or cannot be expressed in 7-Bit ASCII.
It is coded in UTF-8
or (if the 
.B hdrcharset
keyword is present) coded to fit the charset value.
.TP
.B mtime
The time from
.B st_mtime
in sub second granularity. 
.B Star
currently supports a nanosecond granularity.
.TP
.B path
The 
.I path
keyword is created if the path
does not fit into 100 characters + 155 characters prefix
or cannot be expressed in 7-Bit ASCII.
It is coded in UTF-8
or (if the 
.B hdrcharset
keyword is present) coded to fit the charset value.
.TP
.BI realtime. any
The keywords prefixed by
.B realtime.
are reserved for future standardization. 
.TP
.BI security. any
The keywords prefixed by
.B security.
are reserved for future standardization. 
.TP
.B size
The size of the file as decimal number if the file size is greater than 8589934591 (octal 77777777777). 
The
.B size
keyword may not refer to the real file size but is related to the size if the file in the archive.
See also
.B SCHILY.realsize
for more information.
.TP
.B uid
The uid ID of the group that owns the file.
The argument is a decimal number.
This field is used if the uid ID of a file is greater than 2097151 (octal 7777777).
.TP
.B uname
The user name keyword for the following file(s) is created if the user name does not
fit into 32 characters or cannot be expressed in 7-Bit ASCII.
It is coded in UTF-8
or (if the 
.B hdrcharset
keyword is present) coded to fit the charset value.
.TP
.IR VENDOR .keyword
Any keyword that starts with a vendor name in capital letters is reserved 
for vendor specific extensions
by the standard.
.B Star
uses a lot of these vendor specific extension. See below for more information.
.SH "SCHILY PAX EXTENSION KEYWORDS"
.B Star
uses own vendor specific extensions. The
.B SCHILY
vendor specific extended
.B pax
header keywords are:
.TP
.B SCHILY.acl.ace
The NFSv4 ACL for a file.
.sp
Since no official backup format for the NFSv4 ACL standard
has been defined,
.B star
uses the vendor defined attributes
.B SCHILY.acl.ace
for storing the
.B NFSv4 ACL
entries.
.sp
Previous versions of
.B star
used a format for the ACL text that is
is the format created by the function
.BR acl_totext ()
from
.B libsec
on Solaris, using the call:
.sp
.nf
.B acl_totext(aclp, \e
.B "    ACL_COMPACT_FMT | ACL_APPEND_ID | ACL_SID_FMT);"
.fi
.sp
The flags have the following meaning:
.RS
.br
.ne 4
.TP
.B ACL_COMPACT_FMT
Create the compact version of the ACL text representation.
.br
.ne 4
.TP
.B ACL_APPEND_ID
Append
.B uid
or
.B gid
for additional user or group entries.
.br
.ne 4
.TP
.B ACL_SID_FMT
Use the
.B usersid
or
.B groupsid
format for entries related to an ephemeral
.B uid
or
.BR gid .
The raw
.B sid
format will only be used when the "id" cannot be
resolved to a windows name.
.PP
.sp
.ne 12
This is an example of the format used for
.B SCHILY.acl.ace
(a space has been inserted after the equal sign and lines are broken
[marked with '\e' ] for readability):
.sp
.nf
SCHILY.acl.ace= user:lisa:rwx-----------:-------:allow:502,\ \e
            group:toolies:rwx-----------:-------:allow:102,\ \e
                   owner@:--x-----------:-------:deny,\ \ \e
                   owner@:rw-p---A-W-Co-:-------:allow,\ \e
                   group@:-wxp----------:-------:deny,\ \ \e
                   group@:r-------------:-------:allow,\ \e
                everyone@:-wxp---A-W-Co-:-------:deny,\ \ \e
                everyone@:r-----a-R-c--s:-------:allow
.fi
.PP
The numerical user and group identifiers are essential when restoring a
system completely from a backup, as initially the name-to-identifier 
mappings may not be available, and then file ownership restoration 
would not work.
.PP
Newer versions of star use a highly compact variant of the format
mentioned above that avoids the
\&'-' characters in the text.
The example below is using lines broken the same way as in
the previous example.
.sp
.nf
SCHILY.acl.ace= user:lisa:rwx::allow:502,\ \e
            group:toolies:rwx::allow:102,\ \e
                   owner@:x::deny,\ \ \ \ \ \ \ \ \e
                   owner@:rwpAWCo::allow,\ \e
                   group@:wxp::deny,\ \ \ \ \ \ \e
                   group@:r::allow,\ \ \ \ \ \ \ \e
                everyone@:wxpAWCo::deny,\ \ \e
                everyone@:raRcs::allow
.fi
.PP
This highly compact format is understood by
.B acl_fromtext()
in
.B libsec
from Solaris and by the corresponding code from FreeBSD.
It is created by removing the
.B '-'
characters from the normal compact format.
.PP
The advantage of th highly compact format is that it typically avoids the
need to make the extended header data larger than 512 bytes.
.PP
In addition to the documented entry formats, a compatible implementation
needs to be able to understand the long
.B ace
format, if it appears in extended tar headers.
The long format for the ACL text is the format created by the function
.BR acl_totext ()
from
.B libsec
on Solaris, using the call:
.sp
.nf
.B acl_totext(aclp, ACL_APPEND_ID | ACL_SID_FMT);
.fi
.sp
.PP
As the archive format that is used for backing up access control lists is
compatible with the
.B pax
archive format, archives created that way can be restored by
.B star
or a POSIX.1-2001 compliant
.BR pax .
Note that programs that do not implement compatibility to the
.B star
extensions will ignore the ACL information.
.RE
.sp
.TP
.B SCHILY.acl.access
The withdrawn POSIX draft ACL for a file.
.sp
Since no official backup format for the withdrawn POSIX draft
access control lists has been defined,
.B star
uses the vendor defined attributes
.B SCHILY.acl.access
and
.B SCHILY.acl.default
for storing the
.B ACL 
and 
.B "Default ACL"
of a file, respectively.
The access control lists are stored in the short text form as defined in
the withdrawn
.BR "POSIX 1003.1e draft standard 17" .
.sp
Note that the POSIX 1003.1e draft has been withdrawn in 1997 but some 
operating systems still support it with some filesystems.
.sp
To each named user 
.B ACL
entry a fourth colon separated field, containing the
.I "user identifier (UID)"
of the associated user, is appended.
To each named group entry a fourth colon separated field containing the
.I "group identifier (GID)"
of the associated group is appended.
(POSIX 1003.1e draft standard 17 allows one to add fields to ACL entries.)
.sp
If the
.B user name
or
.B group name
field is numeric because the related user has no entry in the
.BR passwd / "group database"
at the time the archive is created,
the additional numeric field may be omitted.
.sp
.ne 7
This is an example of the format used for
.B SCHILY.acl.access
(a space has been inserted after the equal sign and lines are broken
[marked with '\e' ] for readability, additional fields in bold):
.sp
.nf
SCHILY.acl.access= user::rwx,user:lisa:r\-x:\fB502\fP,\ \e
                   group::r\-x,group:toolies:rwx:\fB102\fP,\ \e
                   mask::rwx,other::r\-\-x
.fi
.sp
If and only if the
.B user ID 502
and
.B group ID 102
have no passwd/group entry, our example acl entry looks this way:
.sp
.nf
SCHILY.acl.access= user::rwx,user:502:r\-x,\ \e
                   group::r\-x,group:102:rwx:,\ \e
                   mask::rwx,other::r\-\-x
.fi
.sp
The added numerical user and group identifiers are essential when
restoring a system completely from a backup,
as initially the name-to-identifier mappings may not be available,
and then file ownership restoration would not work.
.sp
When the archive is unpacked and the
.B ACL 
entries for the files are restored, first the additional numeric fields
are removed and an attempt is made to restore the resulting
.B ACL 
data.
If that fails, the numeric fields are extracted and the related
.B user name
and
.B group name
fields are replaced by the numeric fields, before the
.B ACL 
restore is retried.
.sp
As the archive format that is used for backing up access control lists is compatible
with the
.B pax
archive format, archives created that way can be restored by
.B star
or a POSIX.1-2001 compliant
.BR pax .
Note that programs other than
.B star
will ignore the ACL information.
.TP
.B SCHILY.acl.default
The default ACL for a file. See 
.B SCHILY.acl.access
for more information.
.sp
This is an example of the format used for
.B SCHILY.acl.default
(a space has been inserted after the equal sign and lines are broken
[marked with '\e' ] for readability, additional fields in bold):
.sp
.nf
SCHILY.acl.default= user::rwx,user:lisa:r-x:\fB502\fP,\ \e
                    group::r-x,mask::r-x,other::r-x
.fi
.br
.ne 7
.TP
.B SCHILY.acl.type
The ACL type used for coding access control lists.
.sp
.ne 5
The following ACL types are possible:
.RS
.br
.ne 5
.TP
.B "POSIX\ draft"
ACLs as defined in the withdrawn
.BR "POSIX 1003.1e draft standard 17" .
.br
.ne 5
.TP
.B NFSv4
ACLs as used by
.BR NFSv4 ,
.B NTFS
and
.BR ZFS .
.LP
Note that the
.B SCHILY.acl.type
keyword is currently not generated by
.BR star .
Star however accepts this keyword if it appears in extended tar headers.
The ACL type is determined from the existence of the keyword type that holds
the ACL text.
.RE
.TP
.B SCHILY.ddev
The device ids for names used is the
.B SCHILY.dir
dump directory list from
.B st_dev
of the file as decimal number.
The
.B SCHILY.ddev
keyword is followed by a space separated list of device id numbers. Each corresponds
exactly to a name in the list found in
.BR SCHILY.dir .
If a specific device id number is repeated, a comma (,) without a following space may be
use to denote that the current device id number is identical to the previous number.
This keyword is used in
.B dump
mode.
This keyword is not yet implemented.
It will be implemented in case that
.B star
will support incremental dumps that span more than one filesystem.
.sp
The value is a signed int.
An implementation should be able to handle at least 64 bit values.
Note that the value is signed because POSIX does not specify
more than the type should be an int.
.TP
.B SCHILY.dev
The device id from
.B st_dev
of the file as decimal number.
This keyword is used in
.B dump
mode.
.sp
The value is a signed int.
An implementation should be able to handle at least 64 bit values.
Note that the value is signed because POSIX does not specify
more than the type should be an int.
.TP
.B SCHILY.devmajor
The device major number of the file (from
.BR st_rdev )
if it is a character or block special file.
The argument is a decimal number.
This field is used if the device major of the file is greater than 2097151 (octal 7777777).
.sp
The value is a signed int.
An implementation should be able to handle at least 64 bit values.
Note that the value is signed because POSIX does not specify
more than the type should be an int.
.TP
.B SCHILY.devminor
The device minor number of the file (from
.BR st_rdev )
if it is a character or block special file.
The argument is a decimal number.
This field is used if the device minor of the file is greater than 2097151 (octal 7777777).
.sp
The value is a signed int.
An implementation should be able to handle at least 64 bit values.
Note that the value is signed because POSIX does not specify
more than the type should be an int.
.TP
.B SCHILY.devminorbits
The number of minorbits used in the device id from
.B st_dev
as decimal number.
.sp
The value is mainly needed for SunOS where the number of minor bits in st_dev
depends on whether a program is run in 32 or 64 bit mode. There is no support
for platforms that do not have the minor part of the device id in a contiguous
set of bits (like e.g. FreeBSD).
.TP
.B SCHILY.dino
The inode numbers for names used is the
.B SCHILY.dir
dump directory list from
.B st_ino
of the file as decimal number.
The
.B SCHILY.dino
keyword is followed by a space separated list of inode numbers. Each corresponds
exactly to a name in the list found in
.BR SCHILY.dir .
This keyword is used in
.B dump
mode.
.sp
The values are unsigned int.
An implementation should be able to handle at least 64 bit unsigned values.
.TP
.B SCHILY.dir
A list of filenames (the content) for the current directory.
The names are coded in UTF-8.
Each file name is prefixed by a single character that is used as a flag.
Each file name is limited by a null character.
The null character is directly followed
by he flag character for the next file name in case the list is not terminated
by the current file name.
The flag character must not be a null character.
By default, a ^A (octal 001) is used.
The following flags are defined:
.RS
.TP 10
.B \e000
This is the list terminator character - the second null byte, see below.
.TP
.BR \e001 " (" ^A )
The default flag that is used in case the 
.B "dump dir"
features have not been active or in case that the file type is unknown.
.TP
.BR \e002 " (" ^B )
The related file is a
.B FIFO
special (named pipe).
.TP
.BR \e003 " (" ^C )
The related file is a
.BR "character special" .
.TP
.BR \e004 " (" ^D )
Reserved, used e.g. by XENIX
.BR "multiplexed character special" .
.TP
.BR \e005 " (" ^E )
The related file is a
.BR directory .
.TP
.BR \e006 " (" ^F )
Reserved, used e.g. by XENIX
.BR "named file" .
.TP
.BR \e007 " (" ^G )
The related file is a
.BR "block special" .
.TP
.BR \e010 " (" ^H )
Reserved, used e.g. by XENIX
.BR "multiplexed block special" .
.TP
.BR \e011 " (" ^I )
The related file is a
.BR "regular file" .
.TP
.BR \e012 " (" ^J )
The related file is a
.BR "contiguous file" .
.TP
.BR \e013 " (" ^K )
The related file is a
.BR "symbolic link" .
.TP
.BR \e014 " (" ^L )
Reserved, used e.g. by Solaris
.BR "shadow inode" .
.TP
.BR \e015 " (" ^M )
The related file is a
.BR socket .
.TP
.BR \e016 " (" ^N )
The related file is a Solaris
.BR DOOR .
.TP
.BR \e017 " (" ^O )
The related file is a BSD
.BR "whiteout entry" .
.TP
.BR \e020 " (" ^P )
Reserved, used e.g. by UNOS
.BR eventcount .
.TP
.B Y
A non directory file that is in the current (incremental) dump.
.TP
.B N
A non directory file that is not in the current (incremental) dump.
.TP
.B D
A directory that is in the current (incremental) dump.
.TP
.B d
A directory that is not in the current (incremental) dump.
.PP
The list is terminated by two successive null bytes.
The first is the null byte for the last file name.
The second null byte is at the position where a flag character
would be expected, it acts ad a list terminator. The length
tag for the 
.B SCHILY.dir
data includes both null bytes.
.PP
If a dump mode has been selected that writes
compact complete directory information to the beginning of 
the archive, the flag character may contain values different
from ^A.
.B Star
implementations at least up to
.B star-1.5.1
do not use the feature to tag entries and use the default
entry \e001 (^A) for all files.
Tar implementations that like to read archives that use the
.B SCHILY.dir
keyword, shall not rely on values other than \e000 (^@) or \e001 (^A).
.PP
In 2016, with
.B star-1.5.3
the values from \e002 to \e020 have been introduced as a result of a
.B libfind
update that uses struct dirent member
.B d_type
where available.
.PP
This keyword is used in
.B dump
mode.
.RE
.TP
.B SCHILY.fflags
A textual version of the BSD or Linux extended file flags.
.sp
The following flags are defined by star, the bold names are the names
that are generated and the other names are accepted on input as well:
.RS
.TP 15
.B arch
set the
.B archived
flag (super-user only).
.TP
archived
Alias for
.BR arch .
.TP
.B compressed
set the
.B compressed
flag (Mac OS only).
.TP
ucompressed
Alias for
.BR compressed .
.TP
.B hidden
Set the
.B file is hidden
flag.
.TP
uhidden
Alias for
.BR hidden .
.TP
.B nodump
set the nodump flag (owner or super-user).
.TP
.B offline
Set the
.B file is offline
flag.
.TP
uoffline
Alias for
.BR offline .
.TP
.B opaque
set the opaque flag (owner or super-user).
.TP
.B rdonly
Set the
.B readonly
flag.
.TP
urdonly
Alias for
.BR rdonly .
.TP
readonly
Alias for
.BR rdonly .
.TP
.B reparse
Set the
.B reparse
flag.
.TP
ureparse
Alias for
.BR reparse .
.TP
.B sappnd
set the system append-only flag (super-user only).
.TP
sappend
Alias for
.BR sappnd .
.TP
.B schg
set the system immutable flag (super-user only).
.TP
schange
Alias for
.BR schg .
.TP
simmutable
Alias for
.BR schg .
.TP
.B sparse
Set the
.B sparse
flag.
.TP
usparse
Alias for
.BR sparse .
.TP
.B sunlnk
set the system undeletable flag (super-user only).
.TP
sunlink
Alias for
.BR sunlnk .
.TP
.B system
Set the
.B system
flag.
.TP
usystem
Alias for
.BR system .
.TP
.B uappnd
set the user append-only flag (owner or super-user).
.TP
uappend
Alias for
.BR uappnd .
.TP
.B uchg
set the user immutable flag (owner or super-user).
.TP
uchange
Alias for
.BR uchg .
.TP
uimmutable
Alias for
.BR uchg .
.TP
.B uunlnk
set the user undeletable flag (owner or super-user).
.TP
uunlink
Alias for
.BR uunlnk .
.br
.ne 4
.LP
The following flags are only available on Linux:
.TP 15
.B compress
Set the Linux
.B compress
flag (owner or super-user).
.TP
.B dirsync
Set the Linux
.B dirsync
flag (owner or super-user)
that causes synchronous writes for directories.
.TP
.B journal-data
Set the Linux
.B journal data
flag (super-user only).
.TP
.B noatime
Set the Linux
.B no access time
flag (owner or super-user).
.TP
.B nocow
Set the Linux
.B no copy on write
flag (owner or super-user).
.TP
.B notail
Set the Linux
.B no tail merging
flag (owner or super-user).
.TP
.B projinherit
Set the Linux
.B project inherit
flag (owner or super-user).
.TP
.B secdel
Set the Linux
.B secure deletion
(purge before delete) flag (owner or super-user).
.TP
.B sync
Set the Linux
.B sync
flag (owner or super-user).
.TP
.B topdir
Set the Linux
.B top of directory hierarchies
flag (owner or super-user).
.TP
.B undel
Set the Linux
.B "allow unrm"
flag (owner or super-user).
.RE
.TP
.B SCHILY.filetype
A textual version of the real file type of the file.
The following names are used:
.RS
.TP 24
.B unallocated
An unknown file type that may be a result of a
.BR unlink (2)
operation.
This should never happen.
.TP
.B regular
A regular file.
.TP
.B contiguous
A contiguous file. On operating systems or file systems that don't support
this file type, it is handled like a regular file.
.TP
.B symlink
A symbolic link to any file type.
.TP
.B directory
A directory.
.TP
.B "character special"
A character special file.
.TP
.B "block special"
A block special file.
.TP
.B fifo
A named pipe.
.TP
.B socket
A UNIX domain socket.
.TP
.B "mpx character special"
A multiplexed character special file.
.TP
.B "mpx block special"
A multiplexed block special file.
.TP
.B "XENIX nsem"
A XENIX named semaphore.
.TP
.B "XENIX nshd"
XENIX shared data.
.TP
.B door
A Solaris door.
.TP
.B eventcount
A UNOS event count.
.TP
.B whiteout
A BSD whiteout directory entry.
.TP
.B sparse
A sparse regular file.
.TP
.B volheader
A volume header.
.TP
.B "unknown/bad"
Any other unknown file type.
This should never happen.

.RE
.TP
.B SCHILY.fsdevmajor
The device major number of the file (from
.BR st_dev ).
This keyword is used in
.B dump
mode.
The argument is a decimal number.
.sp
The value is a signed int.
An implementation should be able to handle at least 64 bit values.
Note that the value is signed because POSIX does not specify
more than the type should be an int.
.TP
.B SCHILY.fsdevminor
The device minor number of the file (from
.BR st_dev ).
This keyword is used in
.B dump
mode.
The argument is a decimal number.
.sp
The value is a signed int.
An implementation should be able to handle at least 64 bit values.
Note that the value is signed because POSIX does not specify
more than the type should be an int.
.TP
.B SCHILY.ino
The inode number from
.B st_ino
of the file as decimal number.
This keyword is used in
.B dump
mode.
.sp
The value is an unsigned int.
An implementation should be able to handle at least 64 bit unsigned values.
.TP
.B SCHILY.nlink
The link count of the file as decimal number.
This keyword is used in
.B dump
mode.
.sp
The value is an unsigned int.
An implementation should be able to handle at least 32 bit unsigned values.
.TP
.B SCHILY.offset
The 
.B offset
value for a multi volume continuation header.
This keyword is used with multi volume continuation headers.
Multi volume continuation headers are used to allow to start reading
a multi volume archive past the first volume.
.sp
.B SCHILY.offset
specifies the byte offset within a file that was split across volumes
as a result of a multi volume media change operation.
.sp
The value is an unsigned int.
An implementation should be able to handle at least 64 bit unsigned values.
.TP
.B SCHILY.realsize
The real size of the file as decimal number.
This keyword is used if the real size of the file differs from the
visible size of the file in the archive.
The real file size differs from the size in the archive if the
file type is
.B sparse
or if the file is a continuation file on a multi volume archive.
In case the
.B SCHILY.realsize
keyword is needed, it must be past any 
.B size
keyword in case a
.B size
keyword is also present.
.sp
As sparse files allocate less space on tape than a regular file and as a
continued file that started on a previous volume only holds parts of the
file, the
.B SCHILY.realsize
keyword holds a bigger number than the
.B size
keyword.
.sp
The value is an unsigned int.
An implementation should be able to handle at least 64 bit unsigned values.
.TP
.B SCHILY.tarfiletype
The following additional file types are used in
.BR SCHILY.tarfiletype :
.RS
.TP
.B hardlink
A hard link to any file type.
.TP
.B dumpdir
A directory with dump entries
.TP
.B "multivol continuation"
A multi volume continuation for any file type.
.TP
.B meta
A meta entry (inode meta data only) for any file type.
.RE
.TP
.BI SCHILY.xattr. attr
A POSIX.1-2001 coded version of the Linux extended file attributes.
Linux extended file attributes are name/value pairs. Every
attribute 
.I name
results in a
.BI SCHILY.xattr. name
tag and the value of the extended attribute is used as the value of the
POSIX.1-2001 header tag.
Note that this way of coding is not portable across platforms,
even though it is compatible with the implementation on
.BR "Mac OS X" .
A version for BSD may be created but
.B NFSv4
includes far more
features with extended attribute files than Linux does.
.sp
A future version of
.B star
will implement a similar method as the 
.B tar
program on Solaris currently uses. When this implementation is ready,
the
.BI SCHILY.xattr. name
feature may be removed in favor of a truly portable implementation
that supports Solaris also.

.SH "SCHILY 'G'LOBAL PAX EXTENSION KEYWORDS"
The following 
.B star
vendor unique extensions may only appear in
.B "'g'lobal"
extended
.B pax
headers:
.TP
.B SCHILY.archtype
The textual version of the archive type used.
The textual values used for
.B SCHILY.archtype
are the same names that are used in the 
.B star
command line options to set up a specific archive type.
.sp
The following values may currently appear in a global extended header:
.RS
.TP 15
.B xustar
\&'xstar' format without "tar" signature at header offset 508.
.TP
.B exustar
\&'xustar' format variant that always includes x-headers and g-headers.
.LP
A complete tar implementation must be prepared to handle all archives names
as documented in
.BR star (1).
.LP
In order to allow archive type recognition from this keyword,
the minimum tape block size must be 2x512 bytes (1024 bytes)
and the 
.B SCHILY.archtype
keyword needs to be in the first 512 bytes of the content of the
first
.B "'g'lobal pax"
header. Then the first tape block may be scanned to recognize
the archive type.
.RE
.TP
.B SCHILY.release
The textual version of the
.B star
version string and the platform name where this
.B star
has been compiled.
The same text appears when calling
.IR "star -version" .
.sp
Other implementations may use a version string that does not start with
the text
.BR star .
.TP
.B SCHILY.volhdr.blockoff
This keyword is used for multi volume archives.
It represents the offset within the whole archive expressed
in 512 byte units.
.sp
The value is an unsigned int with a valid range between 1 and
infinity. An implementation should be able to handle at least 64 bit
unsigned values.
.TP
.B SCHILY.volhdr.blocksize
The tape blocksize expressed in 512 byte units that was used
when writing the archive.
.sp
The value is an unsigned int with a valid range between 1 and
infinity. An implementation should be able to handle at least 31 bit
unsigned values.
.TP
.B SCHILY.volhdr.cwd
This keyword is used in dump mode.
It is only emitted in case the
.B "fs\-name="
option of star was used to overwrite the
.B SCHILY.volhdr.filesys
value.
If
.B SCHILY.volhdr.cwd
is present, it contains the real backup working directory.
.sp
Overwriting
.B SCHILY.volhdr.filesys
is needed when backups are run on file system snapshots rather
than on the real file system.
.TP
.B SCHILY.volhdr.device
This keyword is used in dump mode.
It represents the name of the device that holds the file system
data. For disk based file systems, this is the device name of the
mounted device.
.sp
This keyword is optional. It helps to correctly identify the
file system from which this dump has been made.
.TP
.B SCHILY.volhdr.dumpdate
This keyword is used in dump mode.
It represents the time the current dump did start.
.TP
.B SCHILY.volhdr.dumplevel
This keyword is used in dump mode.
It represents the level of the current dump.
Dump levels are small numbers, the lowest possible number is 0.
Dump level 0 represents a full backup.
Dump level 1 represents a backup that contains all changes that
did occur since the last level 0 dump.
Dump level 2 represents a backup that contains all changes that
did occur since the last level 1 dump.
.B Star
does not specify a maximum allowed dump level but you should try
to keep the numbers less than 100.
.sp
The value is an unsigned int with a valid range between 0 and at least 100.
.TP
.B SCHILY.volhdr.dumptype
This keyword is used in dump mode.
If the dump is a complete dump of a file system
(i.e. no files are excluded via command line), then the argument
is the text
.BR full ,
else the argument is the text
.BR partial .
.TP
.B SCHILY.volhdr.filesys
This keyword is used in dump mode.
It represents the top level directory for the file system from
which this dump has been made.
If the dump represents a dump that has an associated level, then
the this directory needs to be identical to the root directory
of this file system which is the mount point.
.TP
.B SCHILY.volhdr.hostname
This keyword is used in dump mode.
The value is retrieved from
.B gethostname(3)
or
.BR uname(2) .
.TP
.B SCHILY.volhdr.label
The textual volume label.
The volume label must be identical within a set of
multi volume archives.
.TP
.B SCHILY.volhdr.refdate
This keyword is used in dump mode if the current dump is an
incremental dump with a level > 0.
It represents the time the related dump did start.
.TP
.B SCHILY.volhdr.reflevel
This keyword is used in dump mode if the current dump is an
incremental dump with a level > 0.
It represents the level of the related dump.
The related dump is the last dump with a level that is lower
that the level of this dump.
If a dump with the level of the current dump \-1 exists, then
this is the related dump level. Otherwise, the dump level is
decremented until a valid dump level could be found in the
dump database.
.sp
The value is an unsigned int with a valid range between 0 and at least 100.
.TP
.B SCHILY.volhdr.tapesize
This keyword is used for multi volume archives and may be used
to verify the volume size on read back.
It represents the tape size expressed in 512 byte units.
This keyword is set in multi volume mode if the size of the tape
was not autodetected but set from a command line option.
.sp
The value is an unsigned int with a valid range between 1 and
infinity. An implementation should be able to handle at least 64 bit
unsigned values.
.TP
.B SCHILY.volhdr.volume
This keyword is used for multi volume archives.
It represents the volume number within a volume set.
The number used for the first volume is 1.
.sp
The value is an unsigned int with a valid range between 1 and
infinity. An implementation should be able to handle at least 31 bit
unsigned values.
.SH "MULTI VOLUME ARCHIVE HANDLING"
.PP
Multi volume archives always use volume headers. Starting with the second
volume, there is a multi volume header that helps to skip the rest of the
file that was split at the end of the previous volume.
.LP
.B Star
is able to work with arbitrary unknown volume sizes by detecting the end of
the current media via a
.BR write ()
call that returns
.BR 0 .
A fixed media size is used, when the option
.BI tsize= #
has been specified.
.LP
Since
.B star
uses a
.B fifo
for optimizing the I/O,
except when called with the option
.BR \-no\-fifo ,
it is not possible to know the name of the file that is split at a volume limit
nor to know the offset in that file.
Unless
.B POSIX.1-2001
extensions are used,
.B star 
does not verify whether a follow up volume is the right follow up volume.
For this reason, it is recommended to create multi volume archives only 
with archive formats that support
.B POSIX.1-2001 
extensions.
.LP
The following 
.B POSIX.1-2001 
extensions are used together with multi volume archives:
.TP
.B SCHILY.volhdr.label
the volume lavel is used to help to identify a set of volumes.
.TP
.B SCHILY.volhdr.dumpdate
The start of the dump with nanosecond precision is used to identify
the correct follow up volume.
.TP
.B SCHILY.volhdr.volno
The volume number counts starting with 1 and is used to identify
the correct follow up volume.
.TP
.B SCHILY.volhdr.blockoff
The number of blocks read with all previous volumes.
.TP
.B SCHILY.volhdr.tapesize
The tape size in case that the
.BI tsize= #
option was used.

.SH "SEE ALSO"
.BR spax (1), 
.BR suntar (1), 
.BR scpio (1), 
.BR tar (1), 
.BR cpio (1), 
.BR pax (1), 
.BR star_sym (1),
.BR tartest (1),
.BR star (1)
.\" .SH NOTES

.SH BUGS
.PP
None currently known.
.PP
Mail bugs and suggestions to
.B schilytools@mlists.in-berlin.de
or open a ticket at
.BR https://codeberg.org/schilytools/schilytools/issues .
.PP
The mailing list archive may be found at:
.PP
.nf
.BR https://mlists.in-berlin.de/mailman/listinfo/schilytools-mlists.in-berlin.de .
.fi

.SH HISTORY
A
.B tar
command appeared in Seventh Edition Unix, which was released in
January, 1979. It replaced the
.B tp
program from Fourth Edition Unix which replaced the
.B tap
program from First Edition Unix. 
.LP
.B Star
was first created in 1982 to extract tapes on a UNIX clone
.RB ( UNOS )
that had no
.B tar
command.
In 1985 the first fully functional version has been released as 
.B mtar.
.PP
When the old 
.B star 
format extensions have been introduced in 1985, it was renamed to 
.B star
(Schily tar).
In 1994, Posix 1003.1\-1988 extensions were added and 
.B star 
was renamed to 
.B star
(Standard tar).

.SH AUTHOR
J\*org Schilling and the schilytools project authors.
