#ident "@(#)Makefile	1.7 17/05/22 "
###########################################################################
# Sample makefile for sub-makes in one directory
###########################################################################
SRCROOT=	../../../..
RULESDIR=	RULES
include		$(SRCROOT)/$(RULESDIR)/rules.top
###########################################################################

MK_FILES=	sccs.mk admin.mk comb.mk delta.mk get.mk help.mk \
		prs.mk prt.mk rmchg.mk sccsdiff.mk unget.mk val.mk vc.mk what.mk \
		sccscvt.mk sccslog.mk rcs2sccs.mk bdiff.mk diff.mk diffh.mk

XMK_FILE=	Makefile.man

###########################################################################
include		$(SRCROOT)/$(RULESDIR)/rules.mks
###########################################################################
