#!/bin/sh
# @(#)rmlinks	1.23 13/08/26 Copyright 1999-2013 J. Schilling

rm -f archconf.c
rm -f job.c
rm -f job.h
rm -f make.c
rm -f make.h
rm -f memory.c
rm -f parse.c
rm -f readfile.c
rm -f rules.c
rm -f update.c
rm -f include/schily/archdefs.h
rm -f include/schily/ccomdefs.h
rm -f include/schily/ctype.h
rm -f include/schily/dbgmalloc.h
rm -f include/schily/dirent.h
rm -f include/schily/dlfcn.h
rm -f include/schily/err_arch.h
rm -f include/schily/err_char.h
rm -f include/schily/err_type.h
rm -f include/schily/fcntl.h
rm -f include/schily/getargs.h
rm -f include/schily/getcwd.h
rm -f include/schily/hostname.h
rm -f include/schily/inttypes.h
rm -f include/schily/io.h
rm -f include/schily/libport.h
rm -f include/schily/limits.h
rm -f include/schily/maxpath.h
rm -f include/schily/mconfig.h
rm -f include/schily/netdb.h
rm -f include/schily/xconfig.h
rm -f include/schily/xmconfig.h
rm -f include/schily/prototyp.h
rm -f include/schily/sigblk.h
rm -f include/schily/signal.h
rm -f include/schily/standard.h
rm -f include/schily/stat.h
rm -f include/schily/stdint.h
rm -f include/schily/stdio.h
rm -f include/schily/stdlib.h
rm -f include/schily/stkframe.h
rm -f include/schily/string.h
rm -f include/schily/sunos4_proto.h
rm -f include/schily/systeminfo.h
rm -f include/schily/time.h
rm -f include/schily/unistd.h
rm -f include/schily/utime.h
rm -f include/schily/utsname.h
rm -f include/schily/utypes.h
rm -f include/schily/types.h
rm -f include/schily/param.h
rm -f include/schily/varargs.h
rm -f include/schily/vfork.h
rm -f include/schily/wait.h
rm -f include/schily/schily.h
rm -f include/schily/errno.h
rm -f include/schily/align.h
rm -f include/schily/avoffset.h
rm -f schilyio.h
rm -f config.guess
rm -f config.sub
rm -f configure
if [ -r rules.cnf.in ]; then
	rm -f rules.cnf.in
fi
if [ -r rules.cnf_in ]; then
	rm -f rules.cnf_in
fi
if [ -r xconfig.h.in ]; then
	rm -f xconfig.h.in
fi
if [ -r xconfig.h_in ]; then
	rm -f xconfig.h_in
fi
rm -f install-sh
rm -f astoi.c
rm -f astoll.c
rm -f comerr.c
rm -f eaccess.c
rm -f error.c
rm -f format.c
rm -f getexecpath.c
rm -f printf.c
rm -f sprintf.c
rm -f saveargs.c
rm -f seterrno.c
rm -f strcatl.c
rm -f strlcpy.c
rm -f strncpy.c
rm -f streql.c
rm -f fillbytes.c
rm -f getargs.c
rm -f geterrno.c
rm -f jsprintf.c
rm -f jssnprintf.c
rm -f snprintf.c
rm -f movebytes.c
rm -f raisecond.c
rm -f rename.c
rm -f searchinpath.c
rm -f cvmod.c
rm -f fcons.c
rm -f file_raise.c
rm -f fileopen.c
rm -f dat.c
rm -f fileread.c
rm -f fileseek.c
rm -f filewrite.c
rm -f flag.c
rm -f flush.c
rm -f niread.c
rm -f niwrite.c
