#!/bin/sh

. ${SRCROOT:=`../../../conf/srcroot.sh`}/tests/bin/base

admin=${dir-/usr/bin}/admin
cdc=${dir-/usr/bin}/cdc
delta=${dir-/usr/bin}/delta
get=${dir-/usr/bin}/get
help=${dir-/usr/bin}/help
prs=${dir-/usr/bin}/prs
prt=${dir-/usr/bin}/prt
rmdel=${dir-/usr/bin}/rmdel
sact=${dir-/usr/bin}/sact
sccs=${dir-/usr/bin}/sccs
sccsdiff=${dir-/usr/bin}/sccsdiff
sccslog=${dir-/usr/bin}/sccslog
unget=${dir-/usr/bin}/unget
val=${dir-/usr/bin}/val
what=${dir-/usr/bin}/what

vg_admin=${admin}
vg_cdc=${cdc}
vg_delta=${delta}
vg_get=${get}
vg_help=${help}
vg_prs=${prs}
vg_prt=${prt}
vg_rmdel=${rmdel}
vg_sact=${sact}
vg_sccs=${sccs}
vg_sccsdiff=${sccsdiff}
vg_sccslog=${sccslog}
vg_unget=${unget}
vg_val=${val}
vg_what=${what}

sccsargs=""		# We do not support CSSC --prefix=

DIFF=${DIFF-diff}
