. \" %Z%%M%	%I% %E% Copyright 1985-2018 J. Schilling
. \"  Manual page for hdump
. \"
.if t .ds a \v'-0.55m'\h'0.00n'\z.\h'0.40n'\z.\v'0.55m'\h'-0.40n'a
.if t .ds o \v'-0.55m'\h'0.00n'\z.\h'0.45n'\z.\v'0.55m'\h'-0.45n'o
.if t .ds u \v'-0.55m'\h'0.00n'\z.\h'0.40n'\z.\v'0.55m'\h'-0.40n'u
.if t .ds A \v'-0.77m'\h'0.25n'\z.\h'0.45n'\z.\v'0.77m'\h'-0.70n'A
.if t .ds O \v'-0.77m'\h'0.25n'\z.\h'0.45n'\z.\v'0.77m'\h'-0.70n'O
.if t .ds U \v'-0.77m'\h'0.30n'\z.\h'0.45n'\z.\v'0.77m'\h'-.75n'U
.if t .ds s \(*b
.if t .ds S SS
.if n .ds a ae
.if n .ds o oe
.if n .ds u ue
.if n .ds s sz
.TH HDUMP 1 "2022/09/07" "J\*org Schilling" "Schily\'s USER COMMANDS"
.SH NAME
hdump, od \- displays (dumps) binary contents of a file
.SH SYNOPSIS
.B
hdump
[\c
.I options\c
] [\c
.I file
[\c
.IR starting_address "[.][\fIb\f0|\fIB\f0] [\c"
.I count\c
]]]
.sp
.B
hdump
[\c
.I options\c
] [\c
.I file\c
\&.\&.\&.]
.sp
.B
od
[\c
.I options\c
] [\c
.I file
[\c
.IR starting_address "[.][\fIb\f0|\fIB\f0]]]"
.sp
.B
od
[\c
.I options\c
] [\c
.I file\c
\&.\&.\&.]
.sp
.B
xpg4/bin/od
[\c
.I options\c
] [\c
.I file
[\c
.IR starting_address "[.][\fIb\f0|\fIB\f0]]]"
.sp
.B
xpg4/bin/od
[\c
.I options\c
] [\c
.I file\c
\&.\&.\&.]
.sp
.SH DESCRIPTION
.PP
.B Hdump 
displays the contents of a file in 16-bit words unless
otherwise specified (see options below). It dumps the data in
hexadecimal unless otherwise specified (see options below).
.PP
.B Hdump 
assumes the 
.I "starting_address"
and the 
.I count 
are in decimal unless there is a leading 0--interpreted as octal, or a leading
0x--interpreted as hexadecimal (as in C).
If the 
.I "starting_address"
is followed by a
.IR 'b' ,
the number is multiplied by 512,
if the 
.I "starting_address"
is followed by a
.IR 'B' ,
the number is multiplied by 512.

.PP
The output radix of the label is hexadecimal by default and
may be modified by the radix of the 
.IR starting_address .
If the 
.I starting_address
is specified in hexadecimal,
the label will be displayed in hexadecimal too,
if the 
.I starting_address
is specified in octal,
the label will be displayed in octal.
A decimal radix of the label will be displayed if the
.I starting_address
is followed by a dot.
.LP
If the
.I "starting address"
is odd, it is rounded down
to the next even value.
.LP
The default size of displayed objects is
.B short
unless otherwise mentioned.
.LP
For the
.BR od (1)
features see the
.BR od (1)
man page.

.SH OPTIONS
.TP 10
.BI \-A " radix"
Select the radix used for address labels. The following values are supported:
.RS
.TP
.B d
Use a decimal radix for address labels.
.TP
.B o
Use an octal radix for address labels.
.TP
.B n
Do not print address labels.
.TP
.B x
Use a hexadecimal radix for address labels.
.RE
.TP
.B \-a
Display content also as printable characters,
set the object size to
.BR bytes .
.TP
.B \-b
Display content in
.BR bytes .
.TP
.B \-c
Display content in quoted characters,
set the object size to
.BR bytes .
.TP
.B \-C
Display bytes as single-byte or multi-byte characters
according to the current setting of the
.B LC_CTYPE
locale category.
Printable multibyte characters are written in the area
corresponding to the first byte of the character.
The two-character sequence ** is written in the area
corresponding to each remaining byte in the character,
as an indication that the character is continued.
.TP
.B \-d
Display content in decimal
.TP
.B \-f
Display content longs as floats
.TP
.B \-F
Display content double longs as doubles
.TP
.BI \-j " skip"
Seek or skip
.I skip
bytes before starting to dump.
The same syntax as with
.BR sdd (1)
is supported.
.TP
.B \-l
Display content as
.B longs
instead of using the default size
.BR short .
.TP
.BI \-N " count"
Stop after dumping
.B count
bytes.
The same syntax as with
.BR sdd (1)
is supported.
.TP
.B \-o
Display content in
.B octal
instead of using the default
.B hexadecimal
radix.
.TP
.B \-O
Interprets long words in unsigned octal.
This is equivalent to -t o4.
.TP
.B \-s
Interprets words in signed decimal.
This is equivalent to -t d2.
.TP
.B \-S
Interprets long words in signed decimal.
This is equivalent to -t d4.
.TP
.BI \-t " format"
.RS
.TP
.B a
Print bytes as 7 bit named ASCII characters.
.TP
.B c
Print bytes as quoted characters.
.TP
.B d
Print signed decimal numbers.
.TP
.B f
Print floating point numbers
.TP
.B o
Print octal numbers.
.TP
.B u
Print unsigned decimal numbers.
.TP
.B x
Print hexadecimal numbers.
.PP
The type specification characters
.BR d ,
.BR f ,
.BR o , 
.BR u ,
and
.B x
can be followed by an optional size specifier.
For the types
.BR d ,
.BR o , 
.BR u ,
and
.BR x ,
this may be one of:
.BR 1 ,
.BR 2 ,
.BR 4 ,
.BR 8 ,
.BR C ,
.BR S ,
.BR I ,
and
.BR L .
For the type
.BR f ,
this may be one of:
.BR F ,
.BR D ,
and
.BR L .
.PP
A 
.B \-t
option may have multiple type arguments and there may be multiple
.B \-t
options on the command line.
.RE
.TP
.B \-u
Display content as unsigned numbers.
.TP
.B \-v
Show all data even if it is identical.
.TP
.B \-x
Interprets words in hex.
This is equivalent to -t x2.
.TP
.B \-X
Interprets long words in hex.
This is equivalent to -t x4.
.TP
.B \-help
Prints a short summary of the 
.B hdump
options and exists.
.TP
.B \-version
Prints the 
.B hdump
version number string and exists.

.PP
Address label radix depends on starting address radix (decimal if ends with .)
\&'b' or 'B' after starting address multiplies with 512.
.SH "SEE ALSO"
.BR od (1).
.\" .SH NOTES
.SH BUGS
.PP
None currently known.
.PP
Mail bugs and suggestions to
.B schilytools@mlists.in-berlin.de
or open a ticket at
.B https://codeberg.org/schilytools/schilytools/issues
.PP
The mailing list archive may be found at:
.PP
.nf
.B
https://mlists.in-berlin.de/mailman/listinfo/schilytools-mlists.in-berlin.de
.fi
.SH AUTHORS
.nf
J\*org Schilling and the schilytools project authors.
.fi
.SH "SOURCE DOWNLOAD"
The source code for
.B hdump
is included in the
.B schilytools
project and may be retrieved from the
.B schilytools
project at Codeberg at:
.LP
.B
https://codeberg.org/schilytools/schilytools/
.LP
The download directory is:
.LP
.B
https://codeberg.org/schilytools/schilytools/releases
