. \"  Manual page for filestat
. \" @(#)filestat.3	1.2 20/02/09 Copyright 1985-2020 J. Schilling
. \"
.if t .ds a \v'-0.55m'\h'0.00n'\z.\h'0.40n'\z.\v'0.55m'\h'-0.40n'a
.if t .ds o \v'-0.55m'\h'0.00n'\z.\h'0.45n'\z.\v'0.55m'\h'-0.45n'o
.if t .ds u \v'-0.55m'\h'0.00n'\z.\h'0.40n'\z.\v'0.55m'\h'-0.40n'u
.if t .ds A \v'-0.77m'\h'0.25n'\z.\h'0.45n'\z.\v'0.77m'\h'-0.70n'A
.if t .ds O \v'-0.77m'\h'0.25n'\z.\h'0.45n'\z.\v'0.77m'\h'-0.70n'O
.if t .ds U \v'-0.77m'\h'0.30n'\z.\h'0.45n'\z.\v'0.77m'\h'-.75n'U
.if t .ds s \(*b
.if t .ds S SS
.if n .ds a ae
.if n .ds o oe
.if n .ds u ue
.if n .ds s sz
.TH FILESTAT 3 "2022/09/09" "J\*org Schilling" "Schily\'s LIBRARY FUNCTIONS"
.SH NAME
filestat() \- copies file descriptor information to buffer
.SH SYNOPSIS
.nf
.B
#include <schily/stat.h> 
.sp
.B
int filestat(f,buf)
.B	FILE *f;
.B	struct stat *buf;
.fi
.SH DESCRIPTION
.BR filestat ()
places system dependent information about the file f
into the buffer buf.
.SH RETURNS
Returns a value equal to or greater than zero when successful.
Otherwise, returns -1 and sets the standard error code.
.SH NOTES
The size and the interpretation of the buffer is system
dependent.
