. \"  Manual Page for getfiles
. \" @(#)getfiles.3	1.10 20/09/04 Copyright 1985-2020 J. Schilling
. \"
.if t .ds a \v'-0.55m'\h'0.00n'\z.\h'0.40n'\z.\v'0.55m'\h'-0.40n'a
.if t .ds o \v'-0.55m'\h'0.00n'\z.\h'0.45n'\z.\v'0.55m'\h'-0.45n'o
.if t .ds u \v'-0.55m'\h'0.00n'\z.\h'0.40n'\z.\v'0.55m'\h'-0.40n'u
.if t .ds A \v'-0.77m'\h'0.25n'\z.\h'0.45n'\z.\v'0.77m'\h'-0.70n'A
.if t .ds O \v'-0.77m'\h'0.25n'\z.\h'0.45n'\z.\v'0.77m'\h'-0.70n'O
.if t .ds U \v'-0.77m'\h'0.30n'\z.\h'0.45n'\z.\v'0.77m'\h'-.75n'U
.if t .ds s \(*b
.if t .ds S SS
.if n .ds a ae
.if n .ds o oe
.if n .ds u ue
.if n .ds s sz
.TH GETFILES 3 "2022/09/09" "J\*org Schilling" "Schily\'s LIBRARY FUNCTIONS"
.SH NAME
getfiles() \- gets next non flag-type argument
.SH SYNOPSIS
.nf
#include <schily/getargs.h>

.B
int getfiles(pac, pav, fmt)
.B
	int *pac;       /* pointer to arg count */
.B
	char *(*pav)[]; /* pointer to address of arg vector */
.B
	char *fmt;      /* format string */
.B

int getlfiles(pac, pav, props, fmt)
.B
	int *pac;       /* pointer to arg count */
.B
	char *(*pav)[]; /* pointer to address of arg vector */
.B
	struct ga_props *props; /* control properties */
.B
	char *fmt;      /* format string */

.B
int getvfiles(pac, pav, props, vfmt)
.B
	int *pac;       /* pointer to arg count */
.B
	char *(*pav)[]; /* pointer to address of arg vector */
.B
	struct ga_props *props; /* control properties */
.B
	struct ga_flags *vfmt;  /* array of formats and args */
.fi
.SH DESCRIPTION
.LP
.BR getfiles ()
is part of the advanced option parsing interface together with the
.BR getargs ()
and
.BR getallrgs ()
family.
.BR getfiles ()
skips options until a file type argument is encountered.
.LP
.BR getfiles ()
returns, with a value of
.BR "+1 " ( NOTAFLAG )
or
.BR "+2 " ( FLAGDELIM ),
whenever a non-flag type argument is encountered.
Flag-type (option) arguments, along with their
values, are ignored. The filename is at
.BR *pav[0] .
The caller must increment
.B *pav
and decrement
.B *pac
before calling
.BR getfiles ()
again.
.PP
.BR getlfiles ()
is similar to
.BR getfiles ()
but it implements an additional 
.B ga_props
parameter that must be initialized with
.BR getarginit ()
before it is passed.
.PP
.BR getvfiles ()
is similar to
.BR getlfiles ()
but uses a structure
.B ga_flags
instead of a format string and a variable arg list with pointers.
The array of structures
.BR ga_flags :
.br
.ne 8
.sp
.nf
.B
struct ga_flags {
.B
   const char  *ga_format; /* Comma separated list for one flag */
.B
   void        *ga_arg;    /* Ptr. to variable to fill for flag */
.B
   getpargfun  ga_funcp;   /* Ptr. for function to call (&/~)   */
.B
};
.fi
.sp
is terminated by an element with
.BR "ga_format == NULL" .
For a
.B ga_format
that does not expect a function pointer,
.B ga_funcp
is
.BR NULL .
.SH RETURNS
.TP 14
.B FLAGDELIM\ 2
The command line argument "\c
.B \-\-\c
"
stopped flag processing.
.TP
.B NOTAFLAG\ \ 1
The argument
.B *pav
does not appear to be a flag.
.TP
.B NOARGS\ \ \ \ 0
All arguments have been successfully examined.
.TP
.B BADFLAG\ \ \-1
A bad flag (option) argument was supplied to the program.
The argument
.B *pav
contains the offending command line argument.
.TP
.B BADFMT\ \ \-2
A bad format descriptor string has been detected.
This means an error in the calling program, not a user input data error.
.de ..
.TP
.B NOTAFILE\ \-3
A flag type argument rather than a file type argument has been detected.
..
.LP
General rules for the return code:
.TP 14
.B >\ 0
A file type argument was found.
.TP
.B \ \ 0
All arguments have been parsed.
.TP
.B <\ 0
An error occurred or not a file type argument.
.LP
Flag and file arg processing should be terminated after getting a
return code <= 0.

.\" .SH EXAMPLES
.SH "SEE ALSO"
.nh 
.sp 
.LP
.BR getallargs (3),
.BR getargerror (3),
.BR getargs (3).

.SH NOTES
Initially, 
.B *pav
must point to the first argument (not the
program name) and
.B *pac
must not count the program name. Before calling
.BR getfiles ()
again, decrement
.B *pac
and increment
.BR *pav ,
or the same name will be pointed to by
.BR *pav .

.SH BUGS
.PP
None currently known.
.PP
Mail bugs and suggestions to
.B schilytools@mlists.in-berlin.de
or open a ticket at
.BR https://codeberg.org/schilytools/schilytools/issues .
.PP
The mailing list archive may be found at:
.PP
.nf
.BR https://mlists.in-berlin.de/mailman/listinfo/schilytools-mlists.in-berlin.de .
.fi

.SH AUTHOR
J\*org Schilling and the schilytools project authors.
