#ident @(#)Makefile	1.19 09/06/30 
###########################################################################
# Sample makefile for installing non-localized auxiliary files
###########################################################################
SRCROOT=	../..
RULESDIR=	RULES
include		$(SRCROOT)/$(RULESDIR)/rules.top
###########################################################################

INSDIR=		include/schily
TARGET=		align.h
XMK_FILE=	\
		align.mk alloca.mk archdefs.mk avoffset.mk btorder.mk \
		ccomdefs.mk checkerr.mk \
		deflts.mk device.mk dirent.mk dlfcn.mk errno.mk fcntl.mk \
		fetchdir.mk find.mk fnmatch.mk fstream.mk \
		getargs.mk getcwd.mk \
		hostname.mk \
		iconv.mk idcache.mk intcvt.mk ioctl.mk \
		jmpdefs.mk \
		libport.mk librmt.mk limits.mk locale.mk \
		maxpath.mk mconfig.mk \
		md4.mk md5.mk \
		mman.mk mtio.mk nlsdefs.mk param.mk patmatch.mk prototyp.mk \
		rmtio.mk schily.mk schilyp.mk \
		shcall.mk \
		siconv.mk sigblk.mk signal.mk sigset.mk standard.mk stat.mk \
		stdio.mk \
		stdlib.mk stkframe.mk string.mk \
		sysexits.mk \
		termcap.mk termios.mk time.mk \
		types.mk unistd.mk utime.mk utypes.mk varargs.mk \
		walk.mk wchar.mk wctype.mk wait.mk \
		xconfig.mk xmconfig.mk

###########################################################################
include		$(SRCROOT)/$(RULESDIR)/rules.aux
###########################################################################
