# @(#)Makefile.warn	1.2 15/08/05 Copyr 2000-2015 J. Schilling

SRCROOT=	..
RULESDIR=	RULES
include		$(SRCROOT)/$(RULESDIR)/rules.top

$(ALLTARGETS):
	@echo
	@echo
	@echo "Don't forget to install the helper files from dotfiles.tar ..."
	@echo
	@echo
