#!/bin/sh

SRCROOT=`../../../../conf/srcroot.sh`
. ${SRCROOT}/tests/bin/base

. ../common/command-names

TESTING_CSSC=false
TESTING_REAL_CSSC=false
TESTING_REAL_SCCS=false

if ( ${admin} -V 2>&1 ; echo xxx ) 2>/dev/null | grep CSSC >/dev/null
then
	TESTING_CSSC=true
	TESTING_REAL_CSSC=true
fi

if ( ${admin} -V 2>&1 ; echo xxx ) 2>/dev/null | grep SCCS >/dev/null
then
	if test ".$CSSC_ONLY" = ".true"
	then
		:
	else
		TESTING_CSSC=true
	fi
	TESTING_REAL_SCCS=true
fi
