. \" @(#)pxupgrade.1	1.3 10/05/11 Copyright 1985-2010 J. Schilling
. \"  Manual page for pxupgrade
. \"
.if t .ds a \v'-0.55m'\h'0.00n'\z.\h'0.40n'\z.\v'0.55m'\h'-0.40n'a
.if t .ds o \v'-0.55m'\h'0.00n'\z.\h'0.45n'\z.\v'0.55m'\h'-0.45n'o
.if t .ds u \v'-0.55m'\h'0.00n'\z.\h'0.40n'\z.\v'0.55m'\h'-0.40n'u
.if t .ds A \v'-0.77m'\h'0.25n'\z.\h'0.45n'\z.\v'0.77m'\h'-0.70n'A
.if t .ds O \v'-0.77m'\h'0.25n'\z.\h'0.45n'\z.\v'0.77m'\h'-0.70n'O
.if t .ds U \v'-0.77m'\h'0.30n'\z.\h'0.45n'\z.\v'0.77m'\h'-.75n'U
.if t .ds s \(*b
.if t .ds S SS
.if n .ds a ae
.if n .ds o oe
.if n .ds u ue
.if n .ds s sz
.TH PXUPGRADE 1 "2022/08/20" "J\*org Schilling" "Schily\'s USER COMMANDS"
.SH NAME
pxupgrade \- upgrade firmware in Plextor CD/DVD writers
.SH SYNOPSIS
.B pxupgrade
[
.I options
]
[
.BI dev= device
]
.I firmware_file
.SH DESCRIPTION
Pxupgrade is used to update the firmware in Plextor CD and DVD writers
as well as in the PX-40 CD-ROM drive.
.PP
See
.B OPTIONS
and
.B EXAMPLES
section to lean about possible usage.
.PP
.SS "Device naming"
Most users do not need to care about device naming at all, as
.B pxupgrade
implements
.B auto target
support and automagically finds Plextor drives.
.PP
The
.I device
refers to
.IR scsibus / target / lun
of the CD/DVD-Recorder. Communication on
.I SunOS
is done with the SCSI general driver
.B scg.
Other operating systems are using a library simulation of this driver.
Possible syntax is:
.B dev=
.IR scsibus , target , lun
or
.B dev=
.IR target , lun .
In the latter case, the CD/DVD-Recorder has to be connected to the default
SCSI bus of the machine.
.IR Scsibus ,
.I target
and
.I lun
are integer numbers.
Some operating systems or SCSI transport implementations may require to
specify a filename in addition.
In this case the correct syntax for the device is:
.B dev=
.IR devicename : scsibus , target , lun
or
.B dev=
.IR devicename : target , lun .
If the name of the device node that has been specified on such a system
refers to exactly one SCSI device, a shorthand in the form
.B dev=
.IR devicename : @
or
.B dev=
.IR devicename : @ , lun
may be used instead of
.B dev=
.IR devicename : scsibus , target , lun .

.PP
To access remote SCSI devices, you need to prepend the SCSI device name by
a remote device indicator. The remote device indicator is either
.BI REMOTE: user@host:
or
.BR
.BI REMOTE: host:
.br
A valid remote SCSI device name may be:
.BI REMOTE: user@host:
to allow remote SCSI bus scanning or
.BI REMOTE: user@host:1,0,0
to access the SCSI device at
.I host
connected to SCSI bus # 1,target 0 lun 0.

.PP
.B Pxupgrade
is completely based on
.B SCSI
commands but this is no problem as all CD/DVD writers
ever made use
.B SCSI
commands for the communication. Even
.B ATAPI
drives are just
.B SCSI
drives that inherently use the
.I "ATA packet interface"
as
.B SCSI
command transport layer build into the IDE (ATA) transport.
You may need to specify an alternate transport layer on the command  line
if your OS does not implement a fully integrated kernel driver subsystem that
allows one to access any drive using
.B SCSI
commands via a single unique user interface.

.PP
To access SCSI devices via alternate transport layers,
you need to prepend the SCSI device name by a transport layer indicator.
The transport layer indicator may be something like
.B USCSI:
or
.BR ATAPI: .
To get a list of supported transport layers for your platform, use
.B dev=
.IR HELP :


.PP
To make
.B pxupgrade
portable to all \s-2UNIX\s0 platforms, the syntax
.B dev=
.IR devicename : scsibus , target , lun
is preferred as it hides OS specific knowledge about device names from the user.
A specific OS may not necessarily support a way to specify a real device file name nor a
way to specify
.IR scsibus , target , lun .

.PP
.I Scsibus
0 is the default SCSI bus on the machine. Watch the boot messages for more
information or look into
.B /var/adm/messages
for more information about the SCSI configuration of your machine.
If you have problems to figure out what values for
.IR scsibus , target , lun
should be used, try the
.B \-scanbus
option of
.B cdrecord
described below.

.SH OPTIONS
.TP
.B \-all
Upgrade all drives which may be upgraded using the specified upgrade file.
.TP
.BI dev= target
Sets the SCSI target for the CD/DVD-Recorder, see notes above.
A typical device specification is
.BI dev= 6,0
\&.
If a filename must be provided together with the numerical target
specification, the filename is implementation specific.
The correct filename in this case can be found in the system specific
manuals of the target operating system.
On a
.I FreeBSD
system without
.I CAM
support, you need to use the control device (e.g.
.IR /dev/rcd0.ctl ).
A correct device specification in this case may be
.BI dev= /dev/rcd0.ctl:@
\&.
.sp
On Linux, drives connected to a parallel port adapter are mapped
to a virtual SCSI bus. Different adapters are mapped to different
targets on this virtual SCSI bus.
.TP
.B \-l
List all Plextor drives with their current firmware version.
This works only if the current OS platform allows SCSI bus scanning
for user programs.
.TP
.B \-help
Prints a short summary of the
.B pxupgrade
options and exists.
.TP
.B \-version
Prints the
.B pxupgrade
version number string and exists.

.SH EXAMPLES
.PP
Use
.PP
.B "   pxupgrade \-all    r412c106.bin"
.PP
to upgrade all Plextor PX-W412 drives that may be found using the
SCSI scan bus function of the OS.
.PP
Use
.PP
.B "   pxupgrade dev=3,0 r412c106.bin"
.PP
to upgrade the Plextor PX-W412 drive at target 3 lun 0.
.PP
Use
.PP
.B "   pxupgrade \-l"
.PP
to list all Plextor drives with their firmware if the OS supports
SCSU bus scanning.
.PP
Use
.PP
.B "  pxupgrade dev=USCSI \-l"
.PP
to list all Plextor drives with their firmware using the alternate
SCSU transport method
.BR USCSI .
.PP
Use
.PP
.B "   pxupgrade dev=IOCompactDiscServices \-l"
.PP
On MacOS X to list the first CD-ROM drive in the system.

.SH NOTES
If the update is done with an ATAPI drive and DMA is active,
it is likely that the drive will hang after the firmware update as
this operation puts the drive in PIO mode.
