#ident @(#)Makefile	1.2 17/04/25 
###########################################################################
# Sample makefile for sub directory makes
###########################################################################
SRCROOT=	../..
RULESDIR=	RULES
include		$(SRCROOT)/$(RULESDIR)/rules.top
###########################################################################

DIRS=		lib/bsd/src lib/mksh/src lib/vroot/src \
		lib/makestate/src \
		bin/make/common

###########################################################################
include		$(SRCROOT)/$(RULESDIR)/rules.dir
###########################################################################
