#!/bin/sh
###########################################################################
#ident "@(#)MKLINKS	1.4 18/04/09 "
###########################################################################
# Written 2008-2011 by J. Schilling
###########################################################################
# Copyright (c) 2008-2011 J. Schilling
###########################################################################
#@@C@@
###########################################################################
symlink="ln -s"
MKLINKS_TEST=${MKLINKS_TEST-:}
if [ ".$MKLINKS_COPY" = '.' ]; then
	rm -f xxzzy.123 xxzzy.345
	echo test > xxzzy.123
	$symlink xxzzy.123 xxzzy.345
	test $? = 0 || symlink=cp
	test -r xxzzy.345 || symlink=cp
	${MKLINKS_TEST} -h xxzzy.345 || symlink=cp
	rm -f xxzzy.123 xxzzy.345
else
	symlink=cp
fi
###########################################################################

$symlink	../lib/align_test.c	.
$symlink	../lib/avoffset.c	.
$symlink	../lib/getfp.c		.
$symlink	../lib/fpoff.c		.
