#!/bin/sh
###########################################################################
#ident "@(#)MKLINKS	1.5 15/03/25 "
###########################################################################
# Written 2008-2015 by J. Schilling
###########################################################################
# Copyright (c) 2008-2015 J. Schilling
###########################################################################
#@@C@@
###########################################################################
if [ -r ldummy.lnk ]; then
	if [ $# -le 0 ]; then
		exit 0
	fi
fi
###########################################################################
symlink="ln -s"
MKLINKS_TEST=${MKLINKS_TEST-:}
if [ ".$MKLINKS_COPY" = '.' ]; then
	rm -f xxzzy.123 xxzzy.345
	echo test > xxzzy.123
	$symlink xxzzy.123 xxzzy.345
	test $? = 0 || symlink=cp
	test -r xxzzy.345 || symlink=cp
	${MKLINKS_TEST} -h xxzzy.345 || symlink=cp
	rm -f xxzzy.123 xxzzy.345
else
	symlink=cp
fi
###########################################################################

$symlink Makefile.cmd	ldummy.lnk
$symlink Makefile.cmd	cmd.mk
$symlink Makefile.inc	inc.mk
$symlink Makefile.lib	lib.mk
$symlink Makefile.shl	shl.mk

$symlink temp-clang.rul	temp-clang32.rul
$symlink temp-clang.rul	temp-clang64.rul

$symlink temp-gcc.rul	temp-gcc32.rul
$symlink temp-gcc.rul	temp-gcc64.rul
