. \" @(#)mountcd.1	1.3 10/05/11 Copyright 2005-2010 J. Schilling */
. \"  Manual page for mountcd
. \"
.if t .ds a \v'-0.55m'\h'0.00n'\z.\h'0.40n'\z.\v'0.55m'\h'-0.40n'a
.if t .ds o \v'-0.55m'\h'0.00n'\z.\h'0.45n'\z.\v'0.55m'\h'-0.45n'o
.if t .ds u \v'-0.55m'\h'0.00n'\z.\h'0.40n'\z.\v'0.55m'\h'-0.40n'u
.if t .ds A \v'-0.77m'\h'0.25n'\z.\h'0.45n'\z.\v'0.77m'\h'-0.70n'A
.if t .ds O \v'-0.77m'\h'0.25n'\z.\h'0.45n'\z.\v'0.77m'\h'-0.70n'O
.if t .ds U \v'-0.77m'\h'0.30n'\z.\h'0.45n'\z.\v'0.77m'\h'-.75n'U
.if t .ds s \(*b
.if t .ds S SS
.if n .ds a ae
.if n .ds o oe
.if n .ds u ue
.if n .ds s sz
.TH MOUNTCD 1 "2022/08/21" "J\*org Schilling" "Schily\'s USER COMMANDS"
.SH NAME
mountcd \- shows where two files differ
.SH SYNOPSIS
.B
.B mountcd
[ 
.I options 
]
.I device path \|.\|.\|.
.SH DESCRIPTION
.B mountcd
mounts a ISO-9660 CD or DVD from a list of device paths.
The medium is mounted to the directory
.B /.cdrom
that is created if it does not yet exist.
.PP
If no path list is specified, the directory
.B /dev/dsk/
is scanned for possible target paths.
.SH OPTIONS
.TP
.B \-debug
print debug information while selecting the right device path.
.TP
.B \-help
Prints a short summary of the 
.B mountcd
options and exists.
.TP
.B \-version
Prints the
.B mountcd
version number string and exists.
.TP
.BI V= volume-ID
The ISO-9660 volume ID to look for. If no
.B V= 
option has been specified, the first device path is mounted.
.SH NOTES
Only works on Solaris.

.SH BUGS
.PP
None currently known.
.PP
Mail bugs and suggestions to
.B schilytools@mlists.in-berlin.de
or open a ticket at
.BR https://codeberg.org/schilytools/schilytools/issues .
.PP
The mailing list archive may be found at:
.PP
.nf
.BR https://mlists.in-berlin.de/mailman/listinfo/schilytools-mlists.in-berlin.de .
.fi

.SH AUTHORS
J\*org Schilling and the schilytools project authors.

.SH "SOURCE DOWNLOAD"
The source code for
.B mountcd
is included in the
.B schilytools
project and may be retrieved from the
.B schilytools
project at Codeberg at
.LP
.BR https://codeberg.org/schilytools/schilytools .
.LP
The download directory is
.LP
.BR https://codeberg.org/schilytools/schilytools/releases .
