#!/bin/sh
###########################################################################
#ident "@(#)MKLINKS	1.9 18/06/26 "
###########################################################################
# Written 2008-2018 by J. Schilling
###########################################################################
# Copyright (c) 2008-2018 J. Schilling
###########################################################################
#@@C@@
###########################################################################
symlink="ln -s"
MKLINKS_TEST=${MKLINKS_TEST-:}
if [ ".$MKLINKS_COPY" = '.' ]; then
	rm -f xxzzy.123 xxzzy.345
	echo test > xxzzy.123
	$symlink xxzzy.123 xxzzy.345
	test $? = 0 || symlink=cp
	test -r xxzzy.345 || symlink=cp
	${MKLINKS_TEST} -h xxzzy.345 || symlink=cp
	rm -f xxzzy.123 xxzzy.345
else
	symlink=cp
fi
###########################################################################

$symlink ../bsh/abbrev.h			.
$symlink ../bsh/signames.c		.

$symlink ../sh/bosh.h			.
$symlink ../sh/ctype.h			.
$symlink ../sh/defs.h			.
$symlink ../sh/dup.h			.
$symlink ../sh/hash.h			.
$symlink ../sh/jobs.h			.
$symlink ../sh/mac.h			.
$symlink ../sh/mode.h			.
$symlink ../sh/name.h			.
$symlink ../sh/sh_policy.h		.
$symlink ../sh/stak.h			.
$symlink ../sh/sym.h			.
$symlink ../sh/timeout.h		.
$symlink ../sh/version.h		.

$symlink ../bsh/abbrev.c			.

$symlink ../sh/alias.c			.
$symlink ../sh/args.c			.
$symlink ../sh/bltin.c			.
$symlink ../sh/cmd.c			.
$symlink ../sh/ctype.c			.
$symlink ../sh/defs.c			.
$symlink ../sh/echo.c			.
$symlink ../sh/error.c			.
$symlink ../sh/expand.c			.
$symlink ../sh/fault.c			.
$symlink ../sh/func.c			.
$symlink ../sh/gmatch.c			.
$symlink ../sh/hash.c			.
$symlink ../sh/hashserv.c		.
$symlink ../sh/io.c			.
$symlink ../sh/jobs.c			.
$symlink ../sh/macro.c			.
$symlink ../sh/main.c			.
$symlink ../sh/msg.c			.
$symlink ../sh/name.c			.
$symlink ../sh/optget.c			.
$symlink ../sh/print.c			.
$symlink ../sh/printf.c			.
$symlink ../sh/pwd.c			.
$symlink ../sh/service.c		.
$symlink ../sh/sh_policy.c		.
$symlink ../sh/stak.c			.
$symlink ../sh/strexpr.c			.
$symlink ../sh/string.c			.
$symlink ../sh/test.c			.
$symlink ../sh/ulimit.c			.
$symlink ../sh/umask.c			.
$symlink ../sh/word.c			.
$symlink ../sh/xec.c			.
