. \" @(#)sdd.1	1.11 20/05/30 Copyr 1982-1995,2020 J. Schilling
. \"                          Copyr 2022           the schilytools team
. \"  Manual page for sdd
. \"
.if t .ds a \v'-0.55m'\h'0.00n'\z.\h'0.40n'\z.\v'0.55m'\h'-0.40n'a
.if t .ds o \v'-0.55m'\h'0.00n'\z.\h'0.45n'\z.\v'0.55m'\h'-0.45n'o
.if t .ds u \v'-0.55m'\h'0.00n'\z.\h'0.40n'\z.\v'0.55m'\h'-0.40n'u
.if t .ds A \v'-0.77m'\h'0.25n'\z.\h'0.45n'\z.\v'0.77m'\h'-0.70n'A
.if t .ds O \v'-0.77m'\h'0.25n'\z.\h'0.45n'\z.\v'0.77m'\h'-0.70n'O
.if t .ds U \v'-0.77m'\h'0.30n'\z.\h'0.45n'\z.\v'0.77m'\h'-0.75n'U
.if t .ds s \\(*b
.if t .ds S SS
.if n .ds a ae
.if n .ds o oe
.if n .ds u ue
.if n .ds s sz
.TH SDD 1E "2022/10/12" "J\*org Schilling" "Schily\'s USER COMMANDS"
.SH NAME
sdd \- disk dump and restore to and from tape or file; copy and/or reblock
.SH SYNOPSIS
.B
sdd
[
.BR option "=value"
] [
.B \-flag
]
.SH DESCRIPTION
.I sdd
copies the specified input file to a specified output file performing the
requested conversions. The standard input and output are used by default.
The input and output block size may be specified to take advantage of
raw physical I/O.
.PP
After completion, sdd reports the number of whole records, the sum of bytes 
from partial input and output blocks and the total amount in kilo
bytes on input and output.
.PP 
If
.I ibs
and
.I obs
differ,
.I sdd
is faster than
.I dd
due to the use of an intelligent algorithm.
.SH OPTIONS
.TP
.B \-help
Print a summary of the available options.
.TP
.BI if= name
Input is taken from file
.I name;
default is
.I stdin.
.sp
If 
.B sdd
is installed suid root,
.I name
may be in remote syntax: user@host:filename as in 
.BR rcp (1)
even if 
invoked by non root users.
See SUID NOTES for more information.
.sp
To make a file local although it includes a colon (:), the filename
must start with:
.IR "'/'" ,
.IR "'./'" " or"
.I "'../'"
.TP
.BI of= name
Output is taken from file
.I name;
default is
.I stdout.
Note that
.I sdd
creates and truncates the output file by default; therefore the
.I oseek=#
option is useless without the
.I \-notrunc
option except in special cases such as using magnetic tape or disk 
special files.
.sp
If 
.B sdd
is installed suid root,
.I name
may be in remote syntax: user@host:filename as in 
.BR rcp (1)
even if 
invoked by non root users.
.sp
Note that if
.B sdd
talks to an old 
.B rmt
remote tape server, it does not open a remote file with the 
.B O_CREAT
open flag because this would be extremely dangerous.
If the 
.B rmt 
server on the other side is the 
.B rmt
server that comes with 
.B star
or the GNU
.B rmt
server,
.B sdd
may use the symbolic mode for the open flags.
Only the symbolic open modes allow sending all possible open
modes in a portable way to remote tape servers.
.sp
It is recommended to use the 
.B rmt
server that comes with
.BR star .
It is the only
.B rmt
server that gives platform independent compatibility with BSD, Sun and GNU
.B rmt 
clients and it includes security features that may be set up in /etc/default/rmt.

.TP
.B \-inull
Do not read input from file.
This is similar to if=/dev/zero but much faster.
.I sdd
uses a prepared cleared buffer to satisfy writes.
.TP
.B \-onull
Do not produce any output. This is similar to
.BI of= /dev/null
but actually does not write to any file.
.TP
.BI ibs= "#, " obs= "#, " bs= #
Set input block size, output block size or both to #
(default 512 Bytes).
.TP
.BI cbs= #
Set Conversion buffer size to #.
.TP
.BI ivsize= "#, " ovsize= #
Set input volume size or output volume size to #. You can make copies from
devices of different size by using this option. If you want to make a copy
to a tape having a size of 60 MBytes you should use the option
.BI ovsize= 60M.
If the capacity of the tape is exceeded,
.I sdd
will ask for a second volume. In case
.I ivsize
is exceeded, if 
.I "N<cr>"
is typed, it is treated as an EOF condition and
.I sdd
writes any buffered data to output and exits. In case
.I ovsize
is exceeded, if
.I "N<cr>"
is typed,
.I sdd
stops and the statistics it prints show that more data were read than written.
.TP
.BI count= #
Transfer # of input records or until EOF.
.TP
.BI iseek= "#, " iskip= #
Seek/skip the first # Bytes from input before beginning transfer.
.TP
.BI oseek= "#, " oskip= #
Seek/skip the first # Bytes from output before beginning transfer.
.TP
.BI seek= "#, " skip= #
Seek/skip the first # Bytes from input and output before beginning transfer.
.TP
.BI ivseek= "#, " ovseek= #
Seek
.I #
Bytes from input/output at the beginning of each input/output volume before
beginning transfer. (You can skip labels of disks and floppies with 
this option.)
Note that the
.I iseek/oseek
options still work, but only apply to the first volume.
Their values are added to the values of
.I ivseek
and
.I ovseek.
.TP
.B \-notrunc
Do not truncate an already existing output file before beginning transfer.
This enables it to copy one file into another.
.TP
.B \-pg
Print a dot to
.I stderr
each time a record is written to indicate progress.
.TP
.BI secsize= #
Set the basic buffersize for error recovery via
.B \-noerror
to
.IR #.
The default is 512 to match the most usual physical sector size.
Since error recovery is done at the level of the basic buffer size, you need
to use this option in error recovery mode in case you are accessing a drive
with a different physical sector size than 512 bytes.
.TP
.BR \-time ", " \-t
Report the total time and the transfer rate.
.TP
.B \-noerror
Do not stop transfer on I/O errors. Error messages will appear on the screen.
If this option is used and
.B \-noseek
has not been specified as well,
.B ibs
and
.B obs
need to be multiples of the error recovery blocksize specified via
.BI secsize= #\c
\&.
.TP
.B \-noerrwrite
Do not write blocks that are not read correctly. Seek on the output to skip
the bad block.
The output file must be seekable or 
.B \-noerrwrite
will not work correctly.
.TP
.B \-noseek
Do not
.I seek
after I/O errors. This implies
.I try=1.
.TP
.BI try= #
Set retry count to
.I #.
Only if
.B \-noerror
was specified. (default 2)
.TP
.B \-debug
Turn on debugging messages. You can get knowledge about record sizes on
tapes with variable record size with this option.
.TP
.B \-fill
Pad every output record with zeros up to
.I obs.
If
.I ibs
equals
.I obs,
or only
.I bs
was specified, every record will be padded with zeros, otherwise this only
applies to the last record.
.TP
.B \-swab
Swaps bytes (except for the last byte in odd block sizes and odd transfers
due to EOF).
.TP
.BR \-block ", " \-unblock
Convert fixed length records to variable records and vice versa.
.TP
.BR \-lcase ", " \-ucase
Map alphabetics to lower/upper case.
.TP
.BR \-ascii ", " \-ebcdic ", " \-ibm
Convert
.I EBCDIC
to
.I ASCII
resp.
.I ASCII
to
.I EBCDIC
resp.
.I ASCII
to the
.I IBM
variant of
.I EBCDIC.
.TP
.B \-help
Prints a short summary of the 
.B sdd
options and exists.
.TP
.B \-md5
Compute the md5 sum for the data.
If the option
.B \-onull
was used,
.B sdd
computes the md5 sum on the input data, otherwise the output data is used.
.TP
.BI rsh= path
Specify a remote login program instead of defaulting to
.BR ssh (1).
This can be overridden by the
.I RSH
environment variable.
.TP
.B \-version
Prints the 
.B sdd
version number string and exists.
.
.SH EXAMPLES
.B sdd if=/dev/rsd0a of=/dev/nrst8 bs=2x7x17b
.PP
Copies the disk
.I /dev/rsd0a
to the tape
.I /dev/nrst8
using a record size of 2\|*\|7\|*\|17 blocks.
(this is 2 Cylinders.)
.PP
.B sdd if=/dev/rsd0c of=/dev/rsd1c seek=1b bs=63k
.PP
Copy the whole disk
.I sd0
to
.I sd1
preserving the old label on disk
.I sd1.
.PP
.B sdd if=user@remotehost:/dev/da0 of=/dev/ada1 bs=512 -pg
.PP
Copy the entire disk
.I da0
on host
.I remotehost
as user
.I user
to the disk
.I ada1
on the local host using a block size of 512 while printing a progress
with dots. This command defaults to using
.BR ssh (1).
If you want to use a different remote shell, either give
.B sdd
the
.BI rsh= prog
option or set
.I RSH
to the desired shell program.
.PP
.\" .SH FILES
.SH "SEE ALSO"
dd(1), star(1), rmt(1), tr(1), cp(1), copy(1)
.SH DIAGNOSTICS
sdd: Read  f records + p bytes (total of x bytes = d.nnk).
.br
sdd: Wrote f records + p bytes (total of x bytes = d.nnk).
.PP
The number of full records, the number of bytes in partial records
and the total amount of data in KBytes.
.PP
With the
.I QUIT
signal ( usually ^\\ ) the actual state is displayed.
.SH NOTES
Opposed to
.I dd, sdd
is able to handle
.I \-iseek \-oseek \-seek
as well as
.I \-iskip \-oskip \-skip
regardless to the buffer size. You can make a whole physical copy of a disk
without copying the label in one pass of
.I sdd.
.PP
When numbers are unspecified the are taken to be bytes.
.PP
You can make them `words' (2 bytes) if they are followed by a `w' or `W'.
.PP
You can make them blocks (512 bytes) if they are followed by a `b' or `B'.
.PP
You can make them Kbytes (1024 bytes) if they are followed by a `k' or `K'.
.PP
You can make them Mbytes (1024 * 1024 bytes) if they are followed by
a `m' or `M'.
.PP
You can make them Gbytes (1024 * 1024 *1024 bytes) if they are followed by
a `g' or `G'.
.PP
A pair of numbers may be separated by `*' or `x' to indicate a product.
.SH "SUID NOTES"
If
.B sdd
is installed suid root, 
.B sdd
is able to make connections to remote files for non root users. 
This is done by using the
.BR rcmd (3)
interface to get a connection to a
.BR rmt (1)
server.
It defaults to using
.BR ssh (1)
to establish the remote connection.
.PP
.B sdd
resets its effective uid back to the real user id immediately after setting up
the remote connection to the rmt server and before opening any other file.
.SH BUGS
The option
.BI iskip= #
and
.BI oskip= #
and
.BI skip= #
as well as
.B \-block
and
.B \-unblock
are not implemented.
.PP
It is confusing to allow the use of all additions together with the
record counter
.I \-count
as they are possible with
.BI obs= #.

Mail other bugs and suggestions to
.B schilytools@mlists.in-berlin.de
or open a ticket at
.BR https://codeberg.org/schilytools/schilytools/issues .
.PP
The mailing list archive may be found at:
.PP
.nf
.BR https://mlists.in-berlin.de/mailman/listinfo/schilytools-mlists.in-berlin.de .
.fi

.SH AUTHORS
J\*org Schilling and the schilytools project authors.

.SH "SOURCE DOWNLOAD"
The source code for
.B sdd
is included in the
.B schilytools
project and may be retrieved from the
.B schilytools
project at Codeberg at
.LP
.BR https://codeberg.org/schilytools/schilytools .
.LP
The download directory is
.LP
.BR https://codeberg.org/schilytools/schilytools/releases .
