#ident @(#)Makefile	1.2 07/01/07 
###########################################################################
# Sample makefile for sub-makes in one directory
###########################################################################
SRCROOT=	../../..
RULESDIR=	RULES
include		$(SRCROOT)/$(RULESDIR)/rules.top
###########################################################################

MK_FILES=	ad.mk bd.mk cb.mk cm.mk cmds.mk co.mk de.mk default.mk ge.mk he.mk prs.mk rc.mk un.mk ut.mk va.mk vc.mk


###########################################################################
include		$(SRCROOT)/$(RULESDIR)/rules.mks
###########################################################################
