#ident "@(#)Makefile	1.1 15/08/11 "
###########################################################################
# Sample makefile for installing localized shell scripts
###########################################################################
SRCROOT=	..
RULESDIR=	RULES
include		$(SRCROOT)/$(RULESDIR)/rules.top
###########################################################################

INSDIR=		bin
INSMODE=	0755
TARGET=		man2html
SCRFILE=	man2html
XMK_FILE=	Makefile.man

###########################################################################
include		$(SRCROOT)/$(RULESDIR)/rules.scr
###########################################################################
