#ident "%W% %E% %Q%"
###########################################################################
SRCROOT=	../..
RULESDIR=	RULES
include		$(SRCROOT)/$(RULESDIR)/rules.top
###########################################################################

all:
	cd shelltests && $(MAKE)
	@echo "Watch for FAIL and XFAIL in the output"
