#ident "@(#)Makefile	1.1 16/04/08 "
###########################################################################
SRCROOT=	../..
RULESDIR=	RULES
include		$(SRCROOT)/$(RULESDIR)/rules.top
###########################################################################

all:
	cd shelltests && $(MAKE)
	@echo "Watch for FAIL and XFAIL in the output"
