. \" @(#)compare.1	1.9 20/09/16 Copyr 1982-2019 J. Schilling
. \"  Manual page for compare
. \"
.if t .ds a \v'-0.55m'\h'0.00n'\z.\h'0.40n'\z.\v'0.55m'\h'-0.40n'a
.if t .ds o \v'-0.55m'\h'0.00n'\z.\h'0.45n'\z.\v'0.55m'\h'-0.45n'o
.if t .ds u \v'-0.55m'\h'0.00n'\z.\h'0.40n'\z.\v'0.55m'\h'-0.40n'u
.if t .ds A \v'-0.77m'\h'0.25n'\z.\h'0.45n'\z.\v'0.77m'\h'-0.70n'A
.if t .ds O \v'-0.77m'\h'0.25n'\z.\h'0.45n'\z.\v'0.77m'\h'-0.70n'O
.if t .ds U \v'-0.77m'\h'0.30n'\z.\h'0.45n'\z.\v'0.77m'\h'-.75n'U
.if t .ds s \(*b
.if t .ds S SS
.if n .ds a ae
.if n .ds o oe
.if n .ds u ue
.if n .ds s sz
.TH COMPARE 1L "2022/07/17" "J\*org Schilling" "Schily\'s USER COMMANDS"
.SH NAME
compare \- fast binary comparison of two files
.SH SYNOPSIS
.B compare
[
.I options
] 
.I file1 file2
.SH DESCRIPTION
.B Compare
examines one file and standard in, or two files on a
byte by byte basis, and prints the file position of the first
difference it finds, first in decimal and then in hexadecimal,
followed by the differing byte content in hexadecimal and as 
quoted character.
.PP
.B Compare 
is similar to the UNIX utility
.BR cmp (1)
but faster.
.PP
The lines count from 1, the byte offset counts from 0.
This is a deviation from the UNIX 
.BR cmp (1)
utility, which counts byte offsets beginning from 1.
.SH OPTIONS
Note all options can be abbreviated to their first letter.
.br
.ne 3
.TP
.B "\-all, \-a, \-long, \-l"
Do not stop comparing the files if the first difference is found.
.br
.ne 3
.TP
.BR "\-lines, \-L"
Count lines while comparing data.
This slows down the process of comparison by a factor of two.
The line count starts after the optional initial skip on a file.
.PD 0
.br
.ne 5
.TP
.BR b= "#"
.TP
.BR begin= "#"
.PD
Start comparing at byte n, otherwise at byte 0.
.PD 0
.br
.ne 5
.TP
.BR b1= "#"
.TP
.BR begin1= "#"
.PD
Start comparing file 1 at byte n, otherwise at byte 0.
.PD 0
.br
.ne 5
.TP
.BR b2= "#"
.TP
.BR begin2= "#"
.PD
Start comparing fle 2 at byte n, otherwise at byte 0.
.PD 0
.br
.ne 5
.TP
.BR c= "#"
.TP
.BR count= "#"
.PD
Stops after comparing n bytes, otherwise if the first files encounters EOF.
.br
.ne 3
.TP
.B \-silent
Does not print messages, just returns the exit code.
.br
.ne 3
.TP
.B \-help
Prints a short summary of the 
.B compare
options and exists.
.br
.ne 3
.TP
.B \-version
Prints the 
.B compare
version number string and exists.
.SH NOTES
numbers in the options
.BI begin= #\fR,
.BI begin1= #\fR,
.BI begin2= #\fR,
and
.BI count= #
are assumed to be
bytes. However typing the character
.RB ' b '
after the number means
blocks (512 bytes). (E.g. begin=6b count=1000b). Other 
suffixes may used as for the 
.B bs=
option in
.BR sdd (1)
.RB ' k '
means 1024 bytes,
.RB ' m '
means 1024 KBytes.
.SH BUGS
Not known.
.SH HISTORY
.LP
.BR compare (1)
was initially written by J\*org Schilling in 1985 and has been
maintained ever since by J\*org Schilling.
.LP
.SH AUTHORS
.nf
J\*org Schilling and the schilytools project authors.
.fi
.PP
Mail bugs and suggestions to:
.PP
.B
schilytools@mlists.in-berlin.de
.PP
or open a ticket at:
.PP
.B
https://codeberg.org/schilytools/schilytools/issues
.PP
The mailing list archive may be found at:
.PP
.B
https://mlists.in-berlin.de/mailman/listinfo/schilytools-mlists.in-berlin.de
.LP
.SH "SOURCE DOWNLOAD"
The source code for
.B compare
is included in the
.B schilytools
project and may be retrieved from the
.B schilytools
project at Codeberg at:
.LP
.B
https://codeberg.org/schilytools/schilytools/
.LP
The download directory is:
.LP
.B
https://codeberg.org/schilytools/schilytools/releases
